! ###################################################################
! Copyright (c) 2015-2021, Marc De Graef Research Group/Carnegie Mellon University
! All rights reserved.
!
! Redistribution and use in source and binary forms, with or without modification, are
! permitted provided that the following conditions are met:
!
!     - Redistributions of source code must retain the above copyright notice, this list
!        of conditions and the following disclaimer.
!     - Redistributions in binary form must reproduce the above copyright notice, this
!        list of conditions and the following disclaimer in the documentation and/or
!        other materials provided with the distribution.
!     - Neither the names of Marc De Graef, Carnegie Mellon University nor the names
!        of its contributors may be used to endorse or promote products derived from
!        this software without specific prior written permission.
!
! THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
! AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
! IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
! ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
! LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
! DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
! SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
! CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
! OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
! USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
! ###################################################################

!--------------------------------------------------------------------------
! EMsoft:EMEBSDDI.f90
!--------------------------------------------------------------------------
!
! PROGRAM: EMEBSDDI
!
!> @author Saransh Singh/Marc De Graef, Carnegie Mellon University
!
!> @brief Indexing of EBSD patterns using the dictionary approach. Later, this program
!> will be used for dynamic pattern center correction to hopefully make
!> the dictionary indexing even more robust.
!
!> @date 03/25/15  SS 1.0 original
!> @date 02/02/16 MDG 1.1 significant changes to optimize the code
!> @date 02/04/16 MDG 1.2 added circular mask code
!> @date 03/10/16 MDG 1.3 added h5ebsd formatted output
!> @date 11/14/16 MDG 1.4 added code to read dictionary patterns from h5 file
!> @date 04/04/18 MDG 2.0 separated MC and MP name lists and data structures (all internal changes)
!> @date 02/19/19 MDG 2.1 corrects pattern orientation (manual indexing revealed an unwanted upside down flip)
!> @date 05/19/19 MDG 2.2 removes superfluous code for various types of averaging
!> @date 06/19/19 MDG 2.3 add support for overlap master patterns generated by EMEBSDoverlap.f90
!> 
!--------------------------------------------------------------------------
program EMEBSDDI

use local
use typedefs
use NameListTypedefs
use NameListHandlers
use files
use io
use error
use initializers
use detectors
use Indexingmod
use EBSDmod
use EBSDDImod
use HDF5
use HDFsupport
use ISO_C_BINDING

IMPLICIT NONE

character(fnlen)       :: nmldeffile = 'EMEBSDDI.nml', &
                          progname = 'EMEBSDDI.f90', &
                          progdesc = 'Program to index EBSD patterns using a dynamically calculated pattern dictionary'
character(kind=c_char) :: Cnmldeffile(fnlen), Cprogname(fnlen)

! print some information
call EMsoft(progname, progdesc)

! deal with the command line arguments, if any
call Interpret_Program_Arguments(nmldeffile,1,(/ 80 /), progname)

! call the EBSDdriver routine to take care of the entire indexing process 
Cnmldeffile = carstringify(nmldeffile)
Cprogname = carstringify(progname)
call EBSDDIdriver(Cnmldeffile, Cprogname, C_NULL_FUNPTR, C_NULL_FUNPTR, C_NULL_FUNPTR, 0_ill)

end program EMEBSDDI
