dispfield – Fortran Program
dispfield Program
97 statements
Source File
Uses:
local
typedefs
crystalvars
crystal
symmetryvars
symmetry
postscript
constants
diffraction
dynamical
files
io
foilmodule
stacking_fault
dislocation
void
inclusion
defectmodule
TIFF_global
TIFF_f90
pgm
timing
STEMmodule
YSHModule
Calls
Variables
ira nn izero i j k n nsl numi npix npiy ii jj numvoids numdisl numsf numinc dinfo t_interval outputfirst outputlast DF_nums_new numYdisl DF_npix_new DF_npiy_new numstart numstop isg TID NTHR jcnt numCL iCL ind hkl exerg cosom glen exer dgr sl thr arg zmax thick mi ma att xgp DF_gf DF_gd fname sgname voidname dislname sfname outputroot incname dispfile dislYname imname outputformat illumination_mode dispmode fnumber ci czero cone disparray
Source Code
dispfield
Variables
Type Attributes Name Initial
integer(kind=irg) :: ira
integer(kind=irg) :: nn
integer(kind=irg) :: izero
integer(kind=irg) :: i
integer(kind=irg) :: j
integer(kind=irg) :: k
integer(kind=irg) :: n
integer(kind=irg) :: nsl
integer(kind=irg) :: numi
integer(kind=irg) :: npix
integer(kind=irg) :: npiy
integer(kind=irg) :: ii
integer(kind=irg) :: jj
integer(kind=irg) :: numvoids
integer(kind=irg) :: numdisl
integer(kind=irg) :: numsf
integer(kind=irg) :: numinc
integer(kind=irg) :: dinfo
integer(kind=irg) :: t_interval
integer(kind=irg) :: outputfirst
integer(kind=irg) :: outputlast
integer(kind=irg) :: DF_nums_new
integer(kind=irg) :: numYdisl
integer(kind=irg) :: DF_npix_new
integer(kind=irg) :: DF_npiy_new
integer(kind=irg) :: numstart
integer(kind=irg) :: numstop
integer(kind=irg) :: isg
integer(kind=irg) :: TID
integer(kind=irg) :: NTHR
integer(kind=irg) :: jcnt
integer(kind=irg) :: numCL
integer(kind=irg) :: iCL
real(kind=sgl) :: ind(3)
real(kind=sgl) :: hkl(3)
real(kind=sgl) :: exerg
real(kind=sgl) :: cosom
real(kind=sgl) :: glen
real(kind=sgl) :: exer
real(kind=sgl) :: dgr
real(kind=sgl) :: sl
real(kind=sgl) :: thr
real(kind=sgl) :: arg
real(kind=sgl) :: zmax
real(kind=sgl) :: thick
real(kind=sgl) :: mi
real(kind=sgl) :: ma
real(kind=sgl) :: att
real(kind=sgl) :: xgp
real(kind=sgl) :: DF_gf(3)
real(kind=sgl) :: DF_gd(3,maxdefects)
character(len=50) :: fname
character(len=50) :: sgname
character(len=50) :: voidname
character(len=50) :: dislname(3*maxdefects)
character(len=50) :: sfname(maxdefects)
character(len=50) :: outputroot
character(len=50) :: incname
character(len=50) :: dispfile
character(len=50) :: dislYname(3*maxdefects)
character(len=100) :: imname
character(len=4) :: outputformat
character(len=4) :: illumination_mode
character(len=4) :: dispmode
character(len=5) :: fnumber(-10:10)
character(len=10) :: ci
complex(kind=dbl) :: czero
complex(kind=dbl) :: cone
real(kind=sgl), allocatable :: disparray(:,:,:,:)
Source Code
program dispfield
!
use local
use typedefs
use crystalvars
use crystal
use symmetryvars
use symmetry
use postscript
use constants
use diffraction
use dynamical
use files
use io
use foilmodule
use stacking_fault
use dislocation
use void
use inclusion
use defectmodule
use TIFF_global
use TIFF_f90
use pgm
use timing
use STEMmodule
use YSHModule
IMPLICIT NONE
integer(kind=irg)       :: ira,nn,izero,i,j,k,n,nsl,numi,npix,npiy,ii,jj,numvoids,numdisl,numsf, &
                                  numinc,dinfo,t_interval,outputfirst,outputlast,DF_nums_new, numYdisl, &
                                  DF_npix_new,DF_npiy_new, numstart,numstop, isg, TID, NTHR, jcnt, numCL, iCL
!                                  OMP_GET_THREAD_NUM,OMP_GET_NUM_THREADS
real(kind=sgl)          :: ind(3),hkl(3),exerg,cosom,glen,exer,dgr,sl,thr,arg,zmax,thick,mi,ma, &
                                  att,xgp,DF_gf(3),DF_gd(3,maxdefects)
character(50)           :: fname,sgname,voidname,dislname(3*maxdefects),sfname(maxdefects),outputroot, &
                                  incname,dispfile, dislYname(3*maxdefects)
character(100)          :: imname
character(4)            :: outputformat, illumination_mode, dispmode
character(5)            :: fnumber(-10:10)
character(len=10)       :: ci
complex(kind=dbl)                :: czero,cone
real(kind=sgl),allocatable    :: disparray(:,:,:,:)
namelist / rundata / DF_L, DF_npix, DF_npiy, DF_slice, Nmat, sgname, numvoids, incname, &
                                 voidname, numdisl, dislname, numYdisl, dislYname, numsf, sfname, dinfo, outputformat, &
                 outputroot,t_interval,illumination_mode,outputfirst,outputlast, dispfile, &
                 dispmode
! display the standard program info
 progname = 'dispfield.f90'
 progdesc = 'Defect displacement field simulation program'
 call EMsoft
! get the crystal data and microscope voltage
 SG % SYM_reduce=.TRUE.
 call CrystalData             ! read crystal structure
 hexset = .FALSE.
 czero=cmplx(0.0,0.0,dbl)
 cone=cmplx(1.0,0.0,dbl)
! here we read the general simulation information from a namelist file SRdef_rundata.nml
! first we define the default values
 DF_L = 1.0             ! edge length of column in nanometers
 DF_npix = 256       ! number of image pixels along x
 DF_npiy = 256       ! number of image pixels along y
 DF_slice = 1.0       ! slice thickness in nanometers
 Nmat = 10000       ! number of precomputed A matrices to be stored
 dinfo = 0               ! switch to make makedislocation verbose
 sgname = 'nofile'   ! if this variable is different from 'nofile', then an external sg array is read (to be implemented)
 numdisl = 0           ! number of dislocation files
 numYdisl = 0           ! number of Yoffe dislocation files
 numsf = 0             ! number of stacking fault files
 numinc = 0           ! number of inclusions
 numvoids = 0       ! number of voids
 voidname = 'none' ! filename for void data
 dislname = ''         ! filenames for dislocation data
 dislYname = ''         ! filenames for Yoffe dislocation data
 sfname = ''            ! filenames for stacking fault data
 incname = 'none'   ! filename for inclusion data
 outputformat = 'data'  ! format for output data, can be 'data', 'pgm', or 'tiff'
 outputroot = 'image'  ! default root name for output files
 outputfirst = 1       ! first image number to be written to file (will be set to first image in SR)
 outputlast = nn       ! last image number to be written to file (will be set to last image in SR)
 t_interval = 10       ! default timing interval (output every t_interval image columns)
 dispfile = 'none'     ! name of the displacement field output file (will be created if different from none)
 dispmode = 'not'  ! should a diplacement file be written ('new') or read ('old') or neither ('not')?
 illumination_mode = 'EM'  ! default illumination mode (can be 'EM' or 'STEM')
! then we read the rundata namelist, which may override some of these defaults
 OPEN(UNIT=dataunit,FILE='SRdef_rundata.nml',DELIM='APOSTROPHE')
 READ(UNIT=dataunit,NML=rundata)
 CLOSE(UNIT=dataunit)
! next, we read the foildata namelist from the SRdef_foildata.nml file
! this includes material property data, in this case the elastic moduli
! in particular, the foilmodule MUST compute the beam direction from
! the sample tilt angles !!!
  call read_foil_data(DF_npix,DF_npiy,DF_L)
! define the foil thickness, attenuation, and number slices per column
thick = foil%zb    ! this is the same everywhere for this version; needs to be updated in the next version
DF_nums = nint(thick/DF_slice)  ! this is the number of slices for this particular column
! next, deal with all the defects
!
! if there is a diplacement field file entered in the STEM_rundata.nml file,
! then we simply read that file in; otherwise, we read all the defect descriptor files
! is there a void data filename? If so, then read it
   if (voidname.ne.'none') call read_void_data(numvoids,voidname,DF_L,DF_npix,DF_npiy,dinfo)
! read namelist files for all dislocations, if any
   if (numdisl.gt.0) call read_dislocation_data(dislname,numdisl,numsf,DF_npix,DF_npiy,DF_gf,DF_L,dinfo)
! read namelist files for all Yoffe dislocations, if any
   if (numYdisl.gt.0) call read_YSH_dislocation_data(dislYname,numYdisl,DF_npix,DF_npiy,DF_gf,DF_L,dinfo)
! read namelist files for all stacking faults, if any
   if (numsf.gt.0) call read_stacking_fault_data(numsf,numdisl,sfname,DF_L,DF_npix,DF_npiy,DF_g,dinfo)
! is there an inclusion data file? if so, then read it
   if (incname.ne.'none') call read_inclusion_data(numinc,incname,DF_L,DF_npix,DF_npiy,dinfo)
! transform the g-vector to the defect reference frames (needed for all dislocations in CalcR).
! this can only be done AFTER all dislocations and stacking faults have been created.
   do i=1,numdisl
     DF_gd(0:2,i) = matmul(DL(i)%a_dc,DF_gc)
   end do
! precompute ALL the defect columns and, if needed, store them in dispfile
! this portion should be carried out in multi-threaded mode as much as possible
  allocate(disparray(DF_nums,DF_npix,DF_npiy,3))
  disparray = 0.0
  mess = ' Starting Displacement Field Computation '; call Message("(A/)")
  call CalcRLocal(numvoids,numdisl,numYdisl,numsf,numinc,DF_nums,DF_npix,DF_npiy,t_interval,disparray)
   write (*,*) maxval(disparray),minval(disparray)
! and, if needed, store the defect displacement field for re-runs
    mess = 'Displacement field data stored in file '//dispfile; call Message("(/A/)")
    open(unit=dataunit,file=trim(EMsoft_toNativePath(dispfile)),status='new',action='write',form='unformatted')
    i=3
    write (dataunit) DF_nums,DF_npix,DF_npiy,i
    write (dataunit) disparray
    call SafeCloseFile('d1','keep',dispfile,.FALSE.)
end program dispfield
All Programs
dispfield hdftest
Call graph
dispfield calls read_inclusion_data, dl, safeclosefile, read_stacking_fault_data, read_ysh_dislocation_data, emsoft, crystaldata, message, read_foil_data, calcrlocal, read_void_data, read_dislocation_data, emsoft_tonativepath
read_ysh_dislocation_data calls message, emsoft_tonativepath, makeyshdislocation, float
calcrlocal calls float, time_reset, time_start, yshdisp, time_remaining, sngl, time_stop, time_report
makeyshdislocation calls normvec, calclength, calcangle, calcdot, calccross, transspace
time_start calls time_reset
yshdisp calls datan2
time_remaining calls message, float, printtime, writevalue
time_stop calls message, float, printtime, writevalue
time_report calls message
printtime calls writevalue