hdftest – Fortran Program
hdftest Program
125 statements
Source File
Uses:
hdf5
h5lt
Calls
Variables
filename fix_filename dsetname aname aname2 aname3 aname4 aname5 aname6 RANK NX NY file_id dset_id dataspace attr_id attr2_id attr3_id attr4_id attr5_id attr6_id aspace_id aspace2_id aspace6_id dtype_id atype_id atype2_id atype3_id atype4_id atype5_id adims adims2 arank attrlen attr_space attr2_space attr_type attr2_type attr3_type attr4_type attr5_type attr6_type num_attrs attr_storage attr_name name_size attr_data aread_data attr_character_data attr_double_data attr_real_data attr_integer_data aread_character_data aread_integer_data aread_null_data aread_double_data aread_real_data fname datapath g1 g2 g3 s error total_error i data_dims npoints rnk type_class type_size grp1_id grp2_id grp3_id buf_dbl1 buf_dbl2 buf_dbl3 buf_flt1 scversion dstring tstring
Source Code
hdftest
Variables
Type Attributes Name Initial
character(len=5), parameter :: filename = "atest"
character(len=80) :: fix_filename
character(len=9), parameter :: dsetname = "atestdset"
character(len=11), parameter :: aname = "attr_string"
character(len=14), parameter :: aname2 = "attr_character"
character(len=11), parameter :: aname3 = "attr_double"
character(len=9), parameter :: aname4 = "attr_real"
character(len=12), parameter :: aname5 = "attr_integer"
character(len=9), parameter :: aname6 = "attr_null"
integer, parameter :: RANK = 2
integer, parameter :: NX = 4
integer, parameter :: NY = 5
integer(kind=HID_T) :: file_id
integer(kind=HID_T) :: dset_id
integer(kind=HID_T) :: dataspace
integer(kind=HID_T) :: attr_id
integer(kind=HID_T) :: attr2_id
integer(kind=HID_T) :: attr3_id
integer(kind=HID_T) :: attr4_id
integer(kind=HID_T) :: attr5_id
integer(kind=HID_T) :: attr6_id
integer(kind=HID_T) :: aspace_id
integer(kind=HID_T) :: aspace2_id
integer(kind=HID_T) :: aspace6_id
integer(kind=HID_T) :: dtype_id
integer(kind=HID_T) :: atype_id
integer(kind=HID_T) :: atype2_id
integer(kind=HID_T) :: atype3_id
integer(kind=HID_T) :: atype4_id
integer(kind=HID_T) :: atype5_id
integer(kind=HSIZE_T), DIMENSION(1) :: adims = (/2/)
integer(kind=HSIZE_T), DIMENSION(1) :: adims2 = (/1/)
integer :: arank = 1
integer(kind=SIZE_T) :: attrlen
integer(kind=HID_T) :: attr_space
integer(kind=HID_T) :: attr2_space
integer(kind=HID_T) :: attr_type
integer(kind=HID_T) :: attr2_type
integer(kind=HID_T) :: attr3_type
integer(kind=HID_T) :: attr4_type
integer(kind=HID_T) :: attr5_type
integer(kind=HID_T) :: attr6_type
integer :: num_attrs
integer(kind=HSIZE_T) :: attr_storage
character(len=256) :: attr_name
integer(kind=SIZE_T) :: name_size = 80
character(len=35), DIMENSION(2) :: attr_data
character(len=35), DIMENSION(2) :: aread_data
character :: attr_character_data = 'A'
double precision, DIMENSION(1) :: attr_double_data = 3.459
real, DIMENSION(1) :: attr_real_data = 4.0
integer, DIMENSION(1) :: attr_integer_data = 5
character :: aread_character_data
integer, DIMENSION(1) :: aread_integer_data
integer, DIMENSION(1) :: aread_null_data = 7
double precision, DIMENSION(1) :: aread_double_data
real, DIMENSION(1) :: aread_real_data
character(len=80) :: fname
character(len=80) :: datapath
character(len=80) :: g1
character(len=80) :: g2
character(len=80) :: g3
character(len=80) :: s
integer :: error
integer :: total_error
integer :: i
integer(kind=HSIZE_T), allocatable :: data_dims(:)
integer(kind=HSIZE_T) :: npoints
integer :: rnk
integer :: type_class
integer(kind=SIZE_T) :: type_size
integer(kind=HID_T) :: grp1_id
integer(kind=HID_T) :: grp2_id
integer(kind=HID_T) :: grp3_id
real(kind=8), allocatable :: buf_dbl1(:)
real(kind=8), allocatable :: buf_dbl2(:,:)
real(kind=8), allocatable :: buf_dbl3(:,:,:)
real(kind=4), allocatable :: buf_flt1(:)
character(len=8) :: scversion
character(len=11) :: dstring
character(len=15) :: tstring
Source Code
program hdftest
use hdf5
use h5lt
IMPLICIT NONE
     CHARACTER(LEN=5), PARAMETER :: filename = "atest"    !File name
     CHARACTER(LEN=80) :: fix_filename
     CHARACTER(LEN=9), PARAMETER :: dsetname = "atestdset"        !Dataset name
     CHARACTER(LEN=11), PARAMETER :: aname = "attr_string"   !String Attribute name
     CHARACTER(LEN=14), PARAMETER :: aname2 = "attr_character"!Character Attribute name
     CHARACTER(LEN=11), PARAMETER :: aname3 = "attr_double"   !DOuble Attribute name
     CHARACTER(LEN=9), PARAMETER :: aname4 = "attr_real"      !Real Attribute name
     CHARACTER(LEN=12), PARAMETER :: aname5 = "attr_integer"  !Integer Attribute name
     CHARACTER(LEN=9), PARAMETER :: aname6 = "attr_null"     !Null Attribute name
     !
     !data space rank and dimensions
     !
     INTEGER, PARAMETER :: RANK = 2
     INTEGER, PARAMETER :: NX = 4
     INTEGER, PARAMETER :: NY = 5
     INTEGER(HID_T) :: file_id       ! File identifier
     INTEGER(HID_T) :: dset_id       ! Dataset identifier
     INTEGER(HID_T) :: dataspace     ! Dataspace identifier for dataset
     INTEGER(HID_T) :: attr_id        !String Attribute identifier
     INTEGER(HID_T) :: attr2_id       !Character Attribute identifier
     INTEGER(HID_T) :: attr3_id       !Double Attribute identifier
     INTEGER(HID_T) :: attr4_id       !Real Attribute identifier
     INTEGER(HID_T) :: attr5_id       !Integer Attribute identifier
     INTEGER(HID_T) :: attr6_id       !Null Attribute identifier
     INTEGER(HID_T) :: aspace_id      !String Attribute Dataspace identifier
     INTEGER(HID_T) :: aspace2_id     !Character Attribute Dataspace identifier
     INTEGER(HID_T) :: aspace6_id     !Null Attribute Dataspace identifier
     INTEGER(HID_T) :: dtype_id       !
     INTEGER(HID_T) :: atype_id       !String Attribute Datatype identifier
     INTEGER(HID_T) :: atype2_id      !Character Attribute Datatype identifier
     INTEGER(HID_T) :: atype3_id      !Double Attribute Datatype identifier
     INTEGER(HID_T) :: atype4_id      !Real Attribute Datatype identifier
     INTEGER(HID_T) :: atype5_id      !Integer Attribute Datatype identifier
     INTEGER(HSIZE_T), DIMENSION(1) :: adims = (/2/) ! Attribute dimension
     INTEGER(HSIZE_T), DIMENSION(1) :: adims2 = (/1/) ! Attribute dimension
     INTEGER     ::   arank = 1                      ! Attribure rank
     INTEGER(SIZE_T) :: attrlen    ! Length of the attribute string
     INTEGER(HID_T) :: attr_space     !Returned String Attribute Space identifier
     INTEGER(HID_T) :: attr2_space    !Returned other Attribute Space identifier
     INTEGER(HID_T) :: attr_type      !Returned Attribute Datatype identifier
     INTEGER(HID_T) :: attr2_type      !Returned CHARACTER Attribute Datatype identifier
     INTEGER(HID_T) :: attr3_type      !Returned DOUBLE Attribute Datatype identifier
     INTEGER(HID_T) :: attr4_type      !Returned REAL Attribute Datatype identifier
     INTEGER(HID_T) :: attr5_type      !Returned INTEGER Attribute Datatype identifier
     INTEGER(HID_T) :: attr6_type      !Returned NULL Attribute Datatype identifier
     INTEGER        :: num_attrs      !number of attributes
     INTEGER(HSIZE_T) :: attr_storage   ! attributes storage requirements .MSB.
     CHARACTER(LEN=256) :: attr_name    !buffer to put attr_name
     INTEGER(SIZE_T)    ::  name_size = 80 !attribute name length
     CHARACTER(LEN=35), DIMENSION(2) ::  attr_data  ! String attribute data
     CHARACTER(LEN=35), DIMENSION(2) ::  aread_data ! Buffer to put read back
                                               ! string attr data
     CHARACTER ::  attr_character_data = 'A'
     DOUBLE PRECISION,  DIMENSION(1) ::  attr_double_data = 3.459
     REAL,         DIMENSION(1) ::  attr_real_data = 4.0
     INTEGER,      DIMENSION(1) ::  attr_integer_data = 5
     CHARACTER :: aread_character_data ! variable to put read back Character attr data
     INTEGER, DIMENSION(1)  :: aread_integer_data ! variable to put read back integer attr data
     INTEGER, DIMENSION(1)  :: aread_null_data = 7 ! variable to put read back null attr data
     DOUBLE PRECISION, DIMENSION(1)   :: aread_double_data ! variable to put read back double attr data
     REAL, DIMENSION(1)  :: aread_real_data ! variable to put read back real attr data
     character(len=80)          :: fname, datapath,g1,g2,g3,s
     integer                    :: error, total_error, i ! Error flag
     INTEGER(HSIZE_T),allocatable :: data_dims(:)
     INTEGER(HSIZE_T)           :: npoints
     integer                    :: rnk, type_class
     integer(SIZE_T)            :: type_size
     integer(HID_T)             :: grp1_id, grp2_id, grp3_id
     real(kind=8),allocatable   :: buf_dbl1(:), buf_dbl2(:,:), buf_dbl3(:,:,:)
     real(kind=4),allocatable   :: buf_flt1(:)
     character(8)               :: scversion
     character(11)              :: dstring
     character(15)              :: tstring
call timestamp(datestring=dstring, timestring=tstring)
fname = 'Nidata.h5'
scversion = '3.x.x'
write (*,*) 'Date = '//dstring
write (*,*) 'Time = '//tstring
!
! Initialize FORTRAN interface.
!
CALL h5open_EMsoft(error)
write (*,*) 'Initialize Fortran interface error   = ',error
write (*,*) 'calling h5fopen_f to open file '//fname
     CALL h5fopen_f(fname, H5F_ACC_RDWR_F, file_id, error)
write (*,*) 'file_id = ',file_id
write (*,*) 'error   = ',error
!
datapath = "/Scan 1/EBSD/Data/CI"
call h5ltget_dataset_ndims_f(file_id, datapath, rnk, error)
write (*,*) ' data dimensionality = ',rnk
allocate(data_dims(rnk))
call h5ltget_dataset_info_f(file_id, datapath, data_dims, type_class, type_size, error)
write(*,*) ' data set info : ',data_dims(1), type_class, type_size, error
allocate(buf_flt1(data_dims(1)))
call h5ltread_dataset_f(file_id, datapath, H5T_NATIVE_REAL, buf_flt1, data_dims, error)
do i=1,10
  write (*,*) i, buf_flt1(i)
end do
write (*,*) 'calling h5fclose_f to close file '
     CALL h5fclose_f(file_id, error)
write (*,*) 'error   = ',error
! now let's do a test an create a new file with this dataset written to it in a different location
fname = 'test.h5'
call h5fcreate_f(fname, H5F_ACC_TRUNC_F, file_id, error)
g1 = 'EMheader'
call h5gcreate_f(file_id,g1,grp1_id,error)
write (*,*) 'open group ',trim(g1),' ',error
! version number /EMheader/Version 'character'
call h5ltmake_dataset_string_f(grp1_id, 'Version', scversion, error)
! execution data /EMheader/Date 'character'
call h5ltmake_dataset_string_f(grp1_id, 'Date', dstring, error)
! start time /EMheader/StartTime 'character'
call h5ltmake_dataset_string_f(grp1_id, 'StartTime', tstring, error)
! stop time /EMheader/StopTime 'character'
call h5ltmake_dataset_string_f(grp1_id, 'StopTime', tstring, error)
call h5gclose_f(grp1_id,error)
g1 = 'level1'
g2 = 'level2'
g3 = 'CI'
s = '/'
call h5gcreate_f(file_id,g1,grp1_id,error)
write (*,*) 'open group ',trim(g1),' ',error
call h5gcreate_f(grp1_id,g2,grp2_id,error)
write (*,*) 'open group ',trim(g2),' ',error
datapath = trim(s)//trim(g1)//trim(s)//trim(g2)//trim(s)//trim(g3)
write (*,*) 'datapath = ',datapath
call h5ltmake_dataset_f(file_id, datapath, rnk, data_dims, H5T_NATIVE_REAL, buf_flt1, error)
call h5gclose_f(grp2_id,error)
call h5gclose_f(grp1_id,error)
call h5fclose_f(file_id,error)
!
! Close FORTRAN interface.
!
CALL h5close_EMsoft(error)
write (*,*) 'close fortran interface error   = ',error
end program hdftest
All Programs
dispfield hdftest
Call graph
hdftest calls h5fclose_f, timestamp, h5ltmake_dataset_f, h5gclose_f, h5gcreate_f, h5close_emsoft, h5open_emsoft, h5ltmake_dataset_string_f, h5fopen_f, h5ltget_dataset_ndims_f, h5ltget_dataset_info_f, h5ltread_dataset_f, h5fcreate_f