BackProjection – Fortran Program
BackProjection Subroutine
92 statements
Source File
public recursive subroutine BackProjection(ncub, ODF, PFhkl, nLam, PFLam, pgnum) bind(c, name = "0")
Uses:
local
constants
Lambert
rotations
error
dictmod
typedefs
symmetry
iso_c_binding
@author Saransh Singh, Carnegie Mellon University @brief back projection from PF in Lambert space to ODF in cubochoric space @param ncub number of bins in semi-edge in x,y and z directions @param PFhkl hkl indices of the specific pole figure @param nLam bins in the output along semi-edge in Lambert projection @param PFLam Pole figure in Lambert projection @out ODF orientation distribution function @date 11/07/16 SS 1.0 original @date 11/10/16 SS 1.1 added symmetry; all integration done in FZ @date 12/08/16 SS 1.2 all computations in quaternion to avoid infinity problem
Arguments
Type Intent Optional Attributes Name
integer(kind=irg), intent(in) :: ncub
real(kind=dbl), intent(out) :: ODF(-ncub:ncub,-ncub:ncub,-ncub:ncub)
integer(kind=irg), intent(in) :: PFhkl(3)
integer(kind=irg), intent(in) :: nLam
real(kind=dbl), intent(in) :: PFLam(-nLam:nLam,-nLam:nLam)
integer(kind=irg), intent(in) :: pgnum
Calls
Source Code
BackProjection
Source Code
recursive subroutine BackProjection(ncub, ODF, PFhkl, nLam, PFLam, pgnum) &
bind(c, name = 'BackProjection')
!DEC$ ATTRIBUTES DLLEXPORT :: BackProjection
use local
use constants
use Lambert
use rotations
use error
use dictmod
use typedefs,only:dicttype
use symmetry,only:CalcFamily
use ISO_C_BINDING
IMPLICIT NONE
integer(kind=irg),INTENT(IN)        :: ncub
real(kind=dbl),INTENT(OUT)          :: ODF(-ncub:ncub,-ncub:ncub,-ncub:ncub)
integer(kind=irg),INTENT(IN)        :: PFhkl(3)
integer(kind=irg),INTENT(IN)        :: nLam
real(kind=dbl),INTENT(IN)           :: PFLam(-nLam:nLam,-nLam:nLam)
integer(kind=irg),INTENT(IN)        :: pgnum
real(kind=dbl)                       :: xy(2), PFhkl_f(3), xyz(3), hcrossy(3)
integer(kind=irg)                    :: ii, jj, kk, ll, ierr, nth
real(kind=dbl)                       :: cth, sth, rod(4), rod2(4), r(3), r2(4), cu(3), qu(4), qu2(4), &
                                        eu(3), eu2(3), qures(4)
real(kind=dbl),allocatable           :: dth(:)
integer(kind=irg)                    :: nix, niy, niz, nixp, niyp, nizp
real(kind=dbl)                       :: nbx, nby, nbz, dx, dy, dz, dxm, dym, dzm, dconst
type(dicttype),pointer               :: dict
integer(kind=irg)                    :: Pmdims, FZtype, FZorder
! allocate the dict structure
allocate(dict)
dict%Num_of_init = 3
dict%Num_of_iterations = 30
dict%pgnum = pgnum
! initialize the symmetry matrices
call DI_Init(dict,'nil')
Pmdims = dict%Nqsym
FZtype = FZtarray(dict%pgnum)
FZorder = FZoarray(dict%pgnum)
! only valid for cubic/tetragonal/orthorhombic symmetry
! normalize the input pole figure
PFhkl_f = dble(PFhkl)
PFhkl_f = PFhkl_f/NORM2(PFhkl_f)
nth = 101
allocate(dth(1:nth))
dth = 0.D0
dth = (/(2.D0*cPi*float(ii-1)/(float(nth-1)),ii=1,nth)/)
dconst = 1.D0/dble(nth)
do ii = -nLam,nLam
    do jj = -nLam,nLam
        xy = (/dble(ii)/dble(nLam), dble(jj)/dble(nLam)/)
        xyz = LambertSquareToSphere(xy,ierr)
        if (ierr .eq. 0) then
           xyz = xyz/NORM2(xyz)
        else
            call FatalError('LambertSquareToSphere:','Coulnd not convert lambert square to sphere')
        end if
!       hcrossy =  PFhkl_f x xyz;
!       only valid for cubic/tetragonal/orthorhombic symmetry
!       general case will be dealt with later
        hcrossy =  (/ PFhkl_f(2)*xyz(3) - PFhkl_f(3)*xyz(2),&
                      PFhkl_f(3)*xyz(1) - PFhkl_f(1)*xyz(3),&
                      PFhkl_f(1)*xyz(2) - PFhkl_f(2)*xyz(1)/)
        if(sum(abs(hcrossy)) .ne. 0) hcrossy = hcrossy/NORM2(hcrossy)
! rotation by -omega about cross(h,y)
        cth = sum(PFhkl_f*xyz)
        qu = ax2qu((/hcrossy(1),hcrossy(2),hcrossy(3),acos(cth)/))
        do kk = 1,nth
            qu2 = ax2qu((/xyz(1),xyz(2),xyz(3),dth(kk)/))
            qures = quat_mult(qu2,qu)
            eu = qu2eu(qures)
            call ReduceOrientationtoRFZ(eu, dict, FZtype, FZorder, eu2)
            cu = eu2cu(eu2)
            nbx = cu(1)/LPs%ap*ncub
            nby = cu(2)/LPs%ap*ncub
            nbz = cu(3)/LPs%ap*ncub
            nix = floor(nbx)
            niy = floor(nby)
            niz = floor(nbz)
            if(nix < -ncub) nix = -ncub
            if(niy < -ncub) niy = -ncub
            if(niz < -ncub) niz = -ncub
            nixp = nix + 1
            niyp = niy + 1
            nizp = niz + 1
            if(nixp > ncub) nixp = ncub
            if(niyp > ncub) niyp = ncub
            if(nizp > ncub) nizp = ncub
            dx = nbx - nix
            dy = nby - niy
            dz = nbz - niz
            dxm = 1.D0 - dx
            dym = 1.D0 - dy
            dzm = 1.D0 - dz
! assign intensity in ODF according to how close to each cell the resultant orientation is
! sort of like tri-linear interpolation
            ODF(nix,niy,niz)  = ODF(nix,niy,niz)  + PFLam(ii,jj)*dxm*dym*dzm*dconst
            ODF(nixp,niy,niz) = ODF(nixp,niy,niz) + PFLam(ii,jj)*dx*dym*dzm*dconst
            ODF(nix,niyp,niz) = ODF(nix,niyp,niz) + PFLam(ii,jj)*dxm*dy*dzm*dconst
            ODF(nix,niy,nizp) = ODF(nix,niy,nizp) + PFLam(ii,jj)*dxm*dym*dz*dconst
            ODF(nixp,niyp,niz)  = ODF(nixp,niyp,niz)  + PFLam(ii,jj)*dx*dy*dzm*dconst
            ODF(nixp,niy,nizp)  = ODF(nixp,niy,nizp)  + PFLam(ii,jj)*dx*dym*dz*dconst
            ODF(nix,niyp,nizp)  = ODF(nix,niyp,nizp)  + PFLam(ii,jj)*dxm*dy*dz*dconst
            ODF(nixp,niyp,nizp) = ODF(nixp,niyp,nizp) + PFLam(ii,jj)*dx*dy*dz*dconst
        end do
    end do
end do
end subroutine BackProjection
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
backprojection calls float, fatalerror, reduceorientationtorfz, eu2cu, lambertsquaretosphere, ax2qu, fzoarray, qu2eu, quat_mult, di_init, fztarray
reduceorientationtorfz calls quat_mult, isinsidefz, eu2qu, qu2ro, ro2eu, isinsidemfz
di_init calls fatalerror, besselin, besseli1, sym_qsymop, besseli0, pgrot
isinsidefz calls insidecubicfz, insidecubehexfz, insidecyclicfz, insidedihedralfz
isinsidemfz calls insidecyclicfz, insidecubicmfz, insidedihedralmfz
insidecubicmfz calls insidecubicfz
insidedihedralmfz calls insidedihedralfz