bobyqa – Fortran Program
bobyqa Subroutine
92 statements
Source File
public recursive subroutine bobyqa(nipar, nfpar, ninit, ipar, fpar, initmeanval, expt1, n, npt, x, xl, xu, rhobeg, rhoend, iprint, maxfun, calfun, accum_e, mLPNH, mLPSH, nstep, stepsize, verbose)
Uses:
iso_c_binding
Arguments
Type Intent Optional Attributes Name
integer(kind=irg), intent(in) :: nipar
integer(kind=irg), intent(in) :: nfpar
integer(kind=irg), intent(in) :: ninit
integer(kind=8), intent(in) :: ipar(nipar)
real(kind=sgl), intent(inout) :: fpar(nfpar)
real(kind=sgl), intent(in) :: initmeanval(ninit)
real(kind=c_float), intent(in) :: expt1(ipar(2)*ipar(3)/ipar(12)**2)
integer, intent(in) :: n
number of variables (must be at least two)
integer, intent(in) :: npt
number of interpolation conditions. Its value must be in the interval [N+2,(N+1)(N+2)/2]. Choices that exceed 2*N+1 are not recommended.
real(kind=dbl), intent(inout), dimension(:) :: x
Initial values of the variables must be set in X(1),X(2),...,X(N). They will be changed to the values that give the least calculated F.
real(kind=dbl), intent(in), dimension(:) :: xl
lower bounds on x. The construction of quadratic models requires XL(I) to be strictly less than XU(I) for each I. Further, the contribution to a model from changes to the I-th variable is damaged severely by rounding errors if XU(I)-XL(I) is too small.
real(kind=dbl), intent(in), dimension(:) :: xu
upper bounds on x. The construction of quadratic models requires XL(I) to be strictly less than XU(I) for each I. Further, the contribution to a model from changes to the I-th variable is damaged severely by rounding errors if XU(I)-XL(I) is too small.
real(kind=dbl), intent(in) :: rhobeg
RHOBEG must be set to the initial value of a trust region radius.
It must be positive, and typically should be about one tenth of the greatest expected change to a variable. An error return occurs if any of the differences XU(I)-XL(I), I=1,...,N, is less than 2*RHOBEG.
real(kind=dbl), intent(in) :: rhoend
RHOEND must be set to the final value of a trust region radius. It must be positive with RHOEND no greater than RHOBEG. Typically, RHOEND should indicate the accuracy that is required in the final values of the variables.
integer, intent(in) :: iprint
IPRINT should be set to 0, 1, 2 or 3, which controls the amount of printing. Specifically, there is no output if IPRINT=0 and there is output only at the return if IPRINT=1. Otherwise, each new value of RHO is printed, with the best vector of variables so far and the corresponding value of the objective function. Further, each new value of F with its variables are output if IPRINT=3.
integer, intent(in) :: maxfun
an upper bound on the number of calls of CALFUN.
procedure(func) :: calfun
SUBROUTINE CALFUN (N,X,F) has to be provided by the user. It must set F to the value of the objective function for the current values of the variables X(1),X(2),...,X(N), which are generated automatically in a way that satisfies the bounds given in XL and XU.
real(kind=sgl), intent(in) :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
real(kind=sgl), intent(in) :: mLPNH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(10),ipar(7))
real(kind=sgl), intent(in) :: mLPSH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(10),ipar(7))
integer(kind=irg), intent(in) :: nstep
real(kind=sgl), intent(in) :: stepsize(nstep)
logical, intent(in), optional :: verbose
Calls
Source Code
bobyqa
Source Code
    recursive subroutine bobyqa (nipar, nfpar, ninit, ipar, fpar, initmeanval, expt1, n, npt, x, xl,&
                         xu, rhobeg, rhoend, iprint, maxfun, calfun, accum_e, mLPNH, mLPSH,&
                         nstep, stepsize, verbose)
!DEC$ ATTRIBUTES DLLEXPORT :: bobyqa
        use,INTRINSIC :: ISO_C_BINDING
        implicit none
        integer(8),intent(in)               :: ipar(nipar)
        real(sgl),intent(inout)             :: fpar(nfpar)
        real(sgl),intent(in)                :: initmeanval(ninit)
        real(sgl),intent(in)                :: stepsize(nstep)
        integer(irg),intent(in)             :: ninit
        integer(irg),intent(in)             :: nipar
        integer(irg),intent(in)             :: nfpar
        integer(irg),intent(in)             :: nstep
        real(c_float),intent(in)            :: expt1(ipar(2)*ipar(3)/ipar(12)**2)
        real(sgl),intent(in)                :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
        real(sgl),intent(in)                :: mLPNH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(10), ipar(7))
        real(sgl),intent(in)                :: mLPSH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(10), ipar(7))
        logical,intent(in),optional         :: verbose
        integer,intent(in)                  :: n       !! number of variables (must be at least two)
        integer,intent(in)                  :: npt     !! number of interpolation conditions. Its value must be in
                                                       !! the interval [N+2,(N+1)(N+2)/2]. Choices that exceed 2*N+1 are not
                                                       !! recommended.
        real(dbl),dimension(:),intent(inout) :: x       !! Initial values of the variables must be set in X(1),X(2),...,X(N). They
                                                       !! will be changed to the values that give the least calculated F.
        real(dbl),dimension(:),intent(in)    :: xl      !! lower bounds on x. The construction of quadratic models
                                                       !! requires XL(I) to be strictly less than XU(I) for each I. Further,
                                                       !! the contribution to a model from changes to the I-th variable is
                                                       !! damaged severely by rounding errors if XU(I)-XL(I) is too small.
        real(dbl),dimension(:),intent(in)    :: xu      !! upper bounds on x. The construction of quadratic models
                                                       !! requires XL(I) to be strictly less than XU(I) for each I. Further,
                                                       !! the contribution to a model from changes to the I-th variable is
                                                       !! damaged severely by rounding errors if XU(I)-XL(I) is too small.
        real(dbl),intent(in)                 :: rhobeg  !! RHOBEG must be set to the initial value of a trust region radius.
                                                       !! It must be positive, and typically should be about one tenth of the greatest
                                                       !! expected change to a variable.  An error return occurs if any of
                                                       !! the differences XU(I)-XL(I), I=1,...,N, is less than 2*RHOBEG.
        real(dbl),intent(in)                 :: rhoend  !! RHOEND must be set to the final value of a trust
                                                       !! region radius. It must be positive with RHOEND no greater than
                                                       !! RHOBEG. Typically, RHOEND should indicate the
                                                       !! accuracy that is required in the final values of the variables.
        integer,intent(in)                  :: iprint  !! IPRINT should be set to 0, 1, 2 or 3, which controls the
                                                       !! amount of printing. Specifically, there is no output if IPRINT=0 and
                                                       !! there is output only at the return if IPRINT=1. Otherwise, each new
                                                       !! value of RHO is printed, with the best vector of variables so far and
                                                       !! the corresponding value of the objective function. Further, each new
                                                       !! value of F with its variables are output if IPRINT=3.
        integer,intent(in)                  :: maxfun  !! an upper bound on the number of calls of CALFUN.
        procedure (func)                    :: calfun  !! SUBROUTINE CALFUN (N,X,F) has to be provided by the user. It must set
                                                       !! F to the value of the objective function for the current values of the
                                                       !! variables X(1),X(2),...,X(N), which are generated automatically in a
                                                       !! way that satisfies the bounds given in XL and XU.
        integer :: ibmat,id,ifv,igo,ihq,ipq,isl,isu,ivl,iw,ixa,&
                   ixb,ixn,ixo,ixp,izmat,j,jsl,jsu,ndim,np
        real(dbl),dimension(:),allocatable :: w
        real(dbl) :: temp
        real(dbl),parameter :: zero = 0.0_dbl
! The array W will be used for working space.
        allocate( w((NPT+5)*(NPT+N)+3*N*(N+5)/2) )
!
!     Return if the value of NPT is unacceptable.
!
        np = n + 1
        if (npt < n+2 .or. npt > ((n+2)*np)/2) then
            write(*,'(/4X,A)') &
                'Return from BOBYQA because NPT is not in the required interval'
            return
        end if
!
!     Partition the working space array, so that different parts of it can
!     be treated separately during the calculation of BOBYQB. The partition
!     requires the first (NPT+2)*(NPT+N)+3*N*(N+5)/2 elements of W plus the
!     space that is taken by the last array in the argument list of BOBYQB.
!
        ndim = npt + n
        ixb = 1
        ixp = ixb + n
        ifv = ixp + n * npt
        ixo = ifv + npt
        igo = ixo + n
        ihq = igo + n
        ipq = ihq + (n*np) / 2
        ibmat = ipq + npt
        izmat = ibmat + ndim * n
        isl = izmat + npt * (npt-np)
        isu = isl + n
        ixn = isu + n
        ixa = ixn + n
        id = ixa + n
        ivl = id + n
        iw = ivl + ndim
!
!     Return if there is insufficient space between the bounds. Modify the
!     initial X if necessary in order to avoid conflicts between the bounds
!     and the construction of the first quadratic model. The lower and upper
!     bounds on moves from the updated X are set now, in the ISL and ISU
!     partitions of W, in order to provide useful and exact information about
!     components of X that become within distance RHOBEG from their bounds.
!
        do j = 1, n
            temp = xu (j) - xl (j)
            if (temp < rhobeg+rhobeg) then
                write(*,'(/4X,A)') &
                    'Return from BOBYQA because one of the differences '//&
                    'XU(I)-XL(I) is less than 2*RHOBEG.'
                return
            end if
            jsl = isl + j - 1
            jsu = jsl + n
            w (jsl) = xl (j) - x (j)
            w (jsu) = xu (j) - x (j)
            if (w(jsl) >=-rhobeg) then
                if (w(jsl) >= zero) then
                    x (j) = xl (j)
                    w (jsl) = zero
                    w (jsu) = temp
                else
                    x (j) = xl (j) + rhobeg
                    w (jsl) = - rhobeg
                    w (jsu) = max (xu(j)-x(j), rhobeg)
                end if
            else if (w(jsu) <= rhobeg) then
                if (w(jsu) <= zero) then
                    x (j) = xu (j)
                    w (jsl) = - temp
                    w (jsu) = zero
                else
                    x (j) = xu (j) - rhobeg
                    w (jsl) = min (xl(j)-x(j),-rhobeg)
                    w (jsu) = rhobeg
                end if
            end if
        end do
!
!     Make the call of BOBYQB.
!
        if (present(verbose)) then
          call bobyqb (nipar, nfpar, ninit, ipar, fpar, initmeanval, expt1, n, npt, x, xl, xu, rhobeg, rhoend, iprint,&
           maxfun, w(ixb), w(ixp), w(ifv), w(ixo), w(igo), w(ihq), w(ipq), w(ibmat), w(izmat), ndim, w(isl), &
           w(isu), w(ixn), w(ixa), w(id), w(ivl), w(iw), calfun, accum_e, mLPNH, mLPSH, nstep, &
           stepsize, verbose)
        else
          call bobyqb (nipar, nfpar, ninit, ipar, fpar, initmeanval, expt1, n, npt, x, xl, xu, rhobeg, rhoend, iprint,&
           maxfun, w(ixb), w(ixp), w(ifv), w(ixo), w(igo), w(ihq), w(ipq), w(ibmat), w(izmat), ndim, w(isl), &
           w(isu), w(ixn), w(ixa), w(id), w(ivl), w(iw), calfun, accum_e, mLPNH, mLPSH, nstep, &
           stepsize)
        end if
        deallocate(w)
    end subroutine bobyqa
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
bobyqa calls bobyqb
bobyqb calls prelim, altmov, update, trsbox, rescue
rescue calls update