CalcRLocal – Fortran Program
CalcRLocal Subroutine
142 statements
Source File
recursive subroutine CalcRLocal(numvoids, numdisl, numYdisl, numsf, numinc, lDFnums, lDFnpix, lDFnpiy, t_interval, disparray)
Uses:
local
constants
crystal
crystalvars
dislocation
foilmodule
void
stacking_fault
inclusion
defectmodule
timing
YSHModule
Arguments
Type Intent Optional Attributes Name
integer(kind=irg) :: numvoids
integer(kind=irg) :: numdisl
integer(kind=irg) :: numYdisl
integer(kind=irg) :: numsf
integer(kind=irg) :: numinc
integer(kind=irg) :: lDFnums
integer(kind=irg) :: lDFnpix
integer(kind=irg) :: lDFnpiy
integer(kind=irg) :: t_interval
real(kind=sgl) :: disparray(lDFnums,lDFnpix,lDFnpiy,3)
Calls
Called By
Source Code
CalcRLocal
Source Code
recursive subroutine CalcRLocal(numvoids,numdisl,numYdisl,numsf,numinc,lDFnums,lDFnpix,lDFnpiy,t_interval,disparray)
! this routine returns the total displacement field (multithreaded with OPENMP)
use local
use constants
use crystal
use crystalvars
use dislocation
use foilmodule
use void
use stacking_fault
use inclusion
use defectmodule
use timing
use YSHModule
IMPLICIT NONE
integer(kind=irg)     :: i,j,k,ii,islice,numvoids,numdisl,numYdisl,numsf,numinc,lDFnums,lDFnpix,lDFnpiy, &
                                  TID,NTHR,imat,t_interval,jcnt
real(kind=sgl)          :: disparray(lDFnums,lDFnpix,lDFnpiy,3)
real(kind=sgl)          :: rx,ry,rz,dis,xpos,ypos,zpos,RR(3),sumR(3),thick,tmp(3),tmpf(3),u(3),zaamp,zaphase,zar,zai,zr(3),zi(3), &
                                 zt,fx,fy,fz,z0,gdotR,nunit(3)    !,&
!                                nu,x,y,z,zn,t,pre,r1,r2,r3,th,rn
real(kind=dbl)            :: afi(3,3), afc(3,3), lDFR(3)
complex(kind=dbl)     :: za(3)
complex(kind=sgl)     :: zero
logical               :: void
type (voidtype), allocatable  :: lvoids(:)
real(kind=sgl),allocatable :: lsg(:,:)
type (dislocationtype), allocatable  :: lDL(:)
type (YDtype), allocatable  :: YDL(:)
type (stackingfaulttype), allocatable  :: lSF(:)
type (inclusiontype), allocatable  :: linclusions(:)
! before we start the threads, we need to copy data from various modules
! into local variables that can then be accessed by the threads ...
 Nmat = 10000
! foil unit normal in microscope frame
 nunit = matmul(foil%Fn,transpose(foil%a_mc))
! foil normal parameters for zpos computation
 fx = -nunit(1)/nunit(3)
 fy = -nunit(2)/nunit(3)
 fz = foil%zb*0.5
! other parameters
 z0 = foil%z0
 thick = foil%zb
 zero = cmplx(0.0,0.0)
 afi = foil%a_fi
 afc = foil%a_fc
 if (allocated(voids)) then
   allocate(lvoids(numvoids))
   lvoids = voids
 endif
 allocate(lsg(foil%npix,foil%npiy))
 lsg = foil%sg
 if (allocated(DL)) then
   allocate(lDL(numdisl+2*numsf))
   lDL = DL
 endif
 if (allocated(YD)) then
   allocate(YDL(numYdisl))
   YDL = YD
 endif
 if (allocated(SF)) then
   allocate(lSF(numsf))
   do ii=1,numsf
     allocate(lSF(ii)%zpos(foil%npix,foil%npiy))
   end do
   lSF = SF
 endif
 if (allocated(inclusions)) then
   allocate(linclusions(numinc))
   linclusions = inclusions
 end if
! ok, we've copied all the necessary variables into local structures
! now we can perform the multi-threaded loop
! initiate multi-threaded segment
!$OMP     PARALLEL PRIVATE(TID,lDFR,gdotR,i,j,k,imat,zt,xpos,ypos,zpos,islice,dis,sumR,tmp,tmpf, &
!$OMP&   ii,void,za,zar,zai,zaamp,zaphase,zr,zi,u,jcnt) &
!$OMP&   SHARED(NTHR,lDFnpix,lDFnpiy,lDFnums,DF_L,numvoids,numdisl,numsf,numinc,disparray,t_interval, &
!$OMP&    fx,fy,fz,z0,thick,zero,afi,afc,lvoids,lsg,lSF,linclusions,lDL,Nmat,YDL)
!  NTHR = OMP_GET_NUM_THREADS()
!  TID = OMP_GET_THREAD_NUM()
TID = 0
NTHR = 1
  if (TID.eq.0) then
! do time reporting only in the master thread
    write (*,*) 'Message from master thread ',TID,': splitting into ',NTHR,' threads '
    call Time_reset
    call Time_report(0.01*t_interval)
    call Time_start
    jcnt = 0
  end if
!$OMP barrier
!$OMP DO SCHEDULE (GUIDED)
  do i=1,lDFnpix
    do j=1,lDFnpiy
! compute the displacement vectors lDFR for all points in this column
! scale the image coordinates with respect to the origin at the center of the image;
! this is where we need to include the zoom factor ...
      xpos = float(i-lDFnpix/2) * DF_L
      ypos = float(j-lDFnpiy/2) * DF_L
      zt =  (xpos*fx+ypos*fy+fz)
! loop over all slices (this is the main loop)
 sliceloop: do islice = 1,lDFnums
      lDFR = 0.0
! zpos is the position down the column, starting at zt (in image coordinates)
      zpos = zt - float(islice)*DF_slice
! set the displacements to zero
       sumR = 0.0
! convert image point (xpos,ypos,zpos) to tmpf in the foil reference frame
!       tmpf = matmul(matmul((/ xpos, ypos, zpos /),transpose(afi)),afc)
       tmpf = matmul( (/ xpos, ypos, zpos /),transpose(afi))
! let's put a few dislocations in ... (see section 8.4.2)
       do ii=1,numdisl
! convert the defect location from untilted image space to the tilted foil reference frame, and subtract it from the current
! column and slice position
         tmp =  (/ xpos, ypos, zpos /) - matmul( (/ DF_L*lDL(ii)%id, DF_L*lDL(ii)%jd, lDL(ii)%zfrac*z0 /), transpose(afi) )
! then convert the difference vector to the defect reference frame for this dislocation (we will only need the x and y coordinates)
         tmp = matmul(tmp,lDL(ii)%a_id)
! check the z-coordinate; if it falls beyond the dislocation line that is inside the foil, then skip
! the displacement computation... the top and bottom coordinates of the dislocation intersections
! measured along the dislocation line were pre-computed when the dislocations were first read from
! the namelist files...
!         if (abs(tmp(3)).le.lDL(ii)%zu) then
! compute x1 + p_alpha x2  (eq. 8.38)
          za(1:3) = tmp(1) + lDL(ii)%pa(1:3)*tmp(2)
! compute the displacement vector u (eq. 8.38) [this expands the log of a complex number and takes the real part only]
          if (tmp(1).gt.0.0) then
           do k=1,3
            zar =  real(za(k))
            zai = aimag(za(k))
            zaamp = abs(za(k))
            zaphase = abs(zai/zar)
            zr(k) = log(zaamp)
            zi(k) = atan(zaphase)
            if (zar.le.0.0) then
              if (zai.lt.0.0) zi(k) = -cPi+zi(k)
              if (zai.eq.0.0) zi(k) = cPi
              if (zai.gt.0.0) zi(k) = cPi-zi(k)
            else
              if (zai.lt.0.0) zi(k) = -zi(k)
            end if
           end do
          else
           do k=1,3
            zar =  real(za(k))
            zai = aimag(za(k))
            zaamp = abs(za(k))
            zaphase = abs(zai/zar)
            zr(k) = log(zaamp)
            zi(k) = atan(zaphase)
            if (zar.le.0.0) then
              if (zai.gt.0.0) zi(k) = cPi-zi(k)
              if (zai.eq.0.0) zi(k) = cPi
              if (zai.lt.0.0) zi(k) = cPi+zi(k)
            else
              if (zai.lt.0.0) zi(k) = 2.0*cPi-zi(k)
              if (zai.eq.0.0) zi(k) = 0.0
            end if
           end do
          end if
          u = 2.0*real(matmul(lDL(ii)%dismat,cmplx(zr,zi)))
! transform displacement vector u to the Cartesian crystal reference frame and then to the foil frame
          u = matmul(matmul(u,lDL(ii)%a_dc),transpose(afc))
          sumR = sumR + u
!         end if
       end do
! do we have any dislocations with surface relaxations ?  YSH model
       if (numYdisl.gt.0) then
        do ii=1,numYdisl
! first, figure out what the coordinates are in the YSH reference frame for this dislocation ...
! translate to the defect origin
         tmp =  (/ xpos, ypos, zpos /) -  (/ DF_L*YDL(ii)%id, DF_L*YDL(ii)%jd, z0*0.5 /)
! rotate into the defect reference frame
         tmp = matmul(tmp,YDL(ii)%a_id)
! compute the displacement vector
         u = sngl(YSHDisp(dble(tmp(1)),dble(tmp(2)),dble(tmp(3)),ii))
!         write (*,*) u
! and rotate back to the image reference frame
         u = matmul(u,YDL(ii)%a_di)
! that should do it !
         sumR = sumR + u
       end do
      end if
! stacking faults (this is easy because we've already done all the work in the stacking_fault module)
!       do ii=1,numsf
!         if ((zpos.lt.lSF(ii)%zpos(i,j)).and.(lSF(ii)%zpos(i,j).ne.-10000.0)) then
!           sumR = sumR + lSF(ii)%lpbc
!         end if
!       end do
! write(*,*) sumR(1:3)
      disparray(islice,i,j,1:3) = sumR(1:3)
!      if (i.eq.10) write (*,*) sumR(1:3)
    end do sliceloop
   end do  ! j-loop
  if (TID.eq.0) then
    jcnt = jcnt+1
    if (mod(jcnt,t_interval).eq.0) call Time_remaining(jcnt,lDFnpix/NTHR)
  endif
end do  ! i-loop
!$OMP END DO
 if (TID.eq.0) call Time_stop(DF_npix*DF_npiy)
!$OMP END PARALLEL
end subroutine CalcRLocal
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
calcrlocal calls float, time_reset, time_start, yshdisp, time_remaining, sngl, time_stop, time_report
time_start calls time_reset
yshdisp calls datan2
time_remaining calls float, printtime, writevalue, message
time_stop calls float, printtime, writevalue, message
time_report calls message
printtime calls writevalue
dispfield calls calcrlocal