CLinit_PDCCQ – Fortran Program
CLinit_PDCCQ Subroutine
52 statements
Source File
public recursive subroutine CLinit_PDCCQ(platform, nump, selnump, device, numd, selnumd, devinfo, context, command_queue)
Uses:
iso_c_binding
error
io
@author Marc De Graef, Carnegie Mellon University @brief initalize a CL platform, device, context, and command queue @param @date 02/23/16 MDG 1.0 original
Arguments
Type Intent Optional Attributes Name
integer(kind=c_intptr_t), allocatable, target :: platform(:)
integer(kind=irg), intent(out) :: nump
integer(kind=irg), intent(in) :: selnump
integer(kind=c_intptr_t), allocatable, target :: device(:)
integer(kind=irg), intent(out) :: numd
integer(kind=irg), intent(in) :: selnumd
character(len=fnlen), intent(out) :: devinfo
integer(kind=c_intptr_t), target :: context
integer(kind=c_intptr_t), target :: command_queue
Calls
Called By
Source Code
CLinit_PDCCQ
Source Code
recursive subroutine CLinit_PDCCQ(platform, nump, selnump, device, numd, selnumd, devinfo, context, command_queue)
!DEC$ ATTRIBUTES DLLEXPORT :: CLinit_PDCCQ
use ISO_C_BINDING
use error
use io
IMPLICIT NONE
integer(c_intptr_t),allocatable, target  :: platform(:)
integer(kind=irg), INTENT(OUT)           :: nump
integer(kind=irg), INTENT(IN)            :: selnump
integer(c_intptr_t),allocatable, target  :: device(:)
integer(kind=irg), INTENT(OUT)           :: numd
integer(kind=irg), INTENT(IN)            :: selnumd
character(fnlen),INTENT(OUT)             :: devinfo
integer(c_intptr_t),target               :: context
integer(c_intptr_t),target               :: command_queue
integer(c_int32_t)                       :: ierr
integer(c_size_t)                        :: cnuminfo
character(fnlen),target                  :: info
integer(c_intptr_t),target               :: ctx_props(3)
integer(c_int64_t)                       :: cmd_queue_props
! get the platform ID
ierr = clGetPlatformIDs(0, C_NULL_PTR, nump)
call CLerror_check('CLinit_PDCCQ:clGetPlatformIDs',ierr)
allocate(platform(nump))
ierr = clGetPlatformIDs(nump, C_LOC(platform), nump)
call CLerror_check('CLinit_PDCCQ:clGetPlatformIDs',ierr)
if (selnump.gt.nump) then
  call FatalError("CLinit_PDCCQ","non-existing platform id requested")
end if
! get the device ID
ierr =  clGetDeviceIDs(platform(selnump), CL_DEVICE_TYPE_GPU, 0, C_NULL_PTR, numd)
call CLerror_check('CLinit_PDCCQ:clGetDeviceIDs',ierr)
allocate(device(numd))
ierr =  clGetDeviceIDs(platform(selnump), CL_DEVICE_TYPE_GPU, numd, C_LOC(device), numd)
call CLerror_check('CLinit_PDCCQ:clGetDeviceIDs',ierr)
if (selnumd.gt.numd) then
  call FatalError("CLinit_PDCCQ","non-existing device id requested")
end if
! get the device name and return it as devinfo
ierr = clGetDeviceInfo(device(selnumd), CL_DEVICE_NAME, sizeof(info), C_LOC(info), cnuminfo)
call CLerror_check('CLinit_PDCCQ:clGetDeviceInfo',ierr)
if (cnuminfo.gt.fnlen) then
  call WriteValue("CLinit_PDCCQ","device info string truncated to 132 characters")
  devinfo = trim(info(1:132))
else
  devinfo = trim(info(1:cnuminfo))
end if
! create the context and the command queue
ctx_props(1) = CL_CONTEXT_PLATFORM
ctx_props(2) = platform(selnump)
ctx_props(3) = 0
context = clCreateContext(C_LOC(ctx_props), numd, C_LOC(device),C_NULL_FUNPTR, C_NULL_PTR, ierr)
call CLerror_check('CLinit_PDCCQ:clCreateContext',ierr)
cmd_queue_props = 0
command_queue = clCreateCommandQueue(context, device(selnumd), cmd_queue_props, ierr)
call CLerror_check('CLinit_PDCCQ:clCreateCommandQueue',ierr)
end subroutine CLinit_PDCCQ
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
clinit_pdccq calls clgetdeviceinfo, fatalerror, clgetplatformids, clcreatecontext, clcreatecommandqueue, writevalue, clgetdeviceids, clerror_check
clerror_check calls fatalerror, writevalue
emsoftcgetmcopencl calls clinit_pdccq