CLquery_platform_info – Fortran Program
CLquery_platform_info Subroutine
139 statements
Source File
public recursive subroutine CLquery_platform_info(platform_id)
Uses:
iso_c_binding
@author Marc De Graef, Carnegie Mellon University @brief display information about an OpenCL device (based on (clfortran's query_platforms_devices.f90) @param platform_id id number of platform @date 02/18/16 MDG 1.0 modification of clfortran's original routine @date 05/21/16 MDG 1.1 split CPU and GPU device information into separate blocks
Arguments
Type Intent Optional Attributes Name
integer(kind=c_intptr_t), intent(in) :: platform_id
Calls
Source Code
CLquery_platform_info
Source Code
recursive subroutine CLquery_platform_info(platform_id)
!DEC$ ATTRIBUTES DLLEXPORT :: CLquery_platform_info
use ISO_C_BINDING
IMPLICIT NONE
! Input variable.
integer(c_intptr_t), INTENT(IN):: platform_id
! Helper variables to work with OpenCL API.
integer(c_int32_t)             :: err
integer(c_size_t)              :: zero_size = 0
integer(c_size_t)              :: temp_size
! For quering devices.
integer(c_int64_t)             :: device_type
integer(c_int32_t)             :: num_devices
integer(c_int)                 :: i
integer(c_intptr_t), allocatable, target :: device_ids(:)
! String arrays for holding platform details.
character, allocatable, target :: platform_profile(:)
character, allocatable, target :: platform_version(:)
character, allocatable, target :: platform_name(:)
character, allocatable, target :: platform_vendor(:)
character, allocatable, target :: platform_extensions(:)
! String array for holding device name.
character, allocatable, target :: device_name(:)
! Maximum compute units for device.
integer(c_size_t), target      :: device_mwgs, device_mwis(3)
integer(c_int32_t), target     :: device_cu
integer(c_int64_t), target     :: device_gms, device_mmas
! Profile.
err = clGetPlatformInfo(platform_id, CL_PLATFORM_PROFILE, zero_size, C_NULL_PTR, temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
allocate(platform_profile(temp_size))
err = clGetPlatformInfo(platform_id, CL_PLATFORM_PROFILE, temp_size, C_LOC(platform_profile), temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
print *, 'Profile: ', platform_profile
deallocate(platform_profile)
! Version.
err = clGetPlatformInfo(platform_id, CL_PLATFORM_VERSION, zero_size, C_NULL_PTR, temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
allocate(platform_version(temp_size))
err = clGetPlatformInfo(platform_id, CL_PLATFORM_VERSION, temp_size, C_LOC(platform_version), temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
print *, 'Version: ', platform_version
deallocate(platform_version)
! Name.
err = clGetPlatformInfo(platform_id, CL_PLATFORM_NAME, zero_size, C_NULL_PTR, temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
allocate(platform_name(temp_size))
err = clGetPlatformInfo(platform_id, CL_PLATFORM_NAME, temp_size, C_LOC(platform_name), temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
print *, 'Name: ', platform_name
deallocate(platform_name)
! Vendor.
err = clGetPlatformInfo(platform_id, CL_PLATFORM_VENDOR, zero_size, C_NULL_PTR, temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
allocate(platform_vendor(temp_size))
err = clGetPlatformInfo(platform_id, CL_PLATFORM_VENDOR, temp_size, C_LOC(platform_vendor), temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
print *, 'Vendor: ', platform_vendor
deallocate(platform_vendor)
! Extensions.
err = clGetPlatformInfo(platform_id, CL_PLATFORM_EXTENSIONS, zero_size, C_NULL_PTR, temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
allocate(platform_extensions(temp_size))
err = clGetPlatformInfo(platform_id, CL_PLATFORM_EXTENSIONS, temp_size, C_LOC(platform_extensions), temp_size)
call CLerror_check('CLquery_platform_info:clGetPlatformInfo',err)
print *, 'Extensions: ', platform_extensions
deallocate(platform_extensions)
!
! Print device information for this platform.
!
! Get device count.
print *
! device_type = CL_DEVICE_TYPE_CPU
err = clGetDeviceIDs(platform_id, CL_DEVICE_TYPE_CPU, 0, C_NULL_PTR, num_devices)
call CLerror_check('CLquery_platform_info:clGetDeviceIDs',err,.TRUE.)
if (err /= CL_SUCCESS .or. num_devices < 1) then
  print *, 'No CPU devices found on this platform'
else
  print *
  print '(A, I2)', 'Num CPU Devices: ', num_devices
! Allocate an array to hold device handles.
  allocate(device_ids(num_devices))
! Get device IDs.
  err = clGetDeviceIDs(platform_id, CL_DEVICE_TYPE_CPU, num_devices, C_LOC(device_ids), num_devices)
  call CLerror_check('CLquery_platform_info:clGetDeviceIDs',err)
  if (err /= CL_SUCCESS) then
    print *, 'Error quering CPU devices: ', err
    return
  end if
! Loop over devices and print information.
  do i = 1, num_devices
! Maximum compute units.
    temp_size = 8
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_MAX_COMPUTE_UNITS, temp_size, C_LOC(device_cu), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
    temp_size = 8
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_GLOBAL_MEM_SIZE, temp_size, C_LOC(device_gms), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
    device_gms = device_gms/1024/1024/1024
! temp_size = 8
! err = clGetDeviceInfo(device_ids(i), CL_DEVICE_MAX_MEM_ALLOC_SIZE, temp_size, C_LOC(device_gms), temp_size)
!write (*,*) 'mmas : ', device_mmas
! CL_DEVICE_MAX_WORK_GROUP_SIZE
    temp_size = 8
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_MAX_WORK_GROUP_SIZE, temp_size, C_LOC(device_mwgs), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
! CL_DEVICE_MAX_WORK_ITEM_SIZES
    temp_size = 8 * 3
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_MAX_WORK_ITEM_SIZES, temp_size, C_LOC(device_mwis), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
! Name.
    temp_size = 4
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_NAME, zero_size, C_NULL_PTR, temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
    allocate(device_name(temp_size))
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_NAME, temp_size, C_LOC(device_name), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
! Print brief device details. Since this routine can be used by the user to determine GPU device IDs,
! we subtract 1 from the device ID to make sure that the CPU gets number 0...
    write (*, '(A,I2,A,I4,A,I4,A,I4,A,I4,A,I4,A,I3,A,$)') ' Device (#', i, ', CU/MWGS/MWIS/GMS: ',device_cu,'/',device_mwgs,'/',&
                                                   device_mwis(1),',',device_mwis(2),',',device_mwis(3),'/',device_gms,') - '
    print *, device_name
    deallocate(device_name)
  end do
end if
! Get device count.
!device_type = CL_DEVICE_TYPE_ALL
print *
err = clGetDeviceIDs(platform_id, CL_DEVICE_TYPE_GPU, 0, C_NULL_PTR, num_devices)
call CLerror_check('CLquery_platform_info:clGetDeviceIDs',err,.TRUE.)
if (err /= CL_SUCCESS .or. num_devices < 1) then
  print *, 'No GPU devices found on this platform '
else
  print *
  print '(A, I2)', 'Num GPU Devices: ', num_devices
! Allocate an array to hold device handles.
  if (allocated(device_ids)) deallocate(device_ids)
  allocate(device_ids(num_devices))
! Get device IDs.
  err = clGetDeviceIDs(platform_id, CL_DEVICE_TYPE_GPU, num_devices, C_LOC(device_ids), num_devices)
  call CLerror_check('CLquery_platform_info:clGetDeviceIDs',err)
  if (err /= CL_SUCCESS) then
    print *, 'Error quering devices: ', err
    return
  end if
! Loop over devices and print information.
  do i = 1, num_devices
! Maximum compute units.
    temp_size = 8
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_MAX_COMPUTE_UNITS, temp_size, C_LOC(device_cu), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
    temp_size = 8
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_GLOBAL_MEM_SIZE, temp_size, C_LOC(device_gms), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
    device_gms = device_gms/1024/1024/1024
! temp_size = 8
! err = clGetDeviceInfo(device_ids(i), CL_DEVICE_MAX_MEM_ALLOC_SIZE, temp_size, C_LOC(device_gms), temp_size)
!write (*,*) 'mmas : ', device_mmas
! CL_DEVICE_MAX_WORK_GROUP_SIZE
    temp_size = 8
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_MAX_WORK_GROUP_SIZE, temp_size, C_LOC(device_mwgs), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
! CL_DEVICE_MAX_WORK_ITEM_SIZES
    temp_size = 8 * 3
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_MAX_WORK_ITEM_SIZES, temp_size, C_LOC(device_mwis), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
! Name.
    temp_size = 4
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_NAME, zero_size, C_NULL_PTR, temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
    allocate(device_name(temp_size))
    err = clGetDeviceInfo(device_ids(i), CL_DEVICE_NAME, temp_size, C_LOC(device_name), temp_size)
    call CLerror_check('CLquery_platform_info:clGetDeviceInfo',err)
! Print brief device details. Since this routine can be used by the user to determine GPU device IDs,
! we subtract 1 from the device ID to make sure that the CPU gets number 0...
    write (*, '(A,I2,A,I4,A,I4,A,I4,A,I4,A,I4,A,I3,A,$)') ' Device (#', i, ', CU/MWGS/MWIS/GMS: ',device_cu,'/',device_mwgs,'/',&
                                                   device_mwis(1),',',device_mwis(2),',',device_mwis(3),'/',device_gms,') - '
    print *, device_name
    deallocate(device_name)
  end do
end if
print *,' '
write (*,*) '[CU = Compute Units; MWGS = Maximum Work Group Size; MWIS = Maximum Work Item Sizes (3D); '// &
            'GMS = Global Memory Size (Gb)]'
end subroutine CLquery_platform_info
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
clquery_platform_info calls clgetplatforminfo, clgetdeviceinfo, clerror_check, clgetdeviceids
clerror_check calls writevalue, fatalerror