DD_Mstep – Fortran Program
DD_Mstep Function
60 statements
Source File
private recursive function DD_Mstep(X, dict, Pmdims, nums, R, Dtype) result(MuKa)
Uses:
local
typedefs
quaternions
@author Marc De Graef, Carnegie Mellon University / Yu-Hui Chen, U. Michigan @brief computes the M step of the EM process @param X list of input quaternions @param dict dictionary type @param Pmdims number of quaternion symmetry operators @param nums number of samples @param R weight factors form the E step @param Dtype 'VMF' or 'WAT' @date 01/01/15 MDG 1.0 original @date 01/06/15 MDG 1.1 added optional full parameter @date 01/09/15 MDG 1.2 removed optional argument full (incorporated in dicttype) @date 01/09/15 MDG 1.3 introduced accurate numerical approximation for kappa determination @date 02/06/15 MDG 1.4 removed full handling after extensive checking @date 02/06/15 MDG 1.5 merged Msteps for VMF and WAT and renamed
Arguments
Type Intent Optional Attributes Name
real(kind=dbl), intent(in) :: X(4,nums)
type(dicttype), intent(in) :: dict
integer(kind=irg), intent(in) :: Pmdims
integer(kind=irg), intent(in) :: nums
real(kind=dbl), intent(in) :: R(nums,Pmdims)
character(len=3), intent(in) :: Dtype
Return Value real(kind=dbl) (5)
Calls
Called By
Source Code
DD_Mstep
Source Code
recursive function DD_Mstep(X,dict,Pmdims,nums,R,Dtype) result(MuKa)
!DEC$ ATTRIBUTES DLLEXPORT :: DD_Mstep
use local
use typedefs
use quaternions
IMPLICIT NONE
real(kind=dbl),INTENT(IN)               :: X(4,nums)
type(dicttype),INTENT(IN)       :: dict
integer(kind=irg),INTENT(IN)            :: Pmdims
integer(kind=irg),INTENT(IN)            :: nums
real(kind=dbl),INTENT(IN)               :: R(nums,Pmdims)
character(3),INTENT(IN)                 :: Dtype
real(kind=dbl)                          :: MuKa(5)
real(kind=dbl)                          :: tmpGamma(4), nGamma, diff(dict%Apnum), qu(4), y, Tscatt(4,4), tmp(4,4)
integer(kind=irg)                       :: minp, i, j
! variables needed for the dsyev Lapack eigenvalue routine
CHARACTER                               :: JOBZ, UPLO
INTEGER                                 :: INFO, LDA, LWORK, NN
DOUBLE PRECISION                        :: A(4 , 4), W(4), WORK(20)
if (Dtype.eq.'VMF') then
! this is simplified from the Matlab routine and uses straight summations and
! quaternion multiplication instead of arrays
  tmpGamma = 0.D0
  do j=1,Pmdims
    do i=1,nums
      qu = quat_mult(X(1:4,i),conjg(dict%Pm(1:4,j)))
      tmpGamma = tmpGamma +  R(i,j) * qu
    end do
  end do
  nGamma = cabs(tmpGamma)
  MuKa(1:4) = tmpGamma/nGamma
  y = nGamma/dble(nums)
end if
if (Dtype.eq.'WAT') then
! here, we compute the modified scattering matrix Tscatt and compute its largest eigenvalue
! under the assumption that kappa will always be positive for the types of problems that we
! need to consider; we need to use the outer product, implemented using spread calls
  Tscatt = 0.D0
  do j=1,Pmdims
    do i=1,nums
      qu = quat_mult(X(1:4,i),conjg(dict%Pm(1:4,j)))
      tmp = spread(qu,dim=2,ncopies=4)*spread(qu,dim=1,ncopies=4)
      Tscatt = Tscatt + R(i,j) * tmp
    end do
  end do
  Tscatt = Tscatt/dble(nums)
  JOBZ = 'V'
  UPLO = 'U'
  NN = 4
  LDA = 4
  LWORK = 20
  A = Tscatt
  call DSYEV( JOBZ, UPLO, NN, A, LDA, W, WORK, LWORK, INFO )
  qu(1:4) = A(1:4,4)
  MuKa(1:4) = qu(1:4)
  y = dot_product(qu,matmul(Tscatt,qu))
end if
! find kappa corresponding to this value of gamma (equation 17 in appendix of paper)
! we split this into two regionds: 0<=y<0.94, for which we use the look-up table
! approach, and 0.94<=y<=1, for which we have derived an analytical approximation
! that is pretty accurate in the relevant region of kappa>30.
if (y.ge.0.94D0) then
  if (Dtype.eq.'VMF') MuKa(5) = (15.D0-3.D0*y+dsqrt(15.D0+90.D0*y+39.D0*y*y))/(16.D0*(1.0D0-y))
  if (Dtype.eq.'WAT') MuKa(5) = (5.D0*y-11.D0-dsqrt(39.D0-12.D0*y+9.D0*y**2))/(8.D0*(y-1.D0))
else
  diff = dabs( y - dict%yAp )
  minp = minloc( diff, 1 )
  if (minp.eq.1) minp = 2
  MuKa(5) = dict%xAp(minp)
end if
end function DD_Mstep
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
dd_mstep calls quat_mult, dsyev
di_emfordd calls dd_mstep