EBSD4calfun – Fortran Program
EBSD4calfun Subroutine
206 statements
Source File
public recursive subroutine EBSD4calfun(nipar, nfpar, ninit, ipar, fpar, initmeanval, expt, accum_e, mLPNH, mLPSH, n, x, f, expt2, expt3, expt4, nstep, stepsize, verbose)
Uses:
local
rotations
constants
distortion
filters
Indexingmod
iso_c_binding
@author Saransh Singh, Carnegie Mellon University @brief This function is used by bobyqa to fit an EBSD pattern @details The main purpose of this routine is to calculte the difference of 1 with the dot product of an experimental pattern with the given set of detector parameters. This is used by bobyqa module to fit an EBSD pattern when 4 patterns are fitted simultaneously
This routine will first compute the detector arrays rgx etc. if necessary, and then perform the usual interpolation from the square Lambert projection. The pattern will be a basic pattern, without any intensity scaling or binning etc; the calling program should take care of those operations. @param ipar array with integer input parameters @param fpar array with float input parameters @param initmeanval mean value of search space @param EBSDpattern output array @param quats quaternion input array @param accum_e array with Monte Carlo histogram @param mLPNH Northern hemisphere master pattern @param mLPSH Southern hemisphere master pattern @date 12/12/15 SS 1.0 original @date 03/28/16 SS 1.1 omega is no longer a variable parameter
Arguments
Type Intent Optional Attributes Name
integer(kind=irg), intent(in) :: nipar
integer(kind=irg), intent(in) :: nfpar
integer(kind=irg), intent(in) :: ninit
integer(kind=c_size_t), intent(in) :: ipar(nipar)
real(kind=sgl), intent(inout) :: fpar(nfpar)
real(kind=sgl), intent(in) :: initmeanval(ninit)
real(kind=c_float), intent(in) :: expt(ipar(2)*ipar(3)/ipar(12)/ipar(12))
real(kind=sgl), intent(in) :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
real(kind=sgl), intent(in) :: mLPNH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(10),ipar(7))
real(kind=sgl), intent(in) :: mLPSH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(10),ipar(7))
integer(kind=irg), intent(in) :: n
real(kind=dbl), intent(in), dimension(:) :: x
real(kind=dbl), intent(out) :: f
real(kind=c_float), intent(in) :: expt2(ipar(2)*ipar(3)/ipar(12)/ipar(12))
real(kind=c_float), intent(in) :: expt3(ipar(2)*ipar(3)/ipar(12)/ipar(12))
real(kind=c_float), intent(in) :: expt4(ipar(2)*ipar(3)/ipar(12)/ipar(12))
integer(kind=irg), intent(in) :: nstep
real(kind=sgl), intent(in) :: stepsize(nstep)
logical, intent(in), optional :: verbose
Calls
Source Code
EBSD4calfun
Source Code
recursive subroutine EBSD4calfun(nipar, nfpar, ninit, ipar, fpar, initmeanval, expt, accum_e, &
                                mLPNH, mLPSH, n, x, f, expt2, expt3, expt4, nstep, stepsize, verbose)
!DEC$ ATTRIBUTES DLLEXPORT :: EBSD4calfun
! the input parameters are all part of a ipar and fpar input arrays instead of the usual namelist structures.
! The following is the mapping:
!
! ipar(1) = 2
! ipar(2) = detnumsx
! ipar(3) = detnumsy
! ipar(4) = detnumEbins
! ipar(5) = mcnsx
! ipar(6) = mpnpx
! ipar(7) = numset
! ipar(8) = numquats
! ipar(9) = Emin
! ipar(10) = Emax
! ipar(11) = 0/1 ;0 for no mask, 1 for mask
! ipar(12) = binning
! ipar(13) = pixx_pat1
! ipar(14) = pixy_pat1
! ipar(15) = pixx_pat2
! ipar(16) = pixy_pat2
! ipar(17) = pixx_pat3
! ipar(18) = pixy_pat3
! ipar(19) = pixx_pat4
! ipar(20) = pixy_pat4
! fpar(1) = enl%xpc
! fpar(2) = enl%ypc
! fpar(3) = enl%delta
! fpar(4) = enl%MCsig
! fpar(5) = enl%omega
! fpar(6) = enl%thetac
! fpar(7) = enl%L
! fpar(8) = enl%beamcurrent
! fpar(9) = enl%dwelltime
! fpar(10) = enl%gammavalue
! fpar(11) = maskradius
! fpar(12) = stepx
! fpar(13) = stepy
! initmeanval(1) = fpar(7)
! initmeanval(2) = phi1
! initmeanval(3) = phi
! initmeanval(4) = phi2
! initmeanval(5) = xpc
! initmeanval(6) = ypc
! stepsize(1) = step_xpc
! stepsize(2) = step_ypc
! stepsize(3) = step_phi1 ; all 4 patterns
! stepsize(4) = step_phi ; all 4 patterns
! stepsize(5) = step_phi2 ; all 4 patterns
! stepsize(6) = step_L
! X = (/xpc, ypc, omega, L, phi1, phi, phi2/)
use local
use rotations
use constants
use distortion
use filters
use Indexingmod, ONLY:Jaccard_Distance
use,INTRINSIC :: ISO_C_BINDING
implicit none
integer(irg),intent(in)                 :: nipar
integer(irg),intent(in)                 :: nfpar
integer(irg),intent(in)                 :: ninit
integer(c_size_t),intent(in)            :: ipar(nipar)
real(sgl),intent(inout)                 :: fpar(nfpar)
real(sgl),intent(in)                    :: initmeanval(ninit)
integer(irg),intent(in)                 :: nstep
real(sgl),intent(in)                    :: stepsize(nstep)
real(c_float),intent(in)                :: expt(ipar(2)*ipar(3)/ipar(12)/ipar(12))
real(c_float),intent(in)                :: expt2(ipar(2)*ipar(3)/ipar(12)/ipar(12))
real(c_float),intent(in)                :: expt3(ipar(2)*ipar(3)/ipar(12)/ipar(12))
real(c_float),intent(in)                :: expt4(ipar(2)*ipar(3)/ipar(12)/ipar(12))
real(kind=sgl),INTENT(in)               :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
real(kind=sgl),INTENT(in)               :: mLPNH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(10), ipar(7))
real(kind=sgl),INTENT(in)               :: mLPSH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(10), ipar(7))
integer(irg),intent(in)                 :: n
real(dbl),dimension(:),intent(in)       :: x
real(dbl),intent(out)                   :: f
logical,intent(in),optional             :: verbose
integer(kind=irg)                       :: nnx, nny, binx, biny
complex(dbl)                            :: D
real(kind=sgl)                          :: quats(4,1), bindx, ma, mi
real(kind=sgl),allocatable              :: EBSDpattern(:,:,:), binned(:,:)
real(kind=sgl),allocatable              :: EBSDpatternintd(:,:)
integer(kind=irg),allocatable           :: EBSDpatterninteger(:,:), EBSDpatternad(:,:)
! variables that must be saved for the next time this function is called
real(kind=sgl)                          :: prefactor
integer(kind=irg),allocatable           :: img1(:), img2(:), img_fit_cumul(:), img_expt_cumul(:)
! other variables
real(kind=sgl),parameter                :: dtor = 0.0174533  ! convert from degrees to radians
real(kind=sgl)                          :: ixy(2), eu(3), eu2(3), eu3(3), eu4(3)
real(kind=sgl), allocatable             :: EBSDvector(:), EBSDflip(:,:), mask(:,:)
integer(kind=irg)                       :: i, j, istat
logical                                 :: stat, readonly
integer(kind=irg)                       :: hdferr, nlines
real(kind=sgl)                          :: fpar2(nfpar)
!fpar(1) = sngl(X(1))*ipar(2) - ipar(2)/2 + initmeanval(5) ! xpc +/- detnumx/2 pixels
!fpar(2) = sngl(X(2))*ipar(3) - ipar(3)/2 + initmeanval(6) ! ypc +/- detnumy/2 pixels
fpar(1) = sngl(X(1))*2.0*stepsize(1) - stepsize(1) + initmeanval(5) ! xpc +/- 5 pixels
fpar(2) = sngl(X(2))*2.0*stepsize(2) - stepsize(2) + initmeanval(6) ! ypc +/- 5 pixels
!fpar(1) = initmeanval(5) ! xpc +/- detnumx/2 pixels
!fpar(2) = initmeanval(6) ! ypc +/- detnumy/2 pixels
fpar(7) = sngl(X(4))*2.0*stepsize(6)*fpar(3) - stepsize(6)*fpar(3) + initmeanval(1) ! mean +/- 5 pixels
!fpar(7) = initmeanval(1) ! mean +/- 2000 microns
! 03/28/16 omega is no longer a variable parameter anymore
fpar(5) = sngl(X(3))*0.0 - 0.0 ! omega 0 +/- 5 degrees
!eu = (/initmeanval(2), initmeanval(3), initmeanval(4)/)*dtor ! don't change the values for euler angles
eu = (/X(5)*2.0*stepsize(3) - stepsize(3) + initmeanval(2), X(6)*2.0*stepsize(4) - stepsize(4)  + initmeanval(3), &
       X(7)*2.0*stepsize(5) - stepsize(5) + initmeanval(4)/)*dtor ! mean +/- 2 degrees
eu2 = (/X(8)*2.0*stepsize(3) - stepsize(3) + initmeanval(7), X(9)*2.0*stepsize(4) - stepsize(4) + initmeanval(8), &
       X(10)*2.0*stepsize(5) - stepsize(5) + initmeanval(9)/)*dtor ! mean +/- 2 degrees
eu3 = (/X(11)*2.0*stepsize(3) - stepsize(3) + initmeanval(10), X(12)*2.0*stepsize(4) - stepsize(4) + initmeanval(11), &
       X(13)*2.0*stepsize(5) - stepsize(5) + initmeanval(12)/)*dtor ! mean +/- 2 degrees
eu4 = (/X(14)*2.0*stepsize(3) - stepsize(3) + initmeanval(13), X(15)*2.0*stepsize(4) - stepsize(4) + initmeanval(14), &
       X(16)*2.0*stepsize(5) - stepsize(5) + initmeanval(15)/)*dtor ! mean +/- 2 degrees
!D = dcmplx(X(8)*0.000002D0 - 0.000001D0 + dble(initmeanval(5)), X(9)*0.000002D0 - 0.000001D0 + dble(initmeanval(6)))
binx = ipar(2)/ipar(12)
biny = ipar(3)/ipar(12)
bindx = 1.0/float(ipar(12)**2)
allocate(EBSDvector(binx*biny),mask(binx,biny))
allocate(EBSDpattern(ipar(2),ipar(3),1))
allocate(binned(binx,biny))
allocate(EBSDpatternintd(ipar(2),ipar(3)),EBSDpatterninteger(ipar(2),ipar(3)), EBSDpatternad(ipar(2),ipar(3)))
allocate(img1(binx*biny),img2(binx*biny))
allocate(img_fit_cumul(4*binx*biny),img_expt_cumul(4*binx*biny))
binned = 0.0
EBSDpatternintd = 0.0
EBSDpatterninteger = 0
EBSDpatternad = 0
img1 = 0
img2 = 0
img_fit_cumul = 0
img_expt_cumul = 0
mask = 1.0
if (present(verbose)) then
    if(verbose) then
        print*,'xpc, ypc, L, eu_pat1, eu_pat2, eu_pat3, eu_pat4 = ', fpar(1), fpar(2), fpar(7),eu(1:3)*180.0/cPi,&
        eu2(1:3)*180.0/cPi,eu3(1:3)*180.0/cPi,eu4(1:3)*180.0/cPi
    end if
end if
fpar2(1:nfpar) = fpar(1:nfpar)
!==============================================================================
!============IMAGE 1===========================================================
!==============================================================================
quats(1:4,1) = eu2qu(eu)
fpar2(1:nfpar) = fpar(1:nfpar)
fpar2(1) = fpar(1) + ipar(13)*fpar(12)/fpar(3)
fpar2(2) = fpar(2) - ipar(14)*fpar(13)/fpar(3)
call getEBSDPatterns(ipar, fpar2, EBSDpattern, quats, accum_e, mLPNH, mLPSH)
!nnx = ipar(2)
!nny = ipar(3)
!EBSDpatternintd = ((EBSDPattern(:,:,1) - mi)/ (ma-mi))
!EBSDpatterninteger = nint(EBSDpatternintd*255.0)
!EBSDpatternad =  adhisteq(10,nnx,nny,EBSDpatterninteger)
!EBSDPattern(:,:,1) = float(EBSDpatternad)
if (ipar(12) .ne. 1) then
    do i=1,binx
        do j=1,biny
            binned(i,j) = sum(EBSDpattern((i-1)*ipar(12)+1:i*ipar(12),(j-1)*ipar(12)+1:j*ipar(12),1))
        end do
    end do
    binned = binned * bindx
else
    binned(1:binx,1:biny) = EBSDpattern(1:binx,1:biny,1)
end if
if (ipar(11) .eq. 1) then
    do i = 1,binx
        do j = 1,biny
            if(((float(i)-ceiling(float(binx)/2.0))**2 + (float(j)-ceiling(float(biny)/2.0))**2) .gt. fpar(11)**2) then
                mask(i,j) = 0.0
            end if
        end do
    end do
end if
binned(1:binx,1:biny) = binned(1:binx,1:biny)*mask(1:binx,1:biny)
binned = binned**fpar(10)
do i=1,biny
    do j=1,binx
        EBSDvector((i-1)*binx+j) = binned(j,i)
    end do
end do
ma = maxval(EBSDvector)
mi = minval(EBSDvector)
img1 = nint(255.0*(EBSDvector - mi)/(ma - mi))
ma = maxval(expt)
mi = minval(expt)
img2 = nint(255.0*(expt - mi)/(ma - mi))
img_fit_cumul(1:binx*biny) = img1(1:binx*biny)
img_expt_cumul(1:binx*biny) = img2(1:binx*biny)
!open(unit=13,file='/Users/saranshsingh/Desktop/testd.txt',action='write')
!open(unit=14,file='/Users/saranshsingh/Desktop/teste.txt',action='write')
!do i = 1,binx
!    do j = 1,biny
!        write(13,'(F15.6)',advance='no')EBSDvector((i-1)*biny+j)
!        write(14,'(F15.6)',advance='no')expt((i-1)*biny+j)
!    end do
!    write(13,*)''
!    write(14,*)''
!end do
!close(13)
!close(14)
!stop
!==============================================================================
!============IMAGE 2===========================================================
!==============================================================================
quats(1:4,1) = eu2qu(eu2)
fpar2(1:nfpar) = fpar(1:nfpar)
fpar2(1) = fpar(1) + ipar(15)*fpar(12)/fpar(3)
fpar2(2) = fpar(2) - ipar(16)*fpar(13)/fpar(3)
call getEBSDPatterns(ipar, fpar2, EBSDpattern, quats, accum_e, mLPNH, mLPSH)
if (ipar(12) .ne. 1) then
    do i=1,binx
        do j=1,biny
            binned(i,j) = sum(EBSDpattern((i-1)*ipar(12)+1:i*ipar(12),(j-1)*ipar(12)+1:j*ipar(12),1))
        end do
    end do
    binned = binned * bindx
else
    binned(1:binx,1:biny) = EBSDpattern(1:binx,1:biny,1)
end if
binned(1:binx,1:biny) = binned(1:binx,1:biny)*mask(1:binx,1:biny)
binned = binned**fpar(10)
do i=1,biny
    do j=1,binx
        EBSDvector((i-1)*binx+j) = binned(j,i)
    end do
end do
ma = maxval(EBSDvector)
mi = minval(EBSDvector)
img1 = nint(255.0*(EBSDvector - mi)/(ma - mi))
ma = maxval(expt2)
mi = minval(expt2)
img2 = nint(255.0*(expt2 - mi)/(ma - mi))
img_fit_cumul(binx*biny+1:2*binx*biny) = img1(1:binx*biny)
img_expt_cumul(binx*biny+1:2*binx*biny) = img2(1:binx*biny)
!==============================================================================
!============IMAGE 3===========================================================
!==============================================================================
quats(1:4,1) = eu2qu(eu3)
fpar2(1:nfpar) = fpar(1:nfpar)
fpar2(1) = fpar(1) + ipar(17)*fpar(12)/fpar(3)
fpar2(2) = fpar(2) - ipar(18)*fpar(13)/fpar(3)
call getEBSDPatterns(ipar, fpar2, EBSDpattern, quats, accum_e, mLPNH, mLPSH)
if (ipar(12) .ne. 1) then
    do i=1,binx
        do j=1,biny
            binned(i,j) = sum(EBSDpattern((i-1)*ipar(12)+1:i*ipar(12),(j-1)*ipar(12)+1:j*ipar(12),1))
        end do
    end do
    binned = binned * bindx
else
    binned(1:binx,1:biny) = EBSDpattern(1:binx,1:biny,1)
end if
binned(1:binx,1:biny) = binned(1:binx,1:biny)*mask(1:binx,1:biny)
binned = binned**fpar(10)
do i=1,biny
    do j=1,binx
        EBSDvector((i-1)*binx+j) = binned(j,i)
    end do
end do
ma = maxval(EBSDvector)
mi = minval(EBSDvector)
img1 = nint(255.0*(EBSDvector - mi)/(ma - mi))
ma = maxval(expt3)
mi = minval(expt3)
img2 = nint(255.0*(expt3 - mi)/(ma - mi))
img_fit_cumul(2*binx*biny+1:3*binx*biny) = img1(1:binx*biny)
img_expt_cumul(2*binx*biny+1:3*binx*biny) = img2(1:binx*biny)
!==============================================================================
!============IMAGE 4===========================================================
!==============================================================================
quats(1:4,1) = eu2qu(eu4)
fpar2(1:nfpar) = fpar(1:nfpar)
fpar2(1) = fpar(1) + ipar(19)*fpar(12)/fpar(3)
fpar2(2) = fpar(2) - ipar(20)*fpar(13)/fpar(3)
call getEBSDPatterns(ipar, fpar2, EBSDpattern, quats, accum_e, mLPNH, mLPSH)
if (ipar(12) .ne. 1) then
    do i=1,binx
        do j=1,biny
            binned(i,j) = sum(EBSDpattern((i-1)*ipar(12)+1:i*ipar(12),(j-1)*ipar(12)+1:j*ipar(12),1))
        end do
    end do
    binned = binned * bindx
else
    binned(1:binx,1:biny) = EBSDpattern(1:binx,1:biny,1)
end if
binned(1:binx,1:biny) = binned(1:binx,1:biny)*mask(1:binx,1:biny)
binned = binned**fpar(10)
do i=1,biny
    do j=1,binx
        EBSDvector((i-1)*binx+j) = binned(j,i)
    end do
end do
ma = maxval(EBSDvector)
mi = minval(EBSDvector)
img1 = nint(255.0*(EBSDvector - mi)/(ma - mi))
ma = maxval(expt4)
mi = minval(expt4)
img2 = nint(255.0*(expt4 - mi)/(ma - mi))
img_fit_cumul(3*binx*biny+1:4*binx*biny) = img1(1:binx*biny)
img_expt_cumul(3*binx*biny+1:4*binx*biny) = img2(1:binx*biny)
F = Jaccard_Distance(img_fit_cumul,img_expt_cumul,4*binx*biny)
!F = 1.0 - DOT_PRODUCT(EBSDvector,expt)
end subroutine EBSD4calfun
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
ebsd4calfun calls sngl, jaccard_distance, eu2qu, getebsdpatterns, float
getebsdpatterns calls sngl, float, quat_lp, lambertspheretosquare