ECPcalfun – Fortran Program
ECPcalfun Subroutine
91 statements
Source File
public recursive subroutine ECPcalfun(nipar, nfpar, ninit, ipar, fpar, initmeanval, expt, accum_e, mLPNH, mLPSH, n, x, f, nstep, stepsize, verbose)
Uses:
local
rotations
constants
distortion
iso_c_binding
filters
Indexingmod
@author Saransh Singh, Carnegie Mellon University @brief This function is used by bobyqa to fit an EBSD pattern @etails The main purpose of this routine is to calculte the difference of 1 with the dot product of an experimental pattern with the given set of detector parameters. This is used by bobyqa module to fit an EBSD pattern.
This routine will first compute the detector arrays rgx etc. if necessary, and then perform the usual interpolation from the square Lambert projection. The pattern will be a basic pattern, without any intensity scaling or binning etc; the calling program should take care of those operations. @param ipar array with integer input parameters @param fpar array with float input parameters @param initmeanval array with mean value of search space @param ECPattern output array @param quats array of quaternions @param accum_e array with Monte Carlo histogram @param mLPNH Northern hemisphere master pattern @param mLPSH Southern hemisphere master pattern @date 12/12/15 SS 1.0 original
Arguments
Type Intent Optional Attributes Name
integer(kind=irg), intent(in) :: nipar
integer(kind=irg), intent(in) :: nfpar
integer(kind=irg), intent(in) :: ninit
integer(kind=c_size_t), intent(in) :: ipar(nipar)
real(kind=sgl), intent(inout) :: fpar(nfpar)
real(kind=sgl), intent(in) :: initmeanval(ninit)
real(kind=c_float), intent(in) :: expt(ipar(2)*ipar(3)/ipar(12)**2)
real(kind=sgl), intent(in) :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
real(kind=sgl), intent(in) :: mLPNH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(10),ipar(7))
real(kind=sgl), intent(in) :: mLPSH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(10),ipar(7))
integer(kind=irg), intent(in) :: n
real(kind=dbl), intent(in), dimension(:) :: x
real(kind=dbl), intent(out) :: f
integer(kind=irg), intent(in) :: nstep
real(kind=sgl), intent(in) :: stepsize(nstep)
logical, intent(in), optional :: verbose
Calls
Source Code
ECPcalfun
Source Code
recursive subroutine ECPcalfun (nipar, nfpar, ninit, ipar, fpar, initmeanval, expt, accum_e, mLPNH, mLPSH, &
                                n, x, f, nstep, stepsize, verbose)
!DEC$ ATTRIBUTES DLLEXPORT :: ECPcalfun
! the input parameters are all part of a ipar and fpar input arrays instead of the usual namelist structures.
! The following is the mapping:
!
! ipar(1) = 1
! ipar(2) = detnumsx
! ipar(3) = detnumsy
! ipar(4) = numangle
! ipar(5) = mcnsx
! ipar(6) = mpnpx
! ipar(7) = numset
! ipar(8) = numquats
! ipar(9) = 0/1 ;0 for no mask, 1 for mask
! ipar(10) = 1; equal to numEbins
! ipar(11) = 0/1; 0 for DP 1 for JD
! ipar(12) = 1 ;binning
! fpar(1) = ecpnl%thetac
! fpar(2) = ecpnl%sampletilt
! fpar(3) = ecpnl%workingdistance
! fpar(4) = ecpnl%Rin
! fpar(5) = ecpnl%Rout
! fpar(6) = ecpnl%sigstart
! fpar(7) = ecpnl%sigend
! fpar(8) = ecpnl%sigstep
! fpar(9) = ecpnl%gammavalue
! fpar(10) = maskradius
! initmeanval(1) = thetac
! initmeanval(2) = sampletilt
! initmeanval(3) = working distance
! initmeanval(4) = phi1
! initmeanval(5) = phi
! initmeanval(6) = phi2
! stepsize(1) = step_thetacone
! stepsize(2) = step_phi1
! stepsize(3) = step_phi ; all 4 patterns
! stepsize(4) = step_phi2 ; all 4 patterns
use local
use rotations
use constants
use distortion
use,INTRINSIC :: ISO_C_BINDING
use filters
use Indexingmod, ONLY:Jaccard_Distance
IMPLICIT NONE
integer(c_size_t),intent(in)            :: ipar(nipar)
real(sgl),intent(inout)                 :: fpar(nfpar)
real(sgl),intent(in)                    :: initmeanval(ninit)
integer(irg),intent(in)                 :: nipar
integer(irg),intent(in)                 :: nfpar
integer(irg),intent(in)                 :: ninit
real(c_float),intent(in)                :: expt(ipar(2)*ipar(3)/ipar(12)**2)
integer(irg),intent(in)                 :: nstep
real(sgl),intent(in)                    :: stepsize(nstep)
real(kind=sgl),INTENT(in)               :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
real(kind=sgl),INTENT(in)               :: mLPNH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(10), ipar(7))
real(kind=sgl),INTENT(in)               :: mLPSH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(10), ipar(7))
integer(irg),intent(in)                 :: n
real(dbl),dimension(:),intent(in)       :: x
real(dbl),intent(out)                   :: f
logical,intent(in),optional             :: verbose
integer(kind=irg)                       :: nnx, nny
complex(dbl)                            :: D
real(kind=sgl)                          :: quats(4,1), ma, mi
real(kind=sgl),allocatable              :: ECPpattern(:,:,:)
real(kind=sgl),allocatable              :: binned(:,:)
real(kind=sgl),allocatable              :: ECPpatternintd(:,:)
integer(kind=irg),allocatable           :: ECPpatterninteger(:,:), ECPpatternad(:,:)
real(kind=sgl),allocatable              :: ECPvector(:), ECPvectorcpy(:), ECPtmp(:,:)
real(kind=sgl),allocatable              :: mask(:,:)
integer(kind=irg),allocatable           :: img1(:), img2(:)
integer(kind=irg)                       :: istat, i, j
real(kind=sgl),parameter                :: dtor = 0.0174533  ! convert from degrees to radians
real(kind=sgl)                          :: eu(3)
logical                                 :: stat, readonly
integer(kind=irg)                       :: hdferr, nlines, nregions
fpar(1) = sngl(X(1))*2.0*stepsize(1) - stepsize(1) + initmeanval(1) ! thetac mean +/- stepsize degrees degrees only
eu = (/X(2)*2.0*stepsize(2) - stepsize(2) + initmeanval(2), X(3)*2.0*stepsize(3) - stepsize(3)  + initmeanval(3), &
       X(4)*2.0*stepsize(4) - stepsize(4) + initmeanval(4)/)*cPi/180.0 ! mean +/- stepsize
quats(1:4,1) = eu2qu(eu)
!D = dcmplx(0.D0,0.D0)
! read all the files
allocate(ECPvector(ipar(2)*ipar(3)),mask(ipar(2),ipar(3)))
allocate(ECPpattern(ipar(2),ipar(3),ipar(8)))
allocate(ECPpatternintd(ipar(2),ipar(3)),ECPpatterninteger(ipar(2),ipar(3)), ECPpatternad(ipar(2),ipar(3)))
ECPpatternintd = 0.0
ECPpatterninteger = 0
ECPpatternad = 0
if (present(verbose)) then
    if(verbose) then
        print*,'thetac, eu = ',sngl(X(1))*2.0*stepsize(1) - stepsize(1) + initmeanval(1), eu*180.0/cPi
    end if
end if
mask = 1.0
do i = 1,ipar(2)
    do j = 1,ipar(3)
        if(((float(i)-ceiling(float(ipar(2))/2.0))**2 + (float(j)-ceiling(float(ipar(3))/2.0))**2) .gt. fpar(10)**2) then
            mask(i,j) = 0.0
        end if
    end do
end do
call getECPatterns(ipar, fpar, ECPpattern, quats, accum_e, mLPNH, mLPSH)
nnx = ipar(2)
nny = ipar(3)
!nregions = ipar(12)
allocate(ECPvector(ipar(2)*ipar(3)),stat=istat)
if (ipar(9) .eq. 1) then
    do i = 1,ipar(8)
        ECPpattern(:,:,i) = ECPpattern(:,:,i)*mask
    end do
end if
do i=1,ipar(2)
    do j=1,ipar(3)
        ECPvector((i-1)*ipar(3)+j) = ECPpattern(j,i,1)
    end do
end do
!ECPvector = 0.0
!do i = 1,ipar(2)
!    ECPvector((i-1)*ipar(3)+1:i*ipar(3)) = ECPvectorcpy((ipar(2)-i)*ipar(3)+1:(ipar(2)-i+1)*ipar(3))
!end do
ECPvector = ECPvector**fpar(9)
ECPvector = ECPvector/NORM2(ECPvector)
if(IPAR(11) .eq. 0) then
    F = 1.0 - DOT_PRODUCT(ECPvector,expt)
else
    allocate(img1(ipar(2)*ipar(3)),img2(ipar(2)*ipar(3)))
    ma = maxval(ECPvector)
    mi = minval(ECPvector)
    img1 = nint(255.0*(ECPvector - mi)/(ma - mi))
    ma = maxval(expt)
    mi = minval(expt)
    img2 = nint(255.0*(expt - mi)/(ma - mi))
    F = Jaccard_Distance(img1,img2,nnx*nny)
end if
end subroutine ECPcalfun
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
ecpcalfun calls getecpatterns, sngl, jaccard_distance, eu2qu, float
getecpatterns calls sngl, float, quat_lp, lambertspheretosquare