EMsoftCgetMCOpenCL – Fortran Program
EMsoftCgetMCOpenCL Subroutine
261 statements
Source File
public recursive subroutine EMsoftCgetMCOpenCL(ipar, fpar, atompos, atomtypes, latparm, accum_e, accum_z, cproc, objAddress, cancel) bind(c, name="0")
Uses:
local
constants
crystal
constants
symmetry
io
typedefs
clfortran
CLsupport
timing
iso_c_binding
@author Marc De Graef, Carnegie Mellon University @brief This subroutine can be called by a C/C++ program as a standalone routine to compute Monte Carlo data @details This subroutine provides a method to compute a Monte Carlo data set, normally computed with the EMMCOpenCL.f90 program. The routine can be called from an external C/C++ program; the routine provides a callback mechanism to update the calling program about computational progress, as well as a cancel option.
The routine is intended to be called from a C/C++ program, e.g., DREAM.3D. This routine is a simplified version of the core of the EMMCOpenCL program.
Since the HDF5 library with fortran90 support can only be a static library on Mac OS X, we must have the calling program read the .xtal HDF5 file and pass the necessary information on to this routine. This is a workaround until the HDF group fixes the static library issue; DREAM.3D requires a dynamical HDF5 library, so for DREAM.3D and EMsoft to properly work together, the callable routines in this file may not depend on any HDF code at all, either directly or indirectly.
@param ipar array with integer input parameters @param fpar array with float input parameters @param atdata atom coordinate array @param attypes atom type array @param latparm lattice parameter array @param accum_e output array with Monte Carlo energy histogram @param accum_z output array with Monte Carlo depth histogram @date 03/08/16 MDG 1.0 original @date 03/19/16 MDG 1.1 corrections to a few variable types @date 04/13/16 MDG 1.2 correction to accum_z array size due to changes in calling DREAM.3D filter @date 04/18/16 MDG 1.3 increased number of entries in ipar, fpar for compatibility with EMsoftCgetEBSDmaster routine @date 04/28/16 MDG 1.4 corrected error in indexing of init_seeds array; caused DREAM.3D to crash randomly
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int32_t), intent(in) :: ipar(nipar)
real(kind=sgl), intent(in) :: fpar(nfpar)
real(kind=sgl), intent(in) :: atompos(ipar(9),5)
integer(kind=irg), intent(in) :: atomtypes(ipar(9))
real(kind=sgl), intent(in) :: latparm(6)
integer(kind=irg), intent(out) :: accum_e(ipar(12),-ipar(1):ipar(1),-ipar(1):ipar(1))
integer(kind=irg), intent(out) :: accum_z(ipar(12),ipar(13),-ipar(16):ipar(16),-ipar(16):ipar(16))
type(C_FUNPTR), intent(in), VALUE :: cproc
integer(kind=c_size_t), intent(in), VALUE :: objAddress
character(len=1), intent(in) :: cancel
Calls
Source Code
EMsoftCgetMCOpenCL
Source Code
recursive subroutine EMsoftCgetMCOpenCL(ipar, fpar, atompos, atomtypes, latparm, accum_e, accum_z, cproc, objAddress, cancel) &
           bind(c, name='EMsoftCgetMCOpenCL')    ! this routine is callable from a C/C++ program
!DEC$ ATTRIBUTES DLLEXPORT :: EMsoftCgetMCOpenCL
! ipar components
! ipar(1) : integer(kind=irg)       :: nx  = (numsx-1)/2
! ipar(2) : integer(kind=irg)       :: globalworkgrpsz
! ipar(3) : integer(kind=irg)       :: num_el
! ipar(4) : integer(kind=irg)       :: totnum_el
! ipar(5) : integer(kind=irg)       :: multiplier
! ipar(6) : integer(kind=irg)       :: devid
! ipar(7) : integer(kind=irg)       :: platid
! ipar(8) : integer(kind=irg)       :: CrystalSystem
! ipar(9) : integer(kind=irg)       :: Natomtypes
! ipar(10): integer(kind=irg)       :: SpaceGroupNumber
! ipar(11): integer(kind=irg)       :: SpaceGroupSetting
! ipar(12): integer(kind=irg)       :: numEbins
! ipar(13): integer(kind=irg)       :: numzbins
! ipar(14): integer(kind=irg)       :: mcmode  (1 = 'full', 2 = 'bse1')
! ipar(15): integer(kind=irg)       :: numangle
! ipar(16): integer(kind=irg)       :: nxten = nx/10
! other entries are not used
! fpar components
! fpar(1) : real(kind=dbl)          :: sig
! fpar(2) : real(kind=dbl)          :: omega
! fpar(3) : real(kind=dbl)          :: EkeV
! fpar(4) : real(kind=dbl)          :: Ehistmin
! fpar(5) : real(kind=dbl)          :: Ebinsize
! fpar(6) : real(kind=dbl)          :: depthmax
! fpar(7) : real(kind=dbl)          :: depthstep
! fpar(8) : real(kind=dbl)          :: sigstart
! fpar(9) : real(kind=dbl)          :: sigend
! fpar(10): real(kind=dbl)          :: sigstep
! other entries are not used
use local
use constants
use crystal
use constants
use symmetry
use io
use typedefs
use clfortran
use CLsupport
use timing
use,INTRINSIC :: ISO_C_BINDING
IMPLICIT NONE
integer(c_int32_t),PARAMETER            :: nipar=40
integer(c_int32_t),PARAMETER            :: nfpar=40
integer(c_int32_t),INTENT(IN)           :: ipar(nipar)
real(kind=sgl),INTENT(IN)               :: fpar(nfpar)
real(kind=sgl),INTENT(IN)               :: atompos(ipar(9),5)
integer(kind=irg),INTENT(IN)            :: atomtypes(ipar(9))
real(kind=sgl),INTENT(IN)               :: latparm(6)
integer(kind=irg),INTENT(OUT)           :: accum_e(ipar(12),-ipar(1):ipar(1),-ipar(1):ipar(1))
integer(kind=irg),INTENT(OUT)           :: accum_z(ipar(12),ipar(13),-ipar(16):ipar(16),-ipar(16):ipar(16))
TYPE(C_FUNPTR), INTENT(IN), VALUE       :: cproc
integer(c_size_t),INTENT(IN), VALUE     :: objAddress
character(len=1),INTENT(IN)             :: cancel
! local variables and parameters
type(unitcell),pointer                  :: cell
character(4)                            :: mode
integer(kind=ill)                       :: i, j, k, io_int(1), num_max, totnum_el, ipg, isave, istat
integer(kind=irg)                       :: nx, numEbins, numzbins, numangle, iang, cn, dn, totn
integer(kind=irg),target                :: globalworkgrpsz, num_el, steps
integer(kind=8),target                  :: globalsize(2), localsize(2)
integer(kind=8)                         :: size_in_bytes,size_in_bytes_seeds
real(kind=sgl),target                   :: dens, avA, avZ, omega, EkeV, sig, bseyield, io_real(3)
real(kind=4),target                     :: density, Ze, at_wt, delta
real(kind=8),parameter                  :: dtoR = 0.01745329251D0  ! pi/180
real(kind=4),allocatable, target        :: Lamresx(:), Lamresy(:), depthres(:), energyres(:)
integer(kind=4),allocatable             :: rnseeds(:)
integer(kind=4),allocatable,target      :: init_seeds(:)
integer(kind=4)                         :: idxy(2), iE, px, py, iz, nseeds, hdferr, tstart ! auxiliary variables
real(kind=4)                            :: cxyz(3), edis, bse, xy(2), xs, ys, zs, sclf ! auxiliary variables
real(kind=8)                            :: rand
logical                                 :: f_exists
! OpenCL variables
integer(c_intptr_t),allocatable, target :: platform(:)
integer(c_intptr_t),allocatable, target :: device(:)
integer(c_intptr_t),target              :: context
integer(c_intptr_t),target              :: command_queue
integer(c_intptr_t),target              :: prog
integer(c_intptr_t),target              :: kernel
integer(c_intptr_t),target              :: LamX, LamY, LamZ, depth, energy, seeds
type(c_ptr)                             :: event
integer(c_int32_t)                      :: ierr, pcnt
integer(c_size_t),target                :: slength
integer(c_intptr_t),target              :: ctx_props(3)
character(2),target                     :: kernelname
character(19),target                    :: progoptions
character(fnlen),target                 :: info ! info about the GPU
integer(c_int64_t)                      :: cmd_queue_props
integer, parameter                      :: iunit = 10
integer, parameter                      :: source_length = 50000
character(len=source_length),target     :: source
character(len=source_length, KIND=c_char),TARGET :: csource
type(c_ptr), target                     :: psource
integer(c_int)                          :: nump, numd, irec, val,val1 ! auxiliary variables
integer(c_size_t)                       :: cnum, cnuminfo
character(fnlen)                        :: instring, dataname, fname, sourcefile
PROCEDURE(ProgressCallBack2), POINTER   :: proc
! link the proc procedure to the cproc argument
CALL C_F_PROCPOINTER (cproc, proc)
! since this routine needs to read a .cl file, we need to make sure that the pathnames are
! properly set...
call EMsoft_path_init
! the following is necessitated by the fact that none of this code may
! depend on HDF5 routines, so we need to cut-and-paste from various
! other library routines to set things up so that we can compute the
! density, and the average atomic number and atomic mass...
! copy all the unit cell parameters into the proper fields and compute the
! density parameters needed by the Monte Carlo routine; then discard the cell structure
nullify(cell)
allocate(cell)
! lattice parameters
cell%a = dble(latparm(1))
cell%b = dble(latparm(2))
cell%c = dble(latparm(3))
cell%alpha = dble(latparm(4))
cell%beta = dble(latparm(5))
cell%gamma = dble(latparm(6))
! symmetry parameters
cell%xtal_system = ipar(8)
cell%SYM_SGset = ipar(11)
cell%SYM_SGnum = ipar(10)
if ((cell%SYM_SGnum.ge.143).and.(cell%SYM_SGnum.le.167)) then
  cell%SG%SYM_trigonal = .TRUE.
else
  cell%SG%SYM_trigonal = .FALSE.
end if
! atom type and coordinate parameters
cell%ATOM_ntype = ipar(9)
cell%ATOM_type(1:cell%ATOM_ntype) = atomtypes(1:cell%ATOM_ntype)
cell%ATOM_pos(1:cell%ATOM_ntype,1:5) = atompos(1:cell%ATOM_ntype,1:5)
! generate the symmetry operations
cell%hexset = .FALSE.
if (cell%xtal_system.eq.4) cell%hexset = .TRUE.
if ((cell%xtal_system.eq.5).AND.(cell%SYM_SGset.ne.2)) cell%hexset = .TRUE.
! compute the metric matrices
 call CalcMatrices(cell)
! First generate the point symmetry matrices, then the actual space group.
! Get the symmorphic space group corresponding to the point group
! of the actual space group
 ipg=0
 do i=1,32
  if (SGPG(i).le.cell%SYM_SGnum) ipg=i
 end do
! if the actual group is also the symmorphic group, then both
! steps can be done simultaneously, otherwise two calls to
! GenerateSymmetry are needed.
 if (SGPG(ipg).eq.cell%SYM_SGnum) then
  call GenerateSymmetry(cell,.TRUE.)
 else
  isave = cell%SYM_SGnum
  cell%SYM_SGnum = SGPG(ipg)
  call GenerateSymmetry(cell,.TRUE.)
  cell%SYM_SGnum = isave
  call GenerateSymmetry(cell,.FALSE.)
 end if
! next we get all the atom positions
call CalcPositions(cell,'v')
! and now we have all we need to compute the density, average A and average Z
call CalcDensity(cell, dens, avZ, avA)
! deallocate the cell structure
deallocate(cell)
! and copy these values into the desired variables
density = dble(dens)
Ze = dble(avZ)
at_wt = dble(avA)
! define a number of parameters
steps = 300
mode = 'full'
if (ipar(14).ne.1) mode = 'bse1'
EkeV = sngl(fpar(3))
!sig = mcnl%sig*dtoR    ! this is defined later on and depends on the mode
omega = sngl(fpar(2))*dtoR
globalworkgrpsz = ipar(2)
num_el = int(ipar(3))  ! no. of electron simulation by one work item
num_max = globalworkgrpsz*globalworkgrpsz*num_el ! total simulation in one loop
totnum_el = ipar(4) * ipar(5) ! total number of electrons to simulate
globalsize = (/ globalworkgrpsz, globalworkgrpsz /)
!localsize = (/ globalworkgrpsz, globalworkgrpsz /)
!localsize = (/ globalworkgrpsz/10, globalworkgrpsz/10 /)
numEbins =  int(ipar(12))
numzbins =  int(ipar(13))
nx = int(ipar(1))
delta = dble(nx)
size_in_bytes = num_max*sizeof(EkeV)
size_in_bytes_seeds = 4*globalworkgrpsz*globalworkgrpsz*sizeof(EkeV)
numangle = int(ipar(15))
! next allocate and initialize a couple of arrays
allocate(Lamresx(num_max), Lamresy(num_max), depthres(num_max), energyres(num_max), stat=istat)
depthres = 0.0
energyres = 0.0
Lamresx = 0.0
Lamresy = 0.0
accum_e = 0
accum_z = 0
!======================
! OpenCL INITIALIZATION
!======================
call CLinit_PDCCQ(platform, nump, int(ipar(7)), device, numd, int(ipar(6)), info, context, command_queue)
!=====================
! BUILD THE KERNEL
!=====================
! read the source file
sourcefile = 'EMMC.cl'
call CLread_source_file(sourcefile, csource, slength)
! we disable all screen output; perhaps we can feed error messages back to the calling program...
! create the program
pcnt = 1
psource = C_LOC(csource)
prog = clCreateProgramWithSource(context, pcnt, C_LOC(psource), C_LOC(slength), ierr)
! if(ierr /= CL_SUCCESS) call FatalError("clCreateProgramWithSource: ",'Error: cannot create program from source.')
! build the program
progoptions = '-cl-no-signed-zeros'
ierr = clBuildProgram(prog, numd, C_LOC(device), C_LOC(progoptions), C_NULL_FUNPTR, C_NULL_PTR)
! if(ierr /= CL_SUCCESS) call FatalError("clBuildProgram: ",'Error: cannot build program.')
! get the compilation log
ierr = clGetProgramBuildInfo(prog, device(ipar(6)), CL_PROGRAM_BUILD_LOG, sizeof(source), C_LOC(source), cnum)
! if(len(trim(source)) > 0) call Message(trim(source(1:cnum)),frm='(A)')
! if(ierr /= CL_SUCCESS) call FatalError("clGetProgramBuildInfo: ",'Error building program.')
! if we get here, then the program build was successful and we can proceed with the creation of the kernel
! call Message('Program Build Successful... Creating kernel')
! finally get the kernel and release the program
kernelname = 'MC'
kernel = clCreateKernel(prog, C_LOC(kernelname), ierr)
! if(ierr /= CL_SUCCESS) call FatalError("clCreateKernel: ",'Error creating kernel MC.')
ierr = clReleaseProgram(prog)
! if(ierr /= CL_SUCCESS) call FatalError("clReleaseProgram: ",'Error releasing program.')
open(unit = iunit, file = trim(EMsoft_toNativePath(EMsoft_getRandomseedfilename())), form='unformatted', status='old')
read(iunit) nseeds
allocate(rnseeds(nseeds))
read(iunit) rnseeds
close(unit=iunit,status='keep')
! the next error needs to be checked in the calling program
! if (globalworkgrpsz**2 .gt. nseeds) call FatalError('EMMCOpenCL:','insufficient prime numbers')
allocate(init_seeds(4*globalworkgrpsz*globalworkgrpsz),stat=istat)
init_seeds = 0
do i = 1,globalworkgrpsz
    do j = 1,globalworkgrpsz
        do k = 1,4
            init_seeds(4*((i-1)*globalworkgrpsz+(j-1))+k) = rnseeds(4*((i-1)*globalworkgrpsz+j)+k)
        end do
    end do
end do
! create device memory buffers
LamX = clCreateBuffer(context, CL_MEM_WRITE_ONLY, size_in_bytes, C_NULL_PTR, ierr)
! if(ierr /= CL_SUCCESS) call FatalError('clCreateBuffer: ','cannot allocate device memory for LamX.')
LamY = clCreateBuffer(context, CL_MEM_WRITE_ONLY, size_in_bytes, C_NULL_PTR, ierr)
! if(ierr /= CL_SUCCESS) call FatalError('clCreateBuffer: ','cannot allocate device memory for LamY.')
depth = clCreateBuffer(context, CL_MEM_WRITE_ONLY, size_in_bytes, C_NULL_PTR, ierr)
!   if(ierr /= CL_SUCCESS) call FatalError('clCreateBuffer: ','cannot allocate device memory for depth.')
energy = clCreateBuffer(context, CL_MEM_WRITE_ONLY, size_in_bytes, C_NULL_PTR, ierr)
!   if(ierr /= CL_SUCCESS) call FatalError('clCreateBuffer: ','cannot allocate device memory for energy.')
seeds = clCreateBuffer(context, CL_MEM_READ_WRITE, size_in_bytes, C_NULL_PTR, ierr)
! if(ierr /= CL_SUCCESS) call FatalError('clCreateBuffer: ','cannot allocate device memory for seeds.')
ierr = clEnqueueWriteBuffer(command_queue, seeds, CL_TRUE, 0_8, size_in_bytes_seeds, C_LOC(init_seeds(1)), &
                            0, C_NULL_PTR, C_NULL_PTR)
! if(ierr /= CL_SUCCESS) call FatalError('clEnqueueWriteBuffer: ','cannot Enqueue write buffer.')
! set the callback parameters
dn = 1
cn = dn
totn = numangle * (totnum_el/num_max+1)
call Time_tick(tstart)
! loop over angles (used for BSE1, single run for full)
angleloop: do iang = 1,numangle
  if (mode .eq. 'bse1') then
    sig = (fpar(8) + (iang-1)*fpar(10))*dtoR
  else
    sig = fpar(1)*dtoR
  end if
  mainloop: do i = 1,(totnum_el/num_max+1)
! set the kernel arguments
    ierr = clSetKernelArg(kernel, 0, sizeof(LamX), C_LOC(LamX))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 1, sizeof(LamY), C_LOC(LamY))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 2, sizeof(EkeV), C_LOC(EkeV))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 3, sizeof(globalworkgrpsz), C_LOC(globalworkgrpsz))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 4, sizeof(Ze), C_LOC(Ze))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 5, sizeof(density), C_LOC(density))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 6, sizeof(at_wt), C_LOC(at_wt))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 7, sizeof(num_el), C_LOC(num_el))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 8, sizeof(seeds), C_LOC(seeds))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 9, sizeof(sig), C_LOC(sig))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 10, sizeof(omega), C_LOC(omega))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 11, sizeof(depth), C_LOC(depth))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 12, sizeof(energy), C_LOC(energy))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
    ierr = clSetKernelArg(kernel, 13, sizeof(steps), C_LOC(steps))
    !   if(ierr /= CL_SUCCESS) stop 'Error: cannot set kernel argument.'
! execute the kernel
!   ierr = clEnqueueNDRangeKernel(command_queue, kernel, 2, C_NULL_PTR, C_LOC(globalsize), C_LOC(localsize), &
!                                 0, C_NULL_PTR, C_NULL_PTR)
    ierr = clEnqueueNDRangeKernel(command_queue, kernel, 2, C_NULL_PTR, C_LOC(globalsize), C_NULL_PTR, &
                                  0, C_NULL_PTR, C_NULL_PTR)
! wait for the commands to finish
    ierr = clFinish(command_queue)
! read the resulting vector from device memory
    ierr = clEnqueueReadBuffer(command_queue,LamX,CL_TRUE,0_8,size_in_bytes,C_LOC(Lamresx(1)),0,C_NULL_PTR,C_NULL_PTR)
    ierr = clEnqueueReadBuffer(command_queue,LamY,CL_TRUE,0_8,size_in_bytes,C_LOC(Lamresy(1)),0,C_NULL_PTR,C_NULL_PTR)
    ierr = clEnqueueReadBuffer(command_queue,depth,CL_TRUE,0_8,size_in_bytes,C_LOC(depthres(1)),0,C_NULL_PTR,C_NULL_PTR)
    ierr = clEnqueueReadBuffer(command_queue,energy,CL_TRUE,0_8,size_in_bytes,C_LOC(energyres(1)),0,C_NULL_PTR,C_NULL_PTR)
    if (mode .eq. 'full') then
      subloopfull: do j = 1, num_max
        if ((Lamresx(j) .ne. -10.0) .and. (Lamresy(j) .ne. -10.0) &
          .and. (depthres(j) .ne. 10.0) .and. (energyres(j) .ne. 0.0) &
          .and. .not.isnan(Lamresx(j)) .and. .not.isnan(Lamresy(j))) then
! and get the nearest pixel [ take into account reversal of coordinate frame (x,y) -> (y,-x) ]
             if ((nint(delta*Lamresy(j)) .eq. 0.0) .and. (nint(-delta*Lamresx(j)) .eq. 0.0)) then
               val1 = val1 + 1
             end if
             val = val + 1
             idxy = (/ nint(delta*Lamresy(j)), nint(-delta*Lamresx(j)) /)
             if (maxval(abs(idxy)).le.nx) then
! If Ec larger than Emin, then we should count this electron
               if (energyres(j).gt.fpar(4)) then
                 iE = nint((energyres(j)-fpar(4))/fpar(5))+1
! first add this electron to the correct exit distance vs. energy bin (coarser than the angular plot)
                 edis = abs(depthres(j))  ! distance from last scattering point to surface along trajectory
                 iz = nint(edis/fpar(7)) +1
                 if ( (iz.gt.0).and.(iz.le.ipar(13)) ) then
                   px = nint(idxy(1)/10.0)
                   py = nint(idxy(2)/10.0)
                   accum_z(iE,iz,px,py) = accum_z(iE,iz,px,py) + 1
                 end if
! then add it to the modified Lambert accumulator array.
                 accum_e(iE,idxy(1),idxy(2)) = accum_e(iE,idxy(1),idxy(2)) + 1
               end if
             end if
        end if
      end do subloopfull
    end if
    if (mode .eq. 'bse1') then
      subloopbse1: do j = 1, num_max
        if ((Lamresx(j) .ne. -10.0) .and. (Lamresy(j) .ne. -10.0) &
          .and. (depthres(j) .ne. 10.0) .and. (energyres(j) .ne. 0.0) &
          .and. .not.isnan(Lamresx(j)) .and. .not.isnan(Lamresy(j))) then
! and get the nearest pixel [ take into account reversal of coordinate frame (x,y) -> (y,-x) ]
          if ((nint(delta*Lamresy(j)) .eq. 0.0) .and. (nint(-delta*Lamresx(j)) .eq. 0.0)) then
            val1 = val1 + 1
          end if
          val = val + 1
          idxy = (/ nint(delta*Lamresy(j)), nint(-delta*Lamresx(j)) /)
          if (maxval(abs(idxy)).le.nx) then
! first add this electron to the correct exit distance vs. sigma (coarser than the angular plot)
            edis = abs(depthres(j))  ! distance from last scattering point to surface along trajectory
            iz = nint(edis/fpar(7)) +1
            if ( (iz.gt.0).and.(iz.le.ipar(13)) ) then
              px = nint(idxy(1)/10.0)
              py = nint(idxy(2)/10.0)
              accum_z(iang,iz,px,py) = accum_z(iang,iz,px,py) + 1
            end if
! then add it to the modified Lambert accumulator array.
            accum_e(iang,idxy(1),idxy(2)) = accum_e(iang,idxy(1),idxy(2)) + 1
          end if
        end if
      end do subloopbse1
    end if
! has the cancel flag been set by the calling program ?
  if(cancel.ne.char(0)) EXIT angleloop
! update the progress counter and report it to the calling program via the proc callback routine
  if(objAddress.ne.0) then
    cn = cn+dn
    bseyield = 100.0*float(sum(accum_e))/float(i*num_max)
    write(*,*)cn, totn, bseyield
    call proc(objAddress, cn, totn, bseyield)
  end if
  end do mainloop
end do angleloop
write(*,*)'Total GPU time [s] = ',Time_tock(tstart)
!=====================
! RELEASE EVERYTHING
!=====================
ierr = clReleaseKernel(kernel)
ierr = clReleaseCommandQueue(command_queue)
ierr = clReleaseContext(context)
ierr = clReleaseMemObject(LamX)
ierr = clReleaseMemObject(LamY)
ierr = clReleaseMemObject(depth)
ierr = clReleaseMemObject(energy)
ierr = clReleaseMemObject(seeds)
end subroutine EMsoftCgetMCOpenCL
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
emsoftcgetmcopencl calls emsoft_path_init, calcmatrices, calcpositions, generatesymmetry, calcdensity, clcreateprogramwithsource, clreleasecontext, clinit_pdccq, clbuildprogram, clgetprogrambuildinfo, clcreatekernel, sngl, emsoft_tonativepath, clreleasememobject, clreleaseprogram, emsoft_getrandomseedfilename, sgpg, clcreatebuffer, float, clenqueuewritebuffer, clreleasekernel, time_tick, clsetkernelarg, clread_source_file, clenqueuendrangekernel, clfinish, clreleasecommandqueue, clenqueuereadbuffer, time_tock
clinit_pdccq calls clgetdeviceinfo, fatalerror, clgetplatformids, clcreatecontext, clcreatecommandqueue, writevalue, clgetdeviceids, clerror_check
clread_source_file calls emsoft_tonativepath, fatalerror, emsoft_getopenclpathname, emsoft_getemdevelop
clerror_check calls fatalerror, writevalue