getEBSDPatterns – Fortran Program
getEBSDPatterns Subroutine
165 statements
Source File
public recursive subroutine getEBSDPatterns(ipar, fpar, EBSDpattern, quats, accum_e, mLPNH, mLPSH)
Uses:
local
constants
Lambert
quaternions
iso_c_binding
@author Marc De Graef, Carnegie Mellon University @brief This function can be called as a standalone function to compute an EBSD pattern @etails The main purpose of this routine and its accompanying wrapper routine is to provide a way for an external program to compute a channeling pattern. The idea is that all the necessary arrays and variables are passed in by reference as arguments, without the need for the routine to fetch any other data from files etc... The initial goal is to have a function that can be called with the CALL_EXTERNAL mechanism in IDL or MatLab. This routine should be called via the getEBSDPatternsWrapper routine! For calls from a C/C++ program, use the EMsoftCgetEBSDPatterns routine instead. @param ipar array with integer input parameters @param fpar array with float input parameters @param EBSDpattern output array @param quats quaternion input array @param accum_e array with Monte Carlo histogram @param mLPNH Northern hemisphere master pattern @param mLPSH Southern hemisphere master pattern @date 10/16/15 MDG 1.0 original @date 11/02/15 MDG 1.1 simplification of the input variables @date 11/04/15 MDG 1.2 added array of quaternions as input parameter; used complete mLPNH/SH arrays with local sum @date 01/12/15 MDG 1.3 added arguments and functionality for interface with DREAM.3D and other calling programs @date 01/13/15 MDG 1.4 after split with EMsoftCgetEBSDPatterns subroutine, removed DREAM.3D interfacing stuff @date 07/10/16 MDG 1.5 added energy min/max parameters @date 08/03/16 MDG 1.6 corrected normalizing issue in rgx,y,z arrays that causes NANs to be returned from Lambert projection routines @date 08/R2516 MDG 1.7 added transfer optics barrel distortion to rgx,y,z arrays.
Arguments
Type Intent Optional Attributes Name
integer(kind=c_size_t), intent(in) :: ipar(nipar)
real(kind=sgl), intent(in) :: fpar(nfpar)
real(kind=sgl), intent(out) :: EBSDpattern(ipar(2),ipar(3),ipar(8))
real(kind=sgl), intent(in) :: quats(nq,ipar(8))
real(kind=sgl), intent(in) :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
real(kind=sgl), intent(in) :: mLPNH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(4),ipar(7))
real(kind=sgl), intent(in) :: mLPSH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(4),ipar(7))
Calls
Called By
Source Code
getEBSDPatterns
Source Code
recursive subroutine getEBSDPatterns(ipar, fpar, EBSDpattern, quats, accum_e, mLPNH, mLPSH)
!DEC$ ATTRIBUTES DLLEXPORT :: getEBSDPatterns
! the input parameters are all part of a ipar and fpar input arrays instead of the usual namelist structure to
! make this routine callable by external programs; for calls from  C/C++, use the EsoftCgetEBSDPatterns routine instead.
! The following is the mapping for the ipar and fpar arrays:
!
! ipar(1) = 2 if rgx, rgy, rgz detector arrays need to be computed, 1 if not (arrays will have save status)
! ipar(2) = detnumsx
! ipar(3) = detnumsy
! ipar(4) = detnumEbins
! ipar(5) = mcnsx
! ipar(6) = mpnpx
! ipar(7) = numset
! ipar(8) = numquats
! ipar(9) = Eminsel
! ipar(10) = Emaxsel
! fpar(1) = enl%xpc
! fpar(2) = enl%ypc
! fpar(3) = enl%delta
! fpar(4) = enl%MCsig
! fpar(5) = enl%omega
! fpar(6) = enl%thetac
! fpar(7) = enl%L
! fpar(8) = enl%beamcurrent
! fpar(9) = enl%dwelltime
! fpar(10) = enl%alphaBD
use local
use constants
use Lambert
use quaternions
use,INTRINSIC :: ISO_C_BINDING
IMPLICIT NONE
integer(c_size_t),PARAMETER             :: nipar=10
integer(c_size_t),PARAMETER             :: nfpar=10
integer(c_size_t),PARAMETER             :: nq=4
integer(c_size_t),INTENT(IN)            :: ipar(nipar)
real(kind=sgl),INTENT(IN)               :: fpar(nfpar)
real(kind=sgl),INTENT(IN)               :: quats(nq,ipar(8))
real(kind=sgl),INTENT(IN)               :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
real(kind=sgl),INTENT(IN)               :: mLPNH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(4), ipar(7))
real(kind=sgl),INTENT(IN)               :: mLPSH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(4), ipar(7))
real(kind=sgl),INTENT(OUT)              :: EBSDpattern(ipar(2),ipar(3),ipar(8))
! variables that must potentially be saved for the next time this function is called
real(kind=sgl),allocatable,save         :: accum_e_detector(:,:,:)
real(kind=sgl),allocatable,save         :: rgx(:,:), rgy(:,:), rgz(:,:)
real(kind=sgl),allocatable,save         :: mLPNHsum(:,:,:), mLPSHsum(:,:,:)
real(kind=sgl),save                     :: prefactor
! other variables
real(kind=sgl),allocatable              :: scin_x(:), scin_y(:)                 ! scintillator coordinate arrays [microns]
real(kind=sgl),parameter                :: dtor = 0.0174533  ! convert from degrees to radians
real(kind=sgl)                          :: alp, ca, sa, cw, sw
real(kind=sgl)                          :: L2, Ls, Lc, pcxd, pcyd, xx, yy     ! distances
integer(kind=irg)                       :: nix, niy, binx, biny,  nixp, niyp, i, j, Emin, Emax, istat, k, ip, ipx, ipy ! various parameters
real(kind=sgl)                          :: dc(3), scl, alpha, theta, gam, pcvec(3), dp, calpha           ! direction cosine array
real(kind=sgl)                          :: sx, dx, dxm, dy, dym, rhos, x, bindx         ! various parameters
real(kind=sgl)                          :: ixy(2)
real(kind=dbl),parameter                :: nAmpere = 6.241D+18
!====================================
! ------ generate the detector rgx, rgy, rgz arrays if needed (calling program must decide this via ipar(1))
!====================================
if (ipar(1).ge.1) then
 if ((ipar(1).eq.2).or.(.not.allocated(mLPNHsum))) then ! complete reset, including the mLPNHsum and mLPSHsum arrays
    if (allocated(mLPNHsum)) deallocate(mLPNHsum)
    if (allocated(mLPSHsum)) deallocate(mLPSHsum)
    allocate(mLPNHsum(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(4)))
    allocate(mLPSHsum(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(4)))
    mLPNHsum = sum(mLPNH,4)
    mLPSHsum = sum(mLPSH,4)
 end if
! This needs to be done only once for a given detector geometry (i.e., when ipar(1)=1 or larger)
  allocate(scin_x(ipar(2)),scin_y(ipar(3)),stat=istat)
  pcxd = fpar(1) * fpar(3)
  pcyd = fpar(2) * fpar(3)
  scin_x = - ( fpar(1) - ( 1.0 - float(ipar(2)) ) * 0.5 - (/ (i-1, i=1,ipar(2)) /) ) * fpar(3)
  scin_y = ( fpar(2) - ( 1.0 - float(ipar(3)) ) * 0.5 - (/ (i-1, i=1,ipar(3)) /) ) * fpar(3)
! auxiliary angle to rotate between reference frames
  alp = 0.5 * cPi - (fpar(4) - fpar(6)) * dtor
  ca = cos(alp)
  sa = sin(alp)
  cw = cos(fpar(5) * dtor)
  sw = sin(fpar(5) * dtor)
! compute auxilliary interpolation arrays
  if (allocated(rgx)) deallocate(rgx, rgy, rgz)
  allocate(rgx(ipar(2),ipar(3)), rgy(ipar(2),ipar(3)), rgz(ipar(2),ipar(3)))
! do we need to perform a Barrel Distortion?
! we will do this here by expanding/contracting the radial component of the
! (rgx, rgy) to (rgx,rgy) * (1+alphaBD * (rgx^2+rgy^2))
! in other words, we pre-distort the sampling grid with the barrel distortion.
  L2 = fpar(7) * fpar(7)
  do j=1,ipar(2)
    Ls = -sw * scin_x(j) + fpar(7) * cw
    Lc = cw * scin_x(j) + fpar(7) * sw
    do i=1,ipar(3)
!    rhos = 1.0/sqrt(sx + scin_y(i)**2)
     rgx(j,i) = (scin_y(i) * ca + sa * Ls) ! * rhos
     rgy(j,i) = Lc ! * rhos
     rgz(j,i) = (-sa * scin_y(i) + ca * Ls) ! * rhos
! apply Barrel Distortion ?
     if (fpar(10).ne.0.0) then
! shift the components to the detector center coordinate frame
       xx = rgx(j,i)-pcyd
       yy = rgy(j,i)+pcxd
! compute the distortion amount; the factor of 10^(-10) is inserted here...
       sx = 1.0 + 1.E-10 * fpar(10) * (xx**2+yy**2)
! and shift them back to the pattern center reference frame
       rgx(j,i) = xx*sx+pcyd
       rgy(j,i) = yy*sx-pcxd
     end if
! make sure that these vectors are normalized !
     x = sqrt(rgx(j,i)**2+rgy(j,i)**2+rgz(j,i)**2)
     rgx(j,i) = rgx(j,i) / x
     rgy(j,i) = rgy(j,i) / x
     rgz(j,i) = rgz(j,i) / x
    end do
  end do
! test dump of rgx/y/z arrays to check for proper inclusion of barrel distortion:
!open(unit=dataunit,file='rgxyz.data',status='unknown',form='unformatted')
!write(dataunit) rgx
!write(dataunit) rgy
!write(dataunit) rgz
!close(unit=dataunit,status='keep')
! remove the auxiliary arrays scin_x and scin_y
  deallocate(scin_x, scin_y)
!====================================
! ------ create the equivalent detector energy array
!====================================
! from the Monte Carlo energy data, we need to extract the relevant
! entries for the detector geometry defined above.
! determine the scale factor for the Lambert interpolation; the square has
! an edge length of 2 x sqrt(pi/2)
  scl = float(ipar(5))
! energy summation will go over all energy bins
  Emin = ipar(9)
  Emax = ipar(10)
  if (allocated(accum_e_detector)) deallocate(accum_e_detector)
  allocate(accum_e_detector(ipar(4),ipar(2),ipar(3)))
! correction of change in effective pixel area compared to equal-area Lambert projection
  alpha = atan(fpar(3)/fpar(7)/sqrt(sngl(cPi)))
  ipx = ipar(2)/2 + nint(fpar(1))
  ipy = ipar(3)/2 + nint(fpar(2))
  if ((abs(ipy).gt.ipar(3)).or.(abs(ipx).gt.ipar(2))) then
    pcvec = (/pcyd*ca + pcxd*sa*sw + fpar(7)*cw*sa, &
             fpar(7)*sw - pcxd*cw,&
             fpar(7)*ca*cw + pcxd*ca*sw - pcyd*sa/)
    pcvec = pcvec/NORM2(pcvec)
  else
    pcvec = (/ rgx(ipx,ipy), rgy(ipx,ipy), rgz(ipx,ipy) /)
  end if
  calpha = cos(alpha)
  do i=1,ipar(2)
    do j=1,ipar(3)
! do the coordinate transformation for this detector pixel
       dc = (/ rgx(i,j), rgy(i,j), rgz(i,j) /)
! make sure the third one is positive; if not, switch all
       if (dc(3).lt.0.0) dc = -dc
! convert these direction cosines to coordinates in the Rosca-Lambert projection
        ixy = scl * LambertSphereToSquare( dc, istat )
        x = ixy(1)
        ixy(1) = ixy(2)
        ixy(2) = -x
! four-point interpolation (bi-quadratic)
        nix = int(ipar(5)+ixy(1))-ipar(5)
        niy = int(ipar(5)+ixy(2))-ipar(5)
        nixp = nix+1
        niyp = niy+1
        if (nix .gt. ipar(5)) nix = ipar(5)
        if (niy .gt. ipar(5)) niy = ipar(5)
        if (nix .lt. -ipar(5)) nix = -ipar(5)
        if (niy .lt. -ipar(5)) niy = -ipar(5)
        if (nixp .gt. ipar(5)) nixp = ipar(5)
        if (niyp .gt. ipar(5)) niyp = ipar(5)
        if (nixp .lt. -ipar(5)) nixp = -ipar(5)
        if (niyp .lt. -ipar(5)) niyp = -ipar(5)
        dx = ixy(1)-nix
        dy = ixy(2)-niy
        dxm = 1.0-dx
        dym = 1.0-dy
! do the area correction for this detector pixel
        dp = dot_product(pcvec,dc)
        if ((i.eq.ipx).and.(j.eq.ipy)) then
          gam = 0.25
        else
          gam = ((calpha*calpha + dp*dp - 1.0)**1.5)/(calpha**3) * 0.25
        end if
! interpolate the intensity
        do k= Emin, Emax
          accum_e_detector(k,i,j) = gam * (accum_e(k,nix,niy) * dxm * dym + &
                                    accum_e(k,nixp,niy) * dx * dym + &
                                    accum_e(k,nix,niyp) * dxm * dy + &
                                    accum_e(k,nixp,niyp) * dx * dy)
        end do
    end do
  end do
  prefactor = 0.25D0 * nAmpere * fpar(8) * fpar(9)  * 1.0D-15 / sum(accum_e_detector)
end if   ! end of ipar(1)=1 test
!open(unit=dataunit,file='TKDdetectorarray_dymod.data',status='unknown',form='unformatted')
!write(dataunit) accum_e_detector
!close(unit=dataunit,status='keep')
! from here on, we simply compute the EBSD patterns by interpolation, using the saved arrays from above
! no intensity scaling or anything else...other than multiplication by pre-factor
! intensity scaling is left to the user of the calling program.
! define some parameters and initialize EBSDpattern
scl = dble(ipar(6))
EBSDpattern = 0.0
! here is the main loop over all quaternions
quatloop: do ip=1,ipar(8)
  do i=1,ipar(2)
    do j=1,ipar(3)
! do the active coordinate transformation for this euler angle
      dc = quat_Lp(quats(1:4,ip),  (/ rgx(i,j), rgy(i,j), rgz(i,j) /) )
! normalize dc
      dc = dc/sqrt(sum(dc*dc))
! convert these direction cosines to coordinates in the Rosca-Lambert projection (always square projection !!!)
      ixy = scl * LambertSphereToSquare( dc, istat )
      if (istat.eq.0) then
! four-point interpolation (bi-quadratic)
        nix = int(ipar(6)+ixy(1))-ipar(6)
        niy = int(ipar(6)+ixy(2))-ipar(6)
        nixp = nix+1
        niyp = niy+1
        if (nix .gt. ipar(6)) nix = ipar(6)
        if (niy .gt. ipar(6)) niy = ipar(6)
        if (nix .lt. -ipar(6)) nix = -ipar(6)
        if (niy .lt. -ipar(6)) niy = -ipar(6)
        if (nixp .gt. ipar(6)) nixp = ipar(6)
        if (niyp .gt. ipar(6)) niyp = ipar(6)
        if (nixp .lt. -ipar(6)) nixp = -ipar(6)
        if (niyp .lt. -ipar(6)) niyp = -ipar(6)
        dx = ixy(1)-nix
        dy = ixy(2)-niy
        dxm = 1.0-dx
        dym = 1.0-dy
        if (dc(3).gt.0.0) then ! we're in the Northern hemisphere
          do k=Emin,Emax
            EBSDpattern(i,j,ip) = EBSDpattern(i,j,ip) + accum_e_detector(k,i,j) * ( mLPNHsum(nix,niy,k) * dxm * dym +&
                                        mLPNHsum(nixp,niy,k) * dx * dym + mLPNHsum(nix,niyp,k) * dxm * dy + &
                                        mLPNHsum(nixp,niyp,k) * dx * dy )
          end do
        else                   ! we're in the Southern hemisphere
          do k=Emin,Emax
            EBSDpattern(i,j,ip) = EBSDpattern(i,j,ip) + accum_e_detector(k,i,j) * ( mLPSHsum(nix,niy,k) * dxm * dym +&
                                        mLPSHsum(nixp,niy,k) * dx * dym + mLPSHsum(nix,niyp,k) * dxm * dy + &
                                        mLPSHsum(nixp,niyp,k) * dx * dy )
          end do
        end if
      end if
    end do
  end do
end do quatloop
! finally, scale the patterns by the appropriate factor and return to the calling program
EBSDpattern = prefactor * EBSDpattern
end subroutine getEBSDPatterns
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
getebsdpatterns calls float, quat_lp, lambertspheretosquare, sngl
ebsd4calfun calls getebsdpatterns
getebsdpatternswrapper calls getebsdpatterns
ebsdcalfun calls getebsdpatterns