initialize_foil_geometry – Fortran Program
initialize_foil_geometry Subroutine
117 statements
Source File
public recursive subroutine initialize_foil_geometry(cell, foil, dinfo)
Uses:
local
typedefs
math
constants
crystal
symmetry
io
rotations
@author Marc De Graef, Carnegie Mellon University @brief Initializes the foil geometry @details This new implementation uses quaternions for all rotations. @param cell unit cell pointer @param dinfo @date 1/ 5/99 MDG 1.0 original @date 1/11/10 MDG 2.0 rewrite of beam direction part @date 3/28/11 MDG 2.1 code verified @date 4/23/11 MDG 2.2 redefined origin to be at center of image @date 6/03/13 MDG 3.0 replaced rotation matrices by quaternions throughout @date 10/30/13 MDG 3.1 complete debug of quaternion and rotation implementation @date 06/09/14 MDG 4.0 added cell and foil as argument
Arguments
Type Intent Optional Attributes Name
type(unitcell), pointer :: cell
type(foiltype), intent(inout) :: foil
integer(kind=sgl), intent(in) :: dinfo
Calls
Called By
Source Code
initialize_foil_geometry
Source Code
recursive subroutine initialize_foil_geometry(cell,foil,dinfo)
!DEC$ ATTRIBUTES DLLEXPORT :: initialize_foil_geometry
use local
use typedefs
use math
use constants
use crystal
use symmetry
use io
use rotations
IMPLICIT NONE
type(unitcell),pointer          :: cell
type(foiltype),INTENT(INOUT)    :: foil
integer(kind=sgl),INTENT(IN)    :: dinfo
real(kind=dbl)                  :: ey(3), ex(3), tt, dx, dy
real(kind=sgl)                  :: io_real(3)
real(kind=dbl)                  :: cp,sp,cs,ss,cr,sr, ca, sa, a_fc(3,3)
integer(kind=irg)               :: i,j
type(orientationtyped)          :: ot
character(10)                   :: pret
! determine the foil-to-microscope transformations [verified on 4/23/11, converted to quaternions on 6/4/13,
! verified 10/30/13, and again on 11/11/13 after some changes elsewhere]
  if (foil%alR.eq.0.D0) then
! the double tilt holder transformation a_fm; note quaternions, hence we need the half-angles !
! a_fm transforms a vector v FROM the microscope reference frame To the foil reference frame
! using the quat_rotate_vector routine.
    cp = dcos(foil%alP*0.5D0)
    sp = dsin(foil%alP*0.5D0)
    ca = dcos(foil%alP)
    sa = dsin(foil%alP)
    cs = dcos(foil%alS*0.5D0)
    ss = dsin(foil%alS*0.5D0)
    foil%a_fm = conjg( quat_mult( (/ cs, 0.D0, ss*ca, ss*sa /), (/ cp, sp, 0.D0, 0.D0 /) ) )
  else
! the rotation tilt holder transformation a_fm [verified on 4/23/11, converted to quaternions on 6/4/13,
! and again on 11/11/13 after changes elsewhere]
    cp = dcos(foil%alP*0.5D0)
    sp = dsin(foil%alP*0.5D0)
    cr = dcos(foil%alR*0.5D0)
    sr = dsin(foil%alR*0.5D0)
    ca = dcos(foil%alP)
    sa = dsin(foil%alP)
    foil%a_fm = conjg( quat_mult( (/ cr,0.D0, -sr*sa, sr*ca /), (/ cp, sp,0.D0,0.D0  /) ) )
  end if
  if (dinfo.eq.1) then
    pret = 'a_fm: '
    ot = init_orientation(foil%a_fm,'qu')
    call print_orientation(ot,'om',pret)
  end if
! a_mi (image to microscope) apart from a scale factor, these two are identical
! The EM book uses a beta rotation angle between the image and the microscope,
! but that is really not necessary because we already fix the image with respect to
! the microscope by defining q (the horizontal image direction) to point to the
! airlock. [verified 4/23/11, converted to quaternions on 6/4/13]
! So we'll keep this transformation equal to the identity at all times.
  foil%a_mi = (/ 1.D0,0.D0,0.D0,0.D0 /)   ! identity quaternion
  if (dinfo.eq.1) then
    pret = 'a_mi: '
    ot = init_orientation(foil%a_mi,'qu')
    call print_orientation(ot,'om',pret)
  end if
! This allows us to get the beam direction, since we know the foil normal and tilt angles
! The beam direction is the inverse transform of the microscope e_z-axis to the foil reference frame [verified 11/12/13]
  foil%B = quat_Lp( conjg(foil%a_fm), (/ 0.D0,0.D0,-1.D0 /) )
  foil%Bn = foil%B
  call NormVec(cell,foil%Bn,'c')
  if (dinfo.eq.1) then
    io_real(1:3) = foil%B(1:3)
    call WriteValue('  Beam direction (foil reference frame) = ',io_real,3,"('[',F12.5,',',F12.5,',',F12.5,']')")
  end if
! transform both the foil normal and the q-vector to the crystal cartesian reference frame (eq. 8.8) [verified 4/23/11,
! and again on 11/12/13 afterchanges elsewhere]
  call TransSpace(cell,foil%F,foil%Fn,'d','c')
  call TransSpace(cell,foil%q,foil%qn,'r','c')
  call NormVec(cell,foil%Fn,'c')
  call NormVec(cell,foil%qn,'c')
! a_fc (crystal to foil)
  a_fc(3,1:3) = foil%Fn(1:3)
  a_fc(1,1:3) = foil%qn(1:3)
  call CalcCross(cell,foil%Fn,foil%qn,ey,'c','c',0)
  call NormVec(cell,ey,'c')
  a_fc(2,1:3) = ey(1:3)
  foil%a_fc = om2qu(a_fc)
  if (dinfo.eq.1) then
    pret = 'a_fc: '
    ot = init_orientation(foil%a_fc,'qu')
    call print_orientation(ot,'om',pret)
  end if
! a_mc (crystal to microscope)
  foil%a_mc = quat_mult( conjg(foil%a_fm), foil%a_fc )
  if (dinfo.eq.1) then
    pret = 'a_mc: '
    ot = init_orientation(foil%a_mc,'qu')
    call print_orientation(ot,'om',pret)
  end if
! a_ic (crystal to image)
  foil%a_ic = quat_mult( conjg(foil%a_mi) , foil%a_mc)
  if (dinfo.eq.1) then
    pret = 'a_ic: '
    ot = init_orientation(foil%a_ic,'qu')
    call print_orientation(ot,'om',pret)
  end if
! a_fi (image to foil)
  foil%a_fi = quat_mult( foil%a_fc , conjg(foil%a_ic) )
  if (dinfo.eq.1) then
    pret = 'a_fi: '
    ot = init_orientation(foil%a_fi,'qu')
    call print_orientation(ot,'om',pret)
  end if
! express the beam direction in the Bravais reference frame [verified 4/23/11, and again on 11/12/13
! after changes elsewhere]
  ex = quat_Lp( conjg(foil%a_fc), dble(foil%Bn) )
  call TransSpace(cell,ex,ey,'c','d')
  call NormVec(cell,ey,'c')
  if (dinfo.eq.1) then
    io_real(1:3) = ey(1:3)
    call WriteValue('  Beam direction (crystal reference frame) = ', io_real, 3, "('[',F12.5,',',F12.5,',',F12.5,']'/)")
  end if
! define the foil shape (for now as an elliptic paraboloid z = brx * (x-xc)^2 + bry * (y-yc)^2)
if (.not.allocated(foil%sg)) allocate(foil%sg(foil%npix,foil%npiy))
! if the foil is not bent, then we set this array to zero, otherwise we compute the elliptical paraboloid
if ((foil%brx.eq.0.0).and.(foil%bry.eq.0.0)) then
  if (dinfo.eq.1) then
    call Message(' Initializing a flat foil ', frm = "(A)")
  end if
  foil%sg = 0.0
else
  dx = foil%npix*0.5
  dy = foil%npiy*0.5
  do i=1,foil%npix
   tt = foil%brx * (float(i)-dx-foil%cpx)**2
    do j=1,foil%npiy
! initialize the foil shape function; we assume that the center of the elliptic paraboloid is at location (cpx,cpy)
! presumably, this surface could also be a saddle point if the brx and bry values have opposite sign ...
      foil%sg(i,j) = tt + foil%bry * (float(j)-dy-foil%cpy)**2+ 2.0*foil%brxy * (float(j)-dy-foil%cpy)*(float(i)-dx-foil%cpx)
    end do
  end do
  if (dinfo.eq.1) then
    call Message(' Initializing a bent foil ', frm = "(A)")
    io_real(1)=minval(foil%sg); io_real(2)=maxval(foil%sg);
    call WriteValue('Range of local excitation error deviations : ', io_real, 2, "(F10.6,',',F10.6/)")
  end if
end if
end subroutine initialize_foil_geometry
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
initialize_foil_geometry calls writevalue, om2qu, quat_mult, float, init_orientation, print_orientation, message, normvec, dcos, quat_lp, transspace, calccross, dsin
init_foil_data calls initialize_foil_geometry
initializedefects calls init_foil_data