init_stacking_fault_data – Fortran Program
init_stacking_fault_data Subroutine
27 statements
Source File
public recursive subroutine init_stacking_fault_data(cell, defects, DF_L, DF_npix, DF_npiy, DF_g, dinfo, ECCI)
Uses:
io
files
@author Marc De Graef, Carnegie Mellon University @brief read stacking fault namelist files @param cell unit cell pointer @param defects defect structure @param DF_L @param DF_npix number of x-pixels @param DF_npiy number of y-pixels @param DF_gf @param dinfo logical to trigger verbose output @param ECCI logical optional to indicate ECCI formatting rather than regular TEM @date 1/5/99 MDG 1.0 original @date 5/19/01 MDG 2.0 f90 version @date 11/27/01 MDG 2.1 added kind support @date 06/04/13 MDG 3.0 rewrite @date 12/17/13 MDG 3.1 added ECCI mode @date 06/09/14 MDG 4.0 added cell, defects arguments @date 06/10/14 MDG 4.1 added foil argument
Arguments
Type Intent Optional Attributes Name
type(unitcell), pointer :: cell
type(defecttype), intent(inout) :: defects
real(kind=sgl), intent(in) :: DF_L
integer(kind=irg), intent(in) :: DF_npix
integer(kind=irg), intent(in) :: DF_npiy
real(kind=sgl), intent(in) :: DF_g(3)
integer(kind=irg), intent(in) :: dinfo
logical, intent(in), optional :: ECCI
Calls
Called By
Source Code
init_stacking_fault_data
Source Code
recursive subroutine init_stacking_fault_data(cell,defects,DF_L,DF_npix,DF_npiy,DF_g,dinfo,ECCI)
!DEC$ ATTRIBUTES DLLEXPORT :: init_stacking_fault_data
use io
use files
IMPLICIT NONE
type(unitcell),pointer                  :: cell
type(defecttype),INTENT(INOUT)          :: defects
integer(kind=irg),INTENT(IN)            :: DF_npix, DF_npiy, dinfo
real(kind=sgl),INTENT(IN)               :: DF_g(3)
real(kind=sgl),INTENT(IN)               :: DF_L
logical,INTENT(IN),OPTIONAL             :: ECCI
integer(kind=irg)                       :: i
real(kind=sgl)                          :: poisson
! read the namelist files for all of the stacking faults
 do i=1,defects%numsf
!   SFR = (/ 0.0, 0.0, 0.0 /)
    poisson = 0.0
! transform the fault fractional coordinates to nm in the image reference frame
    defects%SF(i)%id = defects%SF(i)%id * 0.5 * float(DF_npix) ! * DF_L  (zooming is done later in the image reference frame)
    defects%SF(i)%jd = defects%SF(i)%jd * 0.5 * float(DF_npiy) ! * DF_L
    defects%SF(i)%poisson = poisson
!   if (sum(abs(SFR)).eq.0.0) then
      defects%SF(i)%Rdisp = defects%SF(i)%lpb
!   else
!     defects%SF(i)%Rdisp = SFR
!   end if
! initialize the stacking fault variables and both partial dislocations; this might depend
! on the imaging mode (TEM vs. ECCI); careful here, since the counting of dislocations has
! changed with respect to release 2.0 !!!
    if (present(ECCI)) then
      call makestackingfaultECCI(cell,defects,i,DF_L,DF_npix,DF_npiy,DF_g,dinfo)
      defects%numYdisl = defects%numYdisl + 2
    else
      call makestackingfault(cell,defects,i,DF_L,DF_npix,DF_npiy,DF_g,dinfo)
      defects%numdisl = defects%numdisl + 2
    end if
 end do
end subroutine init_stacking_fault_data
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
init_stacking_fault_data calls float, makestackingfaultecci, makestackingfault
makestackingfaultecci calls float, transspace, point_inside_polygon, sgetrf, calcangle, sngl, quat_lp, makeyshdislocation, calccross, normvec
makestackingfault calls float, transspace, point_inside_polygon, sgetrf, quat_lp, calccross, normvec, makedislocation
makeyshdislocation calls transspace, calcangle, calccross, normvec, om2qu, calcdot, calclength, fatalerror, writevalue
makedislocation calls transspace, calcangle, quat_lp, calccross, normvec, om2qu, printmatrixcd, print_orientation_d, minvert, zroots, quat_mult, cinvert, init_orientation_d, transfourthranktensor, qu2om, printmatrixd
initializedefects calls init_stacking_fault_data