InitializeDefects – Fortran Program
InitializeDefects Subroutine
55 statements
Source File
public recursive subroutine InitializeDefects(cell, defects, jsonname, npix, npiy, L, gf, error_cnt, verbose)
Uses:
local
typedefs
io
JSONsupport
@author Marc De Graef, Carnegie Mellon University @brief read defect information, and generate all data that can be precomputed for each defect @date 11/22/15 MDG 1.0 original @date 11/24/15 MDG 1.1 added Ydislocations, stacking faults, inclusions and voids
Arguments
Type Intent Optional Attributes Name
type(unitcell), pointer :: cell
type(defecttype), intent(inout) :: defects
character(len=fnlen), intent(in) :: jsonname
integer(kind=irg), intent(in) :: npix
integer(kind=irg), intent(in) :: npiy
real(kind=sgl), intent(in) :: L
real(kind=sgl), intent(in) :: gf(3)
integer(kind=irg), intent(inout) :: error_cnt
logical, intent(in), optional :: verbose
Calls
Source Code
InitializeDefects
Source Code
recursive subroutine InitializeDefects(cell,defects,jsonname,npix,npiy,L,gf,error_cnt,verbose)
!DEC$ ATTRIBUTES DLLEXPORT :: InitializeDefects
use local
use typedefs
use io
use JSONsupport
IMPLICIT NONE
type(unitcell),pointer                  :: cell
type(defecttype),INTENT(INOUT)          :: defects
character(fnlen),INTENT(IN)             :: jsonname
integer(kind=irg),INTENT(IN)            :: npix
integer(kind=irg),INTENT(IN)            :: npiy
real(kind=sgl),INTENT(IN)               :: L
real(kind=sgl),INTENT(IN)               :: gf(3)
integer(kind=irg),INTENT(INOUT)         :: error_cnt
logical,INTENT(IN),OPTIONAL             :: verbose
integer(kind=irg)                       :: v, i, io_int(1)
error_cnt = 0
v = 0
if (PRESENT(verbose)) then
  if (verbose) then
    v = 1
  end if
end if
defects%numdisl = 0
defects%numYdisl = 0
defects%numsf = 0
defects%numvoids = 0
defects%numinc = 0
defects%numEinc = 0
! first of all, we need to read all the defect data from the jsonname file, including the foil data
call JSONreadDefectFile(cell, jsonname, defects, error_cnt, verbose)
call Message('The following defects were initialized : ')
  io_int(1) = defects%numdisl
  call WriteValue('  Number of dislocations       : ',io_int,1)
  io_int(1) = defects%numYdisl
  call WriteValue('  Number of Yoffe dislocations : ',io_int,1)
  io_int(1) = defects%numsf
  call WriteValue('  Number of stacking faults    : ',io_int,1)
  io_int(1) = defects%numinc
  call WriteValue('  Number of inclusions         : ',io_int,1)
  io_int(1) = defects%numEinc
  call WriteValue('  Number of Eshelby inclusions : ',io_int,1)
  io_int(1) = defects%numvoids
  call WriteValue('  Number of voids              : ',io_int,1)
! once we have this data, we need to initialize all other defect related parameters, including
! things like displacement field parameters etc...
! we begin with the foil itself
call init_foil_data(cell,defects,npix,npiy,L,v)
! then we add the defects, starting with all the regular dislocations, if any
if (defects%numdisl.ne.0) call init_dislocation_data(cell,defects,npix,npiy,gf,L,v)
! then Ydislocations
if (defects%numYdisl.ne.0) call init_YSH_dislocation_data(cell,defects,npix,npiy,gf,L,v)
! stacking faults
if (defects%numsf.ne.0) call init_stacking_fault_data(cell,defects,L,npix,npiy,gf,v)
! inclusions
if (defects%numinc.ne.0) call init_inclusion_data(defects,L,npix,npiy,v)
! Eshelby inclusions
if (defects%numEinc.ne.0) then
  do i=1,defects%numEinc
    call InitializeEshelbyInclusion(cell,defects,i,v,L,npix,npiy)
  end do
end if
! voids
if (defects%numvoids.ne.0) call init_void_data(defects,L,npix,npiy,v)
end subroutine InitializeDefects
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
initializedefects calls init_foil_data, jsonreaddefectfile, init_dislocation_data, init_stacking_fault_data, init_ysh_dislocation_data, init_void_data, initializeeshelbyinclusion, writevalue, init_inclusion_data, message
init_foil_data calls writevalue, float, qu2om, initialize_foil_geometry
jsonreaddefectfile calls writevalue, jsongetdouble, json_parse, emsoft_tonativepath, jsongetdoublevector, json_print_error_message, json_get_child, jsonreadfoildata, json_get, fatalerror, emsoft_getemdatapathname, json_failed, json_info, json_failtest, json_initialize
init_dislocation_data calls float, makedislocation
init_stacking_fault_data calls float, makestackingfaultecci, makestackingfault
init_ysh_dislocation_data calls float, makeyshdislocation
init_void_data calls float, quat_lp
initializeeshelbyinclusion calls float, el2k, kdelta, el1k, dasin
init_inclusion_data calls float, quat_lp
initialize_foil_geometry calls writevalue, message, float, om2qu, quat_mult, init_orientation, print_orientation, normvec, dcos, quat_lp, transspace, calccross, dsin
jsongetdouble calls writevalue, json_get
jsongetdoublevector calls writevalue, json_get
jsonreadfoildata calls writevalue, message, jsongetdouble, json_parse, emsoft_tonativepath, jsongetdoublevector, json_print_error_message, json_get_child, emsoft_getemdatapathname, json_failed, json_info, json_failtest, calcdot
json_failtest calls json_print_error_message, json_failed
makedislocation calls qu2om, om2qu, quat_mult, normvec, quat_lp, transspace, calccross, printmatrixcd, print_orientation_d, minvert, zroots, cinvert, init_orientation_d, transfourthranktensor, printmatrixd, calcangle
makestackingfaultecci calls float, normvec, quat_lp, transspace, calccross, calcangle, point_inside_polygon, sgetrf, sngl, makeyshdislocation
makestackingfault calls float, normvec, quat_lp, transspace, calccross, makedislocation, point_inside_polygon, sgetrf
makeyshdislocation calls writevalue, om2qu, normvec, transspace, calccross, fatalerror, calcdot, calcangle, calclength