InnerProdGPU – Fortran Program
InnerProdGPU Subroutine
85 statements
Source File
public recursive subroutine InnerProdGPU(cl_expt, cl_dict, Ne, Nd, correctsize, results, numd, selnumd, csource, source_length, platform, device, context, command_queue)
Uses:
local
clfortran
CLsupport
iso_c_binding
io
error
@author Saransh Singh, Carnegie Mellon University @brief Perform the inner product computations for the dictionary approach @param expt vector with list of observed patterns @param dict vector with list of calculated patterns @param Ne number of patterns in the expt vector @param Nd number of patterns in the dict vector @param L size of one single pattern @param result result of the matrix multiplication @param source the opencl kernel as a character array @param length of character array @param platform opencl platform type @param device opencl device type @param context opencl context type @param command_queue opencl command queue @date 12/09/14 SS 1.0 original @date 27/01/15 SS 1.1 modified to call the subroutine from mastersubroutine @date 02/24/16 MDG 1.2 converted OpenCL calls to clfortran from fortrancl @date 03/03/16 MDG 1.3 added C_NULL_CHAR to kernelname @date 06/07/17 MDG 1.4 removed progoptions from Build Program call; caused some issues on Linux in Release mode
Arguments
Type Intent Optional Attributes Name
integer(kind=c_intptr_t), intent(inout), target :: cl_expt
integer(kind=c_intptr_t), intent(inout), target :: cl_dict
integer(kind=4), intent(in) :: Ne
integer(kind=4), intent(in) :: Nd
integer(kind=4), intent(in) :: correctsize
real(kind=4), intent(out), target :: results(Ne*Nd)
integer(kind=irg), intent(in) :: numd
integer(kind=irg), intent(in) :: selnumd
character(kind=len=source_length,c_char), intent(in), TARGET :: csource
integer(kind=c_size_t), intent(in), target :: source_length
integer(kind=c_intptr_t), intent(in), allocatable, target :: platform(:)
integer(kind=c_intptr_t), intent(inout), allocatable, target :: device(:)
integer(kind=c_intptr_t), intent(inout), target :: context
integer(kind=c_intptr_t), intent(inout), target :: command_queue
Calls
Source Code
InnerProdGPU
Source Code
recursive subroutine InnerProdGPU(cl_expt,cl_dict,Ne,Nd,correctsize,results,numd,selnumd,csource,source_length, &
                        platform,device,context,command_queue)
!DEC$ ATTRIBUTES DLLEXPORT :: InnerProdGPU
use local
use clfortran
use CLsupport
use ISO_C_BINDING
use io
use error
IMPLICIT NONE
real(kind=4),INTENT(OUT),target                     :: results(Ne*Nd)
integer(c_intptr_t),target,INTENT(INOUT)            :: cl_expt
integer(c_intptr_t),target,INTENT(INOUT)            :: cl_dict
integer(kind=4),INTENT(IN)                          :: Ne
integer(kind=4),INTENT(IN)                          :: Nd
integer(kind=4),INTENT(IN)                          :: correctsize
integer(kind=irg),INTENT(IN)                        :: numd, selnumd
integer(c_size_t),INTENT(IN),target                 :: source_length
character(len=source_length, KIND=c_char),TARGET,INTENT(IN)      :: csource
integer(c_intptr_t),allocatable,target,INTENT(IN)   :: platform(:)
integer(c_intptr_t),allocatable,target,INTENT(INOUT):: device(:)
integer(c_intptr_t),target,INTENT(INOUT)            :: context
integer(c_intptr_t),target,INTENT(INOUT)            :: command_queue
type(c_ptr), target                                 :: psource
integer(c_int32_t)                                  :: ierr, ierr2, pcnt
integer(c_intptr_t),target                          :: prog
integer(c_intptr_t),target                          :: kernel
integer(c_intptr_t),target                          :: cl_result
character(19),target                                :: progoptions
integer(c_size_t)                                   :: cnum
character(len=source_length),target                 :: source
real(kind=4)                                        :: dicttranspose(Nd*correctsize)
integer(kind=4),parameter                           :: iunit = 40
character(fnlen)                                    :: info ! info about the GPU
integer(kind=8),target                              :: globalsize(2),localsize(2)
integer, parameter                                  :: source_length_build_info = 10000
character(len = source_length)                      :: source_build_info
integer(kind=4)                                     :: num,istat,i,j,ii,jj,kk, io_int(1)
integer(kind=4),target                              :: Wexp,Wdict
integer(kind=8)                                     :: size_in_bytes_expt,size_in_bytes_dict,size_in_bytes_result
character(9),target                                 :: kernelname
character(10, KIND=c_char),target                   :: ckernelname
integer(kind=irg)                                   :: irec
size_in_bytes_result = Ne*Nd*sizeof(results(1))
Wexp = correctsize
Wdict = Nd
localsize = (/16,16/)
globalsize = (/Ne,Nd/)
!=====================
! INITIALIZATION
!=====================
! was performed in the calling program
!=====================
! BUILD THE KERNEL
!=====================
! create the program
pcnt = 1
psource = C_LOC(csource)
prog = clCreateProgramWithSource(context, pcnt, C_LOC(psource), C_LOC(source_length), ierr)
call CLerror_check('InnerProdGPU:clCreateProgramWithSource', ierr)
! build the program
progoptions = '-cl-no-signed-zeros'
! ierr = clBuildProgram(prog, numd, C_LOC(device), C_LOC(progoptions), C_NULL_FUNPTR, C_NULL_PTR)
ierr = clBuildProgram(prog, numd, C_LOC(device), C_NULL_PTR, C_NULL_FUNPTR, C_NULL_PTR)
! get the compilation log
ierr2 = clGetProgramBuildInfo(prog, device(selnumd), CL_PROGRAM_BUILD_LOG, sizeof(source), C_LOC(source), cnum)
! if(cnum > 1) call Message(trim(source(1:cnum))//'test',frm='(A)')
call CLerror_check('InnerProdGPU:clBuildProgram', ierr)
call CLerror_check('InnerProdGPU:clGetProgramBuildInfo', ierr2)
! finally get the kernel and release the program
kernelname = 'InnerProd'
ckernelname = kernelname
ckernelname(10:10) = C_NULL_CHAR
kernel = clCreateKernel(prog, C_LOC(ckernelname), ierr)
call CLerror_check('InnerProdGPU:clCreateKernel', ierr)
ierr = clReleaseProgram(prog)
call CLerror_check('InnerProdGPU:clReleaseProgram', ierr)
! create buffer
cl_result = clCreateBuffer(context, CL_MEM_READ_WRITE, size_in_bytes_result, C_NULL_PTR, ierr)
call CLerror_check('InnerProdGPU:clCreateBuffer', ierr)
! set kernel arguments
ierr =  clSetKernelArg(kernel, 0, sizeof(cl_expt), C_LOC(cl_expt))
call CLerror_check('InnerProdGPU:clSetKernelArg:cl_expt', ierr)
ierr = clSetKernelArg(kernel, 1, sizeof(cl_dict), C_LOC(cl_dict))
call CLerror_check('InnerProdGPU:clSetKernelArg:cl_dict', ierr)
ierr = clSetKernelArg(kernel, 2, sizeof(Wexp), C_LOC(Wexp))
call CLerror_check('InnerProdGPU:clSetKernelArg:Wexp', ierr)
ierr = clSetKernelArg(kernel, 3, sizeof(Wdict), C_LOC(Wdict))
call CLerror_check('InnerProdGPU:clSetKernelArg:Wdict', ierr)
ierr = clSetKernelArg(kernel, 4, sizeof(cl_result), C_LOC(cl_result))
call CLerror_check('InnerProdGPU:clSetKernelArg:cl_result', ierr)
!execute the kernel
ierr = clEnqueueNDRangeKernel(command_queue, kernel, 2, C_NULL_PTR, C_LOC(globalsize), C_LOC(localsize), &
                              0, C_NULL_PTR, C_NULL_PTR)
call CLerror_check('InnerProdGPU:clEnqueueNDRangeKernel', ierr)
! wait for the commands to finish
ierr = clFinish(command_queue)
call CLerror_check('InnerProdGPU:clFinish', ierr)
! read the resulting vector from device memory
ierr = clEnqueueReadBuffer(command_queue,cl_result,CL_TRUE,0_8,size_in_bytes_result,C_LOC(results(1)),0,C_NULL_PTR,C_NULL_PTR)
call CLerror_check('InnerProdGPU:clEnqueueReadBuffer', ierr)
ierr = clReleaseKernel(kernel)
call CLerror_check('InnerProdGPU:clReleaseKernel', ierr)
ierr = clReleaseMemObject(cl_result)
call CLerror_check('InnerProdGPU:clReleaseMemObject:cl_result', ierr)
end subroutine InnerProdGPU
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
innerprodgpu calls clreleasememobject, clgetprogrambuildinfo, clcreatekernel, clenqueuendrangekernel, clenqueuereadbuffer, clreleasekernel, clsetkernelarg, clreleaseprogram, clcreatebuffer, clfinish, clcreateprogramwithsource, clbuildprogram, clerror_check
clerror_check calls writevalue, fatalerror