JSONreadDefectFile – Fortran Program
JSONreadDefectFile Subroutine
305 statements
Source File
public recursive subroutine JSONreadDefectFile(cell, jsonname, defects, error_cnt, verbose)
Uses:
iso_c_binding
NameListHandlers
io
error
iso_fortran_env
@author Marc De Graef, Carnegie Mellon University @brief parse json file into defect namelist structures @param cell unit cell pointer @param jsonname input file name @param defects defect structure, to be filled by this routine @param error_cnt total number of errors encountered by json routines @param verbose [optional] print a lot of output if present and true @date 11/20/15 MDG 1.0 new routine @date 12/08/15 MDG 1.1 added Einclusion defect type
Arguments
Type Intent Optional Attributes Name
type(unitcell), intent(in), pointer :: cell
character(len=fnlen), intent(in) :: jsonname
type(defecttype), intent(inout) :: defects
integer(kind=irg), intent(inout) :: error_cnt
logical, intent(in), optional :: verbose
Calls
Called By
Source Code
JSONreadDefectFile
Source Code
recursive subroutine JSONreadDefectFile(cell, jsonname, defects, error_cnt,verbose)
!DEC$ ATTRIBUTES DLLEXPORT :: JSONreadDefectFile
use ISO_C_BINDING
use NameListHandlers
use io
use error
use, intrinsic :: iso_fortran_env, only: wp => real64
IMPLICIT NONE
type(unitcell),pointer,INTENT(IN)                     :: cell
character(fnlen),INTENT(IN)                           :: jsonname
type(defecttype),INTENT(INOUT)                        :: defects
integer(kind=irg),INTENT(INOUT)                       :: error_cnt
logical,INTENT(IN),OPTIONAL                           :: verbose
type(json_file)                                       :: json    !the JSON structure read from the file:
type(json_value),pointer                              :: jval, child, child2, child3, child4
character(kind=jsonCK,len=:),allocatable                  :: name
integer(kind=irg)                                     :: i, j, jj, kk, v, io_int(3), jskip, ndis
integer(kind=irg)                                     :: vart,nc, nc2, nc3, nc4, nc5
logical                                               :: found
character(fnlen)                                      :: foilfilename, str, filename, dummystr
real(wp)                                              :: v4(4), v5(5), v6(6), v9(9), io_real(6)
v = 0
if (PRESENT(verbose)) then
  if (verbose) then
    v = 1
  end if
end if
dummystr = ''
! first of all, initialize json and return an error message if it does not exist
error_cnt = 0
call json_initialize(); call JSON_failtest(error_cnt)
filename = trim(EMsoft_getEMdatapathname())//trim(jsonname)
filename = EMsoft_toNativePath(filename)
! populate the jval json_value structure
call json_parse(trim(filename), jval)
if (json_failed().eqv..TRUE.) then    !if there was an error reading the file
  call json_print_error_message(error_unit)
  error_cnt = error_cnt + 1
else
! get the top level file descriptor (should be the file name) and the number of its children nc (should really be 1)
  call json_info(jval,vart,nc,name)             ! jval name = filename
  if (v.eq.1) then
    call WriteValue(' Defect file name : ',name,"(' ',A)")
  end if
! loop over the children
  do i=1,nc
    call json_get_child(jval,i,child)
    call json_info(child,vart,nc2,name)         ! child name = DefectDescriptors
! loop over those children, which are the actual defect descriptors and deal with each of them separately
! the foil date must be the first entry; if it is not, then loop until we find it
    found = .FALSE.
    nc2loop: do j=1,nc2
      call json_get_child(child,j,child2)
      call json_info(child2,vart,nc3,name)
      if (.not.(name.eq.'foil')) CYCLE nc2loop
! name = foil, so read the name of the foil descriptor file
      call json_get(child2,'foilfilename',child3,found)
      jskip = j
      if (found) then
        call json_get(child3, name)
        if (v.eq.1) call WriteValue(' Foil file name = ',trim(name),"(' ',A)")
        defects%foilname = trim(name)
      end if
    end do nc2loop
    if (.not.found) then
     call FatalError('JSONreadDefectFile','JSON file does not contain a foilfilename entry')
    end if
! here we call the foil reading routine to first fill all the foil parameters
    call JSONreadFoilData(cell, defects, error_cnt, verbose)
! then we need to get the total number of defects in the file, so that we can allocate
! the correct array sizes in the defects structure
    ndis = 0
    nc2loop2: do j=1,nc2
      if (j.eq.jskip) CYCLE nc2loop2
      call json_get_child(child,j,child2)
      call json_info(child2,vart,nc3,name)
      if (name.eq.'voids') then
        allocate(defects%voids(nc3))
        defects%numvoids = nc3
      end if
      if (name.eq.'inclusions') then
        allocate(defects%inclusions(nc3))
        defects%numinc = nc3
      end if
      if (name.eq.'Einclusions') then
        allocate(defects%Einclusions(nc3))
        defects%numEinc = nc3
      end if
      if (name.eq.'Ydislocations') then
        allocate(defects%YD(nc3))
        defects%numYdisl = nc3
      end if
      if (name.eq.'dislocations') then
        ndis = ndis + nc3
        defects%numdisl = nc3
      end if
      if (name.eq.'stackingfaults') then
        allocate(defects%SF(nc3))
        ndis = ndis + 2*nc3
        defects%numsf = nc3
      end if
    end do nc2loop2
    if (ndis.gt.0) allocate(defects%DL(ndis))
! now loop over all entries at the child level (Except for the foil data) and
! read the individual defect parameters; note that these are nested on level 4...
    ndis = 1
    nc2loop3: do j=1,nc2
      if (j.eq.jskip) CYCLE nc2loop3
      call json_get_child(child,j,child2)
      call json_info(child2,vart,nc3,name)
! dislocations
      if (name.eq.'dislocations') then
        do jj=1,nc3
         if (v.eq.1) then
           io_int(1) = jj
           call WriteValue('   dislocation #  ',io_int,1,"(I4)")
         end if
         call json_get_child(child2,jj,child3)
         call json_info(child3,vart,nc4,name)
         do kk=1,nc4
          call json_get_child(child3,kk,child4)
          call json_info(child4,vart,nc5,name)
          if (name.eq.'id') then
            str = '        x-coordinate  = '
            defects%DL(ndis)%id = JSONgetDouble(child4,str,v)
          end if
          if (name.eq.'jd') then
            str = '        y-coordinate  = '
            defects%DL(ndis)%jd = JSONgetDouble(child4,str,v)
          end if
          if (name.eq.'zfrac') then
            str = '        zfrac         = '
            defects%DL(ndis)%zfrac = JSONgetDouble(child4,str,v)
          end if
          if (name.eq.'u') then
            str = '        u             = '
            defects%DL(ndis)%u = JSONgetDoubleVector(child4,nc5,str,v)
          end if
          if (name.eq.'bv') then
            str = '        bv            = '
            defects%DL(ndis)%burg = JSONgetDoubleVector(child4,nc5,str,v)
          end if
         end do
         ndis = ndis + 1
        end do
        CYCLE nc2loop3
      end if
! Ydislocations
      if (name.eq.'Ydislocations') then
        do jj=1,nc3
         if (v.eq.1) then
           io_int(1) = jj
           call WriteValue('   Ydislocation #  ',io_int,1,"(I4)")
         end if
         call json_get_child(child2,jj,child3)
         call json_info(child3,vart,nc4,name)
         do kk=1,nc4
          call json_get_child(child3,kk,child4)
          call json_info(child4,vart,nc5,name)
          if (name.eq.'id') then
            str = '        x-coordinate  = '
            defects%YD(jj)%id = JSONgetDouble(child4,str,v)
          end if
          if (name.eq.'jd') then
            str = '        y-coordinate  = '
            defects%YD(jj)%jd = JSONgetDouble(child4,str,v)
          end if
          if (name.eq.'poisson') then
            str = '        poisson       = '
            defects%YD(jj)%sig = JSONgetDouble(child4,str,v)
          end if
          if (name.eq.'u') then
            str = '        u             = '
            defects%YD(jj)%u = JSONgetDoubleVector(child4,nc5,str,v)
          end if
          if (name.eq.'bv') then
            str = '        bv            = '
            defects%YD(jj)%burg = JSONgetDoubleVector(child4,nc5,str,v)
          end if
         end do
        end do
        CYCLE nc2loop3
      end if
! stacking faults
      if (name.eq.'stackingfaults') then
        do jj=1,nc3
         if (v.eq.1) then
           io_int(1) = jj
           call WriteValue('   Stacking Fault #  ',io_int,1,"(I4)")
         end if
         call json_get_child(child2,jj,child3)
         call json_info(child3,vart,nc4,name)
         do kk=1,nc4
          call json_get_child(child3,kk,child4)
          call json_info(child4,vart,nc5,name)
          if (name.eq.'SFi') then
            str = '        x-coordinate  = '
            defects%SF(jj)%id = JSONgetDouble(child4,str,v)
          end if
          if (name.eq.'SFj') then
            str = '        y-coordinate  = '
            defects%SF(jj)%jd = JSONgetDouble(child4,str,v)
          end if
          if (name.eq.'SFsep') then
            str = '        SF separation = '
            defects%SF(jj)%sep = JSONgetDouble(child4,str,v)
          end if
          if (name.eq.'SFplane') then
            str = '        SF plane      = '
            defects%SF(jj)%plane = JSONgetDoubleVector(child4,nc5,str,v)
          end if
          if (name.eq.'SFlpu') then
            str = '        SF lpu        = '
            defects%SF(jj)%lpu = JSONgetDoubleVector(child4,nc5,str,v)
          end if
          if (name.eq.'SFtpu') then
            str = '        SF tpu        = '
            defects%SF(jj)%tpu = JSONgetDoubleVector(child4,nc5,str,v)
          end if
          if (name.eq.'SFlpb') then
            str = '        SF lpb        = '
            defects%SF(jj)%lpb = JSONgetDoubleVector(child4,nc5,str,v)
          end if
          if (name.eq.'SFtpb') then
            str = '        SF tpb        = '
            defects%SF(jj)%tpb = JSONgetDoubleVector(child4,nc5,str,v)
          end if
         end do
        end do
        CYCLE nc2loop3
      end if
! voids
      if (name.eq.'voids') then
        do jj=1,nc3
         call json_get_child(child2,jj,child3)
         call json_info(child3,vart,nc4,name)
         v4 = JSONgetDoubleVector(child3,nc4,dummystr,0)
         defects%voids(jj)%xpos = v4(1)
         defects%voids(jj)%ypos = v4(2)
         defects%voids(jj)%zpos = v4(3)
         defects%voids(jj)%radius = v4(4)
         if (v.eq.1) then
           io_real(1:4) = v4(1:4)
           io_int(1) = jj
           call WriteValue(' void   ',io_int,1,"(I4,$)")
           call WriteValue('',io_real,4)
         end if
        end do
        CYCLE nc2loop3
      end if
! inclusions
      if (name.eq.'inclusions') then
        do jj=1,nc3
         call json_get_child(child2,jj,child3)
         call json_info(child3,vart,nc4,name)
         v5 = JSONgetDoubleVector(child3,nc4,dummystr,0)
         defects%inclusions(jj)%xpos = v5(1)
         defects%inclusions(jj)%ypos = v5(2)
         defects%inclusions(jj)%zpos = v5(3)
         defects%inclusions(jj)%radius = v5(4)
         defects%inclusions(jj)%C = v5(5)
         if (v.eq.1) then
           io_real(1:5) = v5(1:5)
           io_int(1) = jj
           call WriteValue(' inclusion    ',io_int,1,"(I4,$)")
           call WriteValue('',io_real,5)
         end if
        end do
        CYCLE nc2loop3
      end if
! Eshelby ellipsoidal inclusions (isotropic)
       if (name.eq.'Einclusions') then
         do jj=1,nc3
          if (v.eq.1) then
            io_int(1) = jj
            call WriteValue('   Einclusion   #  ',io_int,1,"(I4)")
          end if
          call json_get_child(child2,jj,child3)
          call json_info(child3,vart,nc4,name)
          do kk=1,nc4
           call json_get_child(child3,kk,child4)
           call json_info(child4,vart,nc5,name)
           if (name.eq.'xyz') then
             str = '        xyz           = '
             defects%Einclusions(jj)%xyz = JSONgetDoubleVector(child4,nc5,str,v)
           end if
           if (name.eq.'a123') then
             str = '        a123          = '
             defects%Einclusions(jj)%a123 = JSONgetDoubleVector(child4,nc5,str,v)
           end if
           if (name.eq.'nu') then
             str = '        nu            = '
             defects%Einclusions(jj)%nu = JSONgetDouble(child4,str,v)
           end if
           if (name.eq.'epsstarvoigt') then
             str = '        eps* (Voigt)  = '
             v6 = JSONgetDoubleVector(child4,nc5,str,v)
             defects%Einclusions(jj)%epsstar(1,1) = v6(1)
             defects%Einclusions(jj)%epsstar(2,2) = v6(2)
             defects%Einclusions(jj)%epsstar(3,3) = v6(3)
             defects%Einclusions(jj)%epsstar(1,2) = v6(6)*0.5D0
             defects%Einclusions(jj)%epsstar(2,1) = v6(6)*0.5D0
             defects%Einclusions(jj)%epsstar(1,3) = v6(5)*0.5D0
             defects%Einclusions(jj)%epsstar(3,1) = v6(5)*0.5D0
             defects%Einclusions(jj)%epsstar(2,3) = v6(4)*0.5D0
             defects%Einclusions(jj)%epsstar(3,2) = v6(4)*0.5D0
           end if
           if (name.eq.'principalaxes') then
             str = '        principalaxes = '
             v9 = JSONgetDoubleVector(child4,nc5,str,v)
             defects%Einclusions(jj)%principalaxes(1,1:3) = v9(1:3)
             defects%Einclusions(jj)%principalaxes(2,1:3) = v9(4:6)
             defects%Einclusions(jj)%principalaxes(3,1:3) = v9(7:9)
           end if
          end do
         end do
         CYCLE nc2loop3
       end if
! other defct types to be added here
    end do nc2loop3
  end do
end if
call JSON_failtest(error_cnt)
end subroutine JSONreadDefectFile
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
jsonreaddefectfile calls writevalue, jsongetdouble, json_parse, emsoft_tonativepath, jsongetdoublevector, json_print_error_message, json_get_child, jsonreadfoildata, json_get, fatalerror, emsoft_getemdatapathname, json_failed, json_info, json_failtest, json_initialize
jsongetdouble calls writevalue, json_get
jsongetdoublevector calls writevalue, json_get
jsonreadfoildata calls writevalue, jsongetdouble, json_parse, emsoft_tonativepath, jsongetdoublevector, json_print_error_message, json_get_child, emsoft_getemdatapathname, json_failed, json_info, json_failtest, calcdot, message
json_failtest calls json_print_error_message, json_failed
initializedefects calls jsonreaddefectfile