JSONreadEBSDNameList – Fortran Program
JSONreadEBSDNameList Subroutine
88 statements
Source File
public recursive subroutine JSONreadEBSDNameList(enl, jsonname, error_cnt)
Uses:
iso_c_binding
NameListHandlers
error
@author Marc De Graef, Carnegie Mellon University @brief read json file and fill enl structure (used by EMEBSD.f90) @param enl EBSD name list structure @param jsonname input file name @param error_cnt total number of errors encountered by json routines @date 08/20/15 MDG 1.0 new routine
Arguments
Type Intent Optional Attributes Name
type(EBSDNameListType), intent(inout) :: enl
character(len=fnlen), intent(in) :: jsonname
integer(kind=irg), intent(inout) :: error_cnt
Calls
Source Code
JSONreadEBSDNameList
Source Code
recursive subroutine JSONreadEBSDNameList(enl, jsonname, error_cnt)
!DEC$ ATTRIBUTES DLLEXPORT :: JSONreadEBSDNameList
use ISO_C_BINDING
use NameListHandlers
use error
IMPLICIT NONE
type(EBSDNameListType),INTENT(INOUT)                  :: enl
character(fnlen),INTENT(IN)                           :: jsonname
integer(kind=irg),INTENT(INOUT)                       :: error_cnt
type(json_file)                                       :: json    !the JSON structure read from the file:
type(EBSDNameListType)                                :: defenl
logical                                               :: init = .TRUE.
character(fnlen)                                      :: nmlfile = '', ep, s, s2
real(kind=wp)                                         :: rval
character(kind=jsonCK,len=:),allocatable                  :: cval
real(wp),dimension(:),allocatable                     :: rvec
! first of all, open the file and return an error message if it does not exist
error_cnt = 0
call json_initialize(); call JSON_failtest(error_cnt)
! populate the json structure
call json%load_file(filename = trim(jsonname))
if (json_failed().eqv..TRUE.) then    !if there was an error reading the file
  call json_print_error_message(error_unit)
  error_cnt = error_cnt + 1
else
! ok, we got here so we need to initialize the namelist first to its default values (set in NameListHandlers)
  call GetEBSDNameList(nmlfile, defenl, initonly=init)
  ep = 'EBSDdata.stdout'
  call JSONreadInteger(json, ep, enl%stdout, defenl%stdout)
  ep = 'EBSDdata.numsx'
  call JSONreadInteger(json, ep, enl%numsx, defenl%numsx)
  ep = 'EBSDdata.numsy'
  call JSONreadInteger(json, ep, enl%numsy, defenl%numsy)
  ep = 'EBSDdata.binning'
  call JSONreadInteger(json, ep, enl%binning, defenl%binning)
  ep = 'EBSDdata.nthreads'
  call JSONreadInteger(json, ep, enl%nthreads, defenl%nthreads)
  ep = 'EBSDdata.energyaverage'
  call JSONreadInteger(json, ep, enl%energyaverage, defenl%energyaverage)
  ep = 'EBSDdata.L'
  call JSONreadReal(json, ep, enl%L, defenl%L)
  ep = 'EBSDdata.thetac'
  call JSONreadReal(json, ep, enl%thetac, defenl%thetac)
  ep = 'EBSDdata.delta'
  call JSONreadReal(json, ep, enl%delta, defenl%delta)
  ep = 'EBSDdata.xpc'
  call JSONreadReal(json, ep, enl%xpc, defenl%xpc)
  ep = 'EBSDdata.ypc'
  call JSONreadReal(json, ep, enl%ypc, defenl%ypc)
  ep = 'EBSDdata.omega'
  call JSONreadReal(json, ep, enl%omega, defenl%omega)
  ep = 'EBSDdata.energymin'
  call JSONreadReal(json, ep, enl%energymin, defenl%energymin)
  ep = 'EBSDdata.energymax'
  call JSONreadReal(json, ep, enl%energymax, defenl%energymax)
  ep = 'EBSDdata.gammavalue'
  call JSONreadReal(json, ep, enl%gammavalue, defenl%gammavalue)
  ep = 'EBSDdata.axisangle'
  call JSONreadRealVec(json, ep, enl%axisangle, defenl%axisangle, size(enl%axisangle))
  ep = 'EBSDdata.beamcurrent'
  call JSONreadDouble(json, ep, enl%beamcurrent, defenl%beamcurrent)
  ep = 'EBSDdata.dwelltime'
  call JSONreadDouble(json, ep, enl%dwelltime, defenl%dwelltime)
  ep = 'EBSDdata.maskpattern'
  s = enl%maskpattern
  s2 = defenl%maskpattern
  call JSONreadString(json, ep, s, s2)
  ep = 'EBSDdata.scalingmode'
  s = enl%scalingmode
  s2 = defenl%scalingmode
  call JSONreadString(json, ep, s, s2)
  ep = 'EBSDdata.eulerconvention'
  s = enl%eulerconvention
  s2 = defenl%eulerconvention
  call JSONreadString(json, ep, s, s2)
  ep = 'EBSDdata.outputformat'
  s = enl%outputformat
  s2 = defenl%outputformat
  call JSONreadString(json, ep, s, s2)
  ep = 'EBSDdata.anglefile'
  call JSONreadString(json, ep, enl%anglefile, defenl%anglefile)
  ep = 'EBSDdata.masterfile'
  call JSONreadString(json, ep, enl%masterfile, defenl%masterfile)
  ep = 'EBSDdata.energyfile'
  call JSONreadString(json, ep, enl%energyfile, defenl%energyfile)
  ep = 'EBSDdata.datafile'
  call JSONreadString(json, ep, enl%datafile, defenl%datafile)
end if
call json%destroy(); call JSON_failtest(error_cnt)
end subroutine JSONreadEBSDNameList
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
jsonreadebsdnamelist calls jsonreaddouble, jsonreadstring, jsonreadinteger, json_print_error_message, jsonreadrealvec, json_initialize, getebsdnamelist, json_failtest, jsonreadreal, json_failed
jsonreadrealvec calls sngl
getebsdnamelist calls emsoft_tonativepath, fatalerror
json_failtest calls json_print_error_message, json_failed
jsonreadreal calls sngl