JSONreadFoilData – Fortran Program
JSONreadFoilData Subroutine
123 statements
Source File
public recursive subroutine JSONreadFoilData(cell, defects, error_cnt, verbose)
Uses:
iso_c_binding
NameListHandlers
io
error
crystal
iso_fortran_env
@author Marc De Graef, Carnegie Mellon University @brief parse json foil file into defect namelist structures @param cell unit cell pointer @param defects defect structure, to be filled by this routine @param error_cnt total number of errors encountered by json routines @param verbose [optional] print a lot of output if present and true @date 11/21/15 MDG 1.0 new routine
Arguments
Type Intent Optional Attributes Name
type(unitcell), intent(in), pointer :: cell
type(defecttype), intent(inout) :: defects
integer(kind=irg), intent(inout) :: error_cnt
logical, intent(in), optional :: verbose
Calls
Called By
Source Code
JSONreadFoilData
Source Code
recursive subroutine JSONreadFoilData(cell, defects, error_cnt, verbose)
!DEC$ ATTRIBUTES DLLEXPORT :: JSONreadFoilData
use ISO_C_BINDING
use NameListHandlers
use io
use error
use crystal
use, intrinsic :: iso_fortran_env, only: wp => real64
IMPLICIT NONE
type(unitcell),pointer,INTENT(IN)                     :: cell
type(defecttype),INTENT(INOUT)                        :: defects
integer(kind=irg),INTENT(INOUT)                       :: error_cnt
logical,INTENT(IN),OPTIONAL                           :: verbose
type(json_value),pointer                              :: jval, child, child2, child3
type(json_value), pointer                             :: tmp_json_ptr
character(kind=jsonCK,len=:),allocatable                  :: name
integer(kind=irg)                                     :: v, i, j, jj, vart, nc, nc2, nc3, io_int(3)
real(kind=wp),dimension(:),allocatable                :: vec3
real(kind=wp)                                         :: val
real(kind=sgl)                                        :: io_real(6), x
logical                                               :: found
character(4),parameter                                :: row(6) = (/ 'row1', 'row2', 'row3', 'row4', 'row5', 'row6' /)
character(fnlen)                                      :: str, filename
v = 0
if (PRESENT(verbose)) then
  if (verbose) then
    v = 1
  end if
end if
! set the default values for all entries
 defects%foil%elmo = 0.0                         ! elastic moduli
 defects%foil%F = (/ 0.0,0.0,1.0 /)              ! foil normal in direct space Bravais reference frame
 defects%foil%q = (/ 1.0,0.0,0.0 /)              ! reciprocal space vector along primary tilt axis towards airlock
 defects%foil%alP = 0.0                          ! primary tilt angle in degrees
 defects%foil%alS = 0.0                          ! secondary tilt angle (for double tilt holder)
 defects%foil%alR = 0.0                          ! secondary tilt angle (for rotation tilt holder)
 defects%foil%beP = 0.0                          ! angle of primary tilt axis w.r.t. image bottom edge
 defects%foil%z0 = 100.0                         ! foil thickness in nm
! the following are not used currently, but need to be initialized properly
 defects%foil%brx = 0.0                          ! parameters to describe the foil shape as a quadratic surface
 defects%foil%bry = 0.0
 defects%foil%brxy = 0.0
 defects%foil%cpx = 0.0                          ! center of the foil quadratic surface within [-1,1] range in pixel coordinates
 defects%foil%cpy = 0.0
filename = trim(EMsoft_getEMdatapathname())//trim(defects%foilname)
filename = EMsoft_toNativePath(filename)
! json has alrady been initialized, so we should be ok directly reading the data from the file
call json_parse(trim(filename), jval)
if (json_failed().eqv..TRUE.) then    !if there was an error reading the file
  call json_print_error_message(error_unit)
  error_cnt = error_cnt + 1
else
  call json_info(jval,vart,nc,name)             ! jval name = filename
! loop over the children (only 1)
  do i=1,nc
    call json_get_child(jval,i,child)
    call json_info(child,vart,nc2,name)         ! child name = FoilDescriptor
    nc2loop: do j=1,nc2
      call json_get_child(child,j,child2)
      call json_info(child2,vart,nc3,name)
! foil normal
        if (name.eq.'foilF') then
          str = '   Foil normal F = '
          defects%foil%F = JSONgetDoubleVector(child2,nc3,str,v)
        end if
! foil q vector
        if (name.eq.'foilq') then
          str = '   Foil q-vector = '
          defects%foil%q = JSONgetDoubleVector(child2,nc3,str,v)
        end if
! foil alP tilt
        if (name.eq.'foilalP') then
          str = '   Foil alP tilt = '
          defects%foil%alP =JSONgetDouble(child2,str,v)
        end if
! foil alS tilt
        if (name.eq.'foilalS') then
          str = '   Foil alS tilt = '
          defects%foil%alS =JSONgetDouble(child2,str,v)
        end if
! foil alR tilt
        if (name.eq.'foilalR') then
          str = '   Foil alR tilt = '
          defects%foil%alR =JSONgetDouble(child2,str,v)
        end if
! foil thickness
        if (name.eq.'foilz0') then
          str = '   Foil thickness = '
          defects%foil%z0 =JSONgetDouble(child2,str,v)
        end if
! foil shape parameters
        if (name.eq.'brx') then
          str = '   shape brx = '
          defects%foil%brx =JSONgetDouble(child2,str,v)
        end if
! foil shape parameters
        if (name.eq.'bry') then
          str = '   shape bry = '
          defects%foil%bry =JSONgetDouble(child2,str,v)
        end if
! foil shape parameters
        if (name.eq.'brxy') then
          str = '   shape brxy = '
          defects%foil%brxy =JSONgetDouble(child2,str,v)
        end if
! foil shape parameters
        if (name.eq.'cpx') then
          str = '   shape cpx = '
          defects%foil%cpx =JSONgetDouble(child2,str,v)
        end if
! foil shape parameters
        if (name.eq.'cpy') then
          str = '   shape cpy = '
          defects%foil%cpy =JSONgetDouble(child2,str,v)
        end if
! foil elastic modulus tensor  (6x6 format)
        if (name.eq.'foilelmo') then
          str = ''
          do jj=1,6
           call json_get_child(child2,jj,child3)
           call json_info(child3,vart,nc3,name)
           if (name.eq.row(jj)) defects%foil%elmo(jj,1:6) = JSONgetDoubleVector(child3,nc3,str,0)
          end do
          if (v.eq.1) then
            call WriteValue('   Elastic moduli tensor (Voigt notation)','')
            do jj=1,6
              io_real(1:6) = defects%foil%elmo(jj,1:6)
              call WriteValue('',io_real,6)
            end do
          end if
        end if
    end do nc2loop
  end do
end if
call JSON_failtest(error_cnt)
! verify that the foil normal (in real space) and q (in reciprocal space) are orthogonal
! in other words, we do a cartesian dot product...
x = CalcDot(cell,defects%foil%F,defects%foil%q,'c')
if (abs(x).gt.0.005) then
  call Message('Foil normal F must be orthogonal to q', frm = "(A)")
!  stop
end if
end subroutine JSONreadFoilData
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
jsonreadfoildata calls writevalue, emsoft_getemdatapathname, emsoft_tonativepath, json_print_error_message, json_get_child, calcdot, jsongetdouble, json_failed, jsongetdoublevector, json_info, json_failtest, message, json_parse
jsongetdouble calls writevalue, json_get
jsongetdoublevector calls writevalue, json_get
json_failtest calls json_print_error_message, json_failed
jsonreaddefectfile calls jsonreadfoildata
initializedefects calls jsonreaddefectfile