makestackingfaultECCI – Fortran Program
makestackingfaultECCI Subroutine
129 statements
Source File
public recursive subroutine makestackingfaultECCI(cell, defects, inum, DF_L, nx, ny, DF_g, dinfo)
Uses:
math
constants
files
rotations
crystal
symmetry
math
@author Marc De Graef, Carnegie Mellon University @brief compute parameters for a stacking fault in ECCI mode @details This subroutine computes the geometrical parameters for a stacking fault. It computes, among others, the coordinates of the surface intersections of the partial dislocations, and an array that indicates, for each image pixel, whether or not the corresponding integration column contains this fault; if it does not, the value in the array is set to -10000; if it does, then the value is equal to the point where the fault plane intersects with the column, measured from the top surface. In short, anything that is needed in the CalcR routine and can be computed ahead of time, is computed here. The routine also calls the makedislocation routine to create the partials. @param cell unit cell pointer @param defects defect structure @param inum @param DF_L column edge length @param nx @param ny @param DF_g @param ndl @param dinfo trigger for verbose output @date 11/05/13 MDG 1.0 new attempt to replace faulty original routine @date 11/13/13 MDG 1.1 traced error to problem with transformations in defectmodule @date 11/13/13 MDG 1.2 changed SF normal transformation for zpos array computation (to be tested) @date 12/17/13 MDG 1.3 branch from original routine to deal with different ECCI geometry @date 12/18/13 MDG 1.4 debug of stacking fault location array @date 06/09/14 MDG 2.0 added cell, SF, YD arguments @date 06/10/14 MDG 2.1 added foil argument
Arguments
Type Intent Optional Attributes Name
type(unitcell), pointer :: cell
type(defecttype), intent(inout) :: defects
integer(kind=irg), intent(in) :: inum
real(kind=sgl), intent(in) :: DF_L
integer(kind=irg), intent(in) :: nx
integer(kind=irg), intent(in) :: ny
real(kind=sgl), intent(in) :: DF_g(3)
integer(kind=irg), intent(in) :: dinfo
Calls
Called By
Source Code
makestackingfaultECCI
Source Code
recursive subroutine makestackingfaultECCI(cell,defects,inum,DF_L,nx,ny,DF_g,dinfo)
!DEC$ ATTRIBUTES DLLEXPORT :: makestackingfaultECCI
use math
use constants
use files
use rotations
use crystal
use symmetry
use math
IMPLICIT NONE
type(defecttype),INTENT(INOUT)  :: defects
type(unitcell),pointer          :: cell
real(kind=sgl),INTENT(IN)       :: DF_L
real(kind=sgl),INTENT(IN)       :: DF_g(3)
integer(kind=irg),INTENT(IN)    :: inum, nx, ny, dinfo
real(kind=sgl)                  :: fpn(3),am(4,4),midpoint(3), ex(3), ey(3),&
                                 lptopi(3),lpboti(3),tptopi(3),tpboti(3),det,A(4), xx(4), yy(4), tmp(3), &
                                 planenormal(3), rzero(3), unita(3), lun(3), tun(3), zang, zu, zz
integer(kind=irg)               :: i,j,info,ipiv,minx,maxx,miny,maxy, ndl
ndl = defects%numYdisl
! we begin by computing the geometry in the foil reference frame, which is the cartesian frame
! for zero sample tilt;  sample tilts are applied once we known the partial dislocation geometry
call TransSpace(cell,defects%SF(inum)%plane,tmp,'r','c')
call NormVec(cell,tmp,'c')
planenormal =  tmp
call CalcCross(cell, planenormal, (/ 0.0,0.0,1.0 /),  unita, 'c', 'c', 0)
call NormVec(cell,unita,'c')
fpn = planenormal
if (dinfo.eq.1) write (*,*) ' unita should have zero third component ',unita, fpn
! the fault plane goes through the point rzero in the foil top surface
rzero = (/ defects%SF(inum)%id, defects%SF(inum)%jd, sngl(defects%foil%z0)*0.5 /)
! this leads to the location of the partial dislocation intersections, and these must
! be Yoffe dislocations !!!
defects%SF(inum)%lpr = rzero + 0.5*defects%SF(inum)%sep*unita / DF_L
defects%SF(inum)%tpr = rzero - 0.5*defects%SF(inum)%sep*unita / DF_L
if (dinfo.eq.1) write (*,*) 'lpr_i = ',defects%SF(inum)%lpr(1:3)
if (dinfo.eq.1) write (*,*) 'tpr_i = ',defects%SF(inum)%tpr(1:3)
! convert line directions to the Cartesian crystal reference frame
call TransSpace(cell,defects%SF(inum)%lpu,lun,'d','c')
call TransSpace(cell,defects%SF(inum)%tpu,tun,'d','c')
! normalize both vectors
call NormVec(cell,lun,'c')
call NormVec(cell,tun,'c')
! call makeYSHdislocation for each of the partials [must be done in main program]
!  if (.not. allocated(YD)) allocate(defects%YD(3*maxdefects))
  defects%YD(ndl+1)%id = defects%SF(inum)%lpr(1)
  defects%YD(ndl+1)%jd = defects%SF(inum)%lpr(2)
  defects%YD(ndl+1)%u(1:3) = dble(defects%SF(inum)%lpu(1:3))
  defects%YD(ndl+1)%burg(1:3) = dble(defects%SF(inum)%lpb(1:3))
  defects%YD(ndl+1)%g = DF_g
  defects%YD(ndl+1)%sig = defects%SF(inum)%poisson
  defects%YD(ndl+2)%id = defects%SF(inum)%tpr(1)
  defects%YD(ndl+2)%jd = defects%SF(inum)%tpr(2)
  defects%YD(ndl+2)%u(1:3) = dble(defects%SF(inum)%tpu(1:3))
  defects%YD(ndl+2)%burg(1:3) = dble(defects%SF(inum)%tpb(1:3))
  defects%YD(ndl+2)%g = DF_g
  defects%YD(ndl+2)%sig = defects%SF(inum)%poisson
  call makeYSHdislocation(cell,defects,ndl+1,dinfo,DF_L)
  if (dinfo.eq.1) write (*,*) 'Leading Partial Position ',defects%YD(ndl+1)%id,defects%YD(ndl+1)%jd
  call makeYSHdislocation(cell,defects,ndl+2,dinfo,DF_L)
  if (dinfo.eq.1) write (*,*) 'Trailing Partial Position ',defects%YD(ndl+2)%id,defects%YD(ndl+2)%jd
! first find the length of the dislocation line inside the foil along the
! dislocation z-axis, which is the line direction; also, compute the intersection
! points of the line with the top and bottom surfaces  (all components in [nm])
zang = CalcAngle(cell, defects%YD(ndl+1)%u,defects%foil%F,'d')
zz = cos(zang)
if (abs(zz).gt.0.00001) then
  zu = abs(defects%foil%z0/zz)
else
  zu = 100000.0         ! this is when the dislocation is nearly parallel to the foil
end if
! transform the line direction to the foil reference frame
  tmp = quat_Lp( conjg(defects%foil%a_fc), dble(lun) ) / DF_L
! determine the top and bottom intersection coordinates
  defects%YD(ndl+1)%top = (/ defects%YD(ndl+1)%id, defects%YD(ndl+1)%jd, defects%foil%z0*0.5 /)
  if (zz.gt.0.0) then  ! u points to the top of the foil
    defects%YD(ndl+1)%bottom = (/ defects%YD(ndl+1)%id - tmp(1)*zu, defects%YD(ndl+1)%jd - tmp(2)*zu, -0.5D0*defects%foil%z0 /)
  else                 ! u points to the bottom of the foil
    defects%YD(ndl+1)%bottom = (/ defects%YD(ndl+1)%id + tmp(1)*zu, defects%YD(ndl+1)%jd + tmp(2)*zu, -0.5D0*defects%foil%z0 /)
  end if
! first find the length of the dislocation line inside the foil along the
! dislocation z-axis, which is the line direction; also, compute the intersection
! points of the line with the top and bottom surfaces  (all components in [nm])
zang = CalcAngle(cell, defects%YD(ndl+2)%u,defects%foil%F,'d')
zz = cos(zang)
if (abs(zz).gt.0.00001) then
  zu = abs(defects%foil%z0/zz)
else
  zu = 100000.0         ! this is when the dislocation is nearly parallel to the foil
end if
! transform the line direction to the foil reference frame
  tmp = quat_Lp( conjg(defects%foil%a_fc), dble(tun) ) / DF_L
! determine the top and bottom intersection coordinates
  defects%YD(ndl+2)%top = (/ defects%YD(ndl+2)%id, defects%YD(ndl+2)%jd, defects%foil%z0*0.5 /)
  if (zz.gt.0.0) then  ! u points to the top of the foil
    defects%YD(ndl+2)%bottom = (/ defects%YD(ndl+2)%id - tmp(1)*zu, defects%YD(ndl+2)%jd - tmp(2)*zu, -0.5D0*defects%foil%z0 /)
  else                 ! u points to the bottom of the foil
    defects%YD(ndl+2)%bottom = (/ defects%YD(ndl+2)%id + tmp(1)*zu, defects%YD(ndl+2)%jd + tmp(2)*zu, -0.5D0*defects%foil%z0 /)
  end if
! copy the top and bottom dislocation intersections
! into the corresponding variables of the SF record
defects%SF(inum)%lpbot = defects%YD(ndl+1)%bottom
defects%SF(inum)%lptop = defects%YD(ndl+1)%top
defects%SF(inum)%tpbot = defects%YD(ndl+2)%bottom
defects%SF(inum)%tptop = defects%YD(ndl+2)%top
! obviously, these four points need to lie in a single plane; at this point, we check that this is indeed the case
! by computing the volume of the tetrahedron formed by these four points; if the volume is zero, then the
! points are co-planar.  (Use LAPACK's LU-decomposition and compute the product of the diagonal elements of U)
am(1:4,1) = (/ defects%SF(inum)%lptop(1:3),1.0 /)
am(1:4,2) = (/ defects%SF(inum)%lpbot(1:3),1.0 /)
am(1:4,3) = (/ defects%SF(inum)%tptop(1:3),1.0 /)
am(1:4,4) = (/ defects%SF(inum)%tpbot(1:3),1.0 /)
call sgetrf(4,4,am,4,ipiv,info)
det = abs(am(1,1)*am(2,2)*am(3,3)*am(4,4))
if (dinfo.eq.1) write (*,*) 'determinant (should be zero) = ',det
! ok, next we need to figure out which image pixels lie on the projection of the stacking fault plane.
! We need to transform the corner points into the image reference frame !!!
lptopi = quat_Lp(defects%foil%a_fi, dble(defects%SF(inum)%lptop))
lpboti = quat_Lp(defects%foil%a_fi, dble(defects%SF(inum)%lpbot))
tptopi = quat_Lp(defects%foil%a_fi, dble(defects%SF(inum)%tptop))
tpboti = quat_Lp(defects%foil%a_fi, dble(defects%SF(inum)%tpbot))
if (dinfo.eq.1) then
  write (*,*) 'SF parameters :'
  write (*,*) lptopi,' <> ',lpboti
  write (*,*) tptopi,' <> ',tpboti
end if
! define the array that will contain the zpos values
allocate(defects%SF(inum)%zpos(nx,ny))
defects%SF(inum)%zpos = -10000.0    ! set all points to be outside the projected SF
! first determine the smaller box
minx = nint(min(lptopi(1),lpboti(1),tptopi(1),tpboti(1))) -2
maxx = nint(max(lptopi(1),lpboti(1),tptopi(1),tpboti(1))) +2
miny = nint(min(lptopi(2),lpboti(2),tptopi(2),tpboti(2))) -2
maxy = nint(max(lptopi(2),lpboti(2),tptopi(2),tpboti(2))) +2
! the fault edges may fall outside of the viewing frame (origin at the center !!!)
if (minx.lt.(-nx/2+1)) minx=-nx/2+1
if (maxx.gt.nx/2) maxx=nx/2
if (miny.lt.(-ny/2+1)) miny=-ny/2+1
if (maxy.gt.ny/2) maxy=ny/2
if (dinfo.eq.1) write (*,*) 'Integer fault box = ',minx,maxx,miny,maxy
! get the equation of the stacking fault plane in the image reference frame
! first the unit plane normal in image space
! we'll take two vectors: ex = from ltop to ttop; ey = from ltop to lbot
ex = tptopi - lptopi
ey = lpboti - lptopi
call NormVec(cell,ex,'c')
call NormVec(cell,ey,'c')
call CalcCross(cell,ex,ey,fpn,'c','c',0)
A(1:3) = fpn ! quat_LPstar(conjg(foil%a_fi), dble(fpn(1:3)))
midpoint = 0.25*(lptopi+lpboti+tptopi+tpboti) ! quat_LPstar(conjg(foil%a_fi), dble(0.25*(lptopi+lpboti+tptopi+tpboti)))
A(4) = sum(A(1:3)*midpoint)
if (dinfo.eq.1) write (*,*) 'fault plane parameters : ',A, midpoint
! rank the corner points so that the polygon is convex
! call rank_points(tpboti(1:2),lpboti(1:2),lptopi(1:2),tptopi(1:2),xx,yy)
xx = (/ lptopi(1), tptopi(1), tpboti(1),lpboti(1) /)
yy = (/ lptopi(2), tptopi(2), tpboti(2),lpboti(2) /)
! for all of the points inside this box:
do i=minx,maxx
  do j=miny,maxy
    if (point_inside_polygon( float(i), float(j), xx, yy ).gt.0) then
! the point lies inside the projected region,
! so we need the depth of the SF plane at this position, taking into account the
! proper coordinate transformation (depth must be expressed in image reference frame)
        defects%SF(inum)%zpos(i+nx/2,j+ny/2) = ( A(4) - A(1)*float(i) - A(2)*float(j) )/A(3)
    end if
  end do
end do
if (dinfo.eq.1) write (*,*) 'fault plane pixels determined'
! let's also make sure that the SF displacement vector is translated to the
! cartesian reference frame, so that it can be used directly by the CalcR routine
defects%SF(inum)%lpbc = matmul(cell%dsm,defects%SF(inum)%Rdisp)
! that should do it for the stacking fault...  The rest
! takes place in the CalcR routine.
end subroutine makestackingfaultECCI
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
makestackingfaultecci calls float, transspace, point_inside_polygon, sgetrf, calcangle, sngl, quat_lp, makeyshdislocation, calccross, normvec
makeyshdislocation calls transspace, calcangle, calccross, normvec, om2qu, calcdot, calclength, fatalerror, writevalue
init_stacking_fault_data calls makestackingfaultecci
initializedefects calls init_stacking_fault_data