makedislocation – Fortran Program
makedislocation Subroutine
219 statements
Source File
public recursive subroutine makedislocation(cell, defects, inum, dinfo, DF_L)
Uses:
math
constants
crystal
math
io
symmetry
rotations
@author Marc De Graef, Carnegie Mellon University @brief Compute the dismat displacement matrix for a given dislocation @details This subroutine computes the matrix dismat that describes the displacement field of a dislocation. The routine needs the elastic moduli tensor, the transformation matrix between the crystal and dislocation reference frames, and the dislocation Burgers vector. The routine computes the arrays dismat and pa, which should be used as follows:
R_k = 2.0real([ sum_a=1^3 (dismat(k,a)log(Z_a)) ]),
with Z_a = x_1 + pa(a)*x_2
[see CalcR subroutine for more information]
We must also make sure that the x=0 plane of the defect reference frame contains the incident beam direction, to avoid getting stacking-fault fringes in the wrong plane... Actual stacking faults are added in using a different module (stacking_fault.f90).
@param cell unit cell pointer @param defects defect structure @param inum @param dinfo @param DF_L column width @date 1/ 5/99 MDG 1.0 original @date 5/19/01 MDG 2.0 f90 version @date 11/27/01 MDG 2.1 added kind support @date 06/04/13 MDG 3.0 rewrite @date 10/30/13 MDG 3.1 debug of all rotation parts @date 06/09/14 MDG 4.0 added cell, defects arguments @date 06/10/14 MDG 4.1 added foil as argument @date 11/21/15 MDG 4.2 moved foil into defects structure
Arguments
Type Intent Optional Attributes Name
type(unitcell), pointer :: cell
type(defecttype), intent(inout) :: defects
integer(kind=irg), intent(in) :: inum
integer(kind=irg), intent(in) :: dinfo
real(kind=sgl), intent(in) :: DF_L
Calls
Called By
Source Code
makedislocation
Source Code
recursive subroutine makedislocation(cell,defects,inum,dinfo,DF_L)
!DEC$ ATTRIBUTES DLLEXPORT :: makedislocation
use math
use constants
use crystal
use math
use io
use symmetry
use rotations
IMPLICIT NONE
type(unitcell),pointer                  :: cell
type(defecttype),INTENT(INOUT)          :: defects
integer(kind=irg),INTENT(IN)            :: inum
integer(kind=irg),INTENT(IN)            :: dinfo
real(kind=sgl),INTENT(IN)               :: DF_L
type(foiltype)                          :: foil
real(kind=dbl)                          :: zz,zang,zmin
real(kind=sgl)                          :: ec(6,6),lec(6,6)
real(kind=dbl)                          :: a_dc(3,3),tmp(3),ex(3),ey(3)
real(kind=dbl)                          :: Bij(3,3),Hij(3,3)
complex(kind=dbl)                       :: a(0:6),b(0:6),c(0:6),d(0:6),e(0:6),ff(0:6),tt(5,0:6),s(0:6),roots(6), &
                                           zero,pasq(3),mat(3,3),aka(3,3),Lia(3,3),Mai(3,3),v(3),pas
integer(kind=irg)                       :: i,j,k,l,imin,ind(3),jnd(3)
foil = defects%foil
! convert line direction and g-vector to the Cartesian crystal reference frame
call TransSpace(cell,defects%DL(inum)%u,defects%DL(inum)%un,'d','c')
call TransSpace(cell,defects%DL(inum)%g,defects%DL(inum)%gn,'r','c')
! normalize both vectors
call NormVec(cell,defects%DL(inum)%un,'c')
call NormVec(cell,defects%DL(inum)%gn,'c')
! first find the length of the dislocation line inside the foil along the
! dislocation z-axis, which is the line direction; also, compute the intersection
! points of the line with the top and bottom surfaces  (all components in [nm])
zang = CalcAngle(cell,defects%DL(inum)%u,dble(foil%F),'d')
zz = cos(zang)
if (abs(zz).gt.0.00001) then
  defects%DL(inum)%zu = 0.5*foil%z0/zz
else
  defects%DL(inum)%zu = 100000.0         ! this is when the dislocation is nearly parallel to the foil
end if
! transform the line direction to the foil reference frame
tmp = quat_Lp(foil%a_fc, dble(defects%DL(inum)%un)) / DF_L
if (dinfo.eq.1) then
  write (*,*) 'transformed line direction ', tmp, zang, zz
end if
! determine the top and bottom intersection coordinates
if (zz.gt.0.0) then  ! u points to the top of the foil
    defects%DL(inum)%top = (/ defects%DL(inum)%id + tmp(1)*defects%DL(inum)%zu, defects%DL(inum)%jd + &
        tmp(2)*defects%DL(inum)%zu, 0.5D0*foil%z0 /)
    defects%DL(inum)%bottom = (/ defects%DL(inum)%id - tmp(1)*defects%DL(inum)%zu, defects%DL(inum)%jd - &
        tmp(2)*defects%DL(inum)%zu, -0.5D0*foil%z0 /)
else                 ! u points to the bottom of the foil
    defects%DL(inum)%top = (/ defects%DL(inum)%id - tmp(1)*defects%DL(inum)%zu, defects%DL(inum)%jd - &
        tmp(2)*defects%DL(inum)%zu, -0.5D0*foil%z0 /)
    defects%DL(inum)%bottom = (/ defects%DL(inum)%id + tmp(1)*defects%DL(inum)%zu, defects%DL(inum)%jd + &
        tmp(2)*defects%DL(inum)%zu, 0.5D0*foil%z0 /)
end if
if (dinfo.eq.1) then
  write (*,*) defects%DL(inum)%id,defects%DL(inum)%jd
  write (*,*) 'dislocation top intersection at ',defects%DL(inum)%top
  write (*,*) 'dislocation bottom intersection at ',defects%DL(inum)%bottom
end if
! a_dc (crystal to defect)  matrix corrected on 11/29/10 to put defect x-axis in the plane of u and B
if (dinfo.eq.1) then
  write (*,*) 'cartesian quantities'
  write (*,*) 'unit line direction = ',defects%DL(inum)%un
  write (*,*) 'unit beam direction = ',foil%Bn
end if
! transform beam direction (currently in foil frame) to cartesian
tmp = quat_Lp(conjg(foil%a_fc), dble(foil%Bn))
!tmp = quat_rotate_vector(conjg(foil%a_fc), (/ 0.0D0, 0.0D0, -1.0D0/))
call NormVec(cell,tmp,'c')
! the defect z axis is the line direction and x is in the plane of u and B to avoid the intrinsic discontinuity (cut plane)
a_dc(3,1:3) = defects%DL(inum)%un(1:3)
call CalcCross(cell,dble(defects%DL(inum)%un),tmp,ex,'c','c',0)
call NormVec(cell,ex,'c')
a_dc(1,1:3) = ex(1:3)
call CalcCross(cell,dble(defects%DL(inum)%un),ex,ey,'c','c',0)
call NormVec(cell,ey,'c')
a_dc(2,1:3) = ey(1:3)
defects%DL(inum)%a_dc = om2qu(a_dc)
if (dinfo.eq.1) then
  call PrintMatrixd('a_dc',a_dc)
end if
! a_di (image to defect)
defects%DL(inum)%a_di = quat_mult(defects%DL(inum)%a_dc, conjg(foil%a_ic))
defects%DL(inum)%a_id = conjg(defects%DL(inum)%a_di)
if (dinfo.eq.1) then
  call print_orientation_d(init_orientation_d(defects%DL(inum)%a_di,'qu'),'om','a_di:     ')
  call print_orientation_d(init_orientation_d(defects%DL(inum)%a_id,'qu'),'om','a_id:     ')
end if
! finally, get the foil to defect transformation (used in defect module)
defects%DL(inum)%a_df = quat_mult(defects%DL(inum)%a_di, conjg(foil%a_fi))
! Burgers vector (in the defect reference frame !!!)
! first transform Burgers vector to crystal cartesian reference frame
call TransSpace(cell,dble(defects%DL(inum)%burg),tmp,'d','c')
! then convert this to the defect reference frame
defects%DL(inum)%burgd(1:3) = quat_Lp(defects%DL(inum)%a_dc,dble(tmp))
if (dinfo.eq.1) then
  write (*,*) 'rotated burgers vector  = ', defects%DL(inum)%burgd(1:3)
end if
! transform the elastic moduli
lec = foil%elmo
! transform lec to defect reference frame
a_dc = qu2om(defects%DL(inum)%a_dc)
call TransFourthRankTensor(a_dc,lec,ec)
if (dinfo.eq.1)  then
  write (*,*) 'Elasticity tensor in defect reference frame'
  do i=1,6
    write (*,"(6(F8.4,2x))") (ec(i,j),j=1,6)
  end do
  write (*,*) '----'
end if
! next, create the sextic polynomial
zero = cmplx(0.0,0.0,dbl)
a=zero; b=zero; c=zero; d=zero; e=zero; ff=zero
a(0:2) = (/ cmplx(ec(1,1),0.0,dbl), cmplx(ec(1,6)*2.0,0.0,dbl),     cmplx(ec(6,6),0.0,dbl) /)
b(0:2) = (/ cmplx(ec(6,6),0.0,dbl), cmplx(ec(2,6)*2.0,0.0,dbl),     cmplx(ec(2,2),0.0,dbl) /)
c(0:2) = (/ cmplx(ec(5,5),0.0,dbl), cmplx(ec(4,5)*2.0,0.0,dbl),     cmplx(ec(4,4),0.0,dbl) /)
d(0:2) = (/ cmplx(ec(5,6),0.0,dbl), cmplx(ec(4,6)+ec(2,5),0.0,dbl), cmplx(ec(2,4),0.0,dbl) /)
e(0:2) = (/ cmplx(ec(1,5),0.0,dbl), cmplx(ec(1,4)+ec(5,6),0.0,dbl), cmplx(ec(4,6),0.0,dbl) /)
ff(0:2) = (/ cmplx(ec(1,6),0.0,dbl), cmplx(ec(1,2)+ec(6,6),0.0,dbl), cmplx(ec(2,6),0.0,dbl) /)
tt = zero
s = zero
! matrix elements
do j=0,6
 do i=0,j
  tt(1,j) = tt(1,j) + a(j-i)*b(i)
  tt(2,j) = tt(2,j) + d(j-i)*e(i)
  tt(3,j) = tt(3,j) + a(j-i)*d(i)
  tt(4,j) = tt(4,j) + b(j-i)*e(i)
  tt(5,j) = tt(5,j) + c(j-i)*ff(i)
 end do
end do
! determinant leading to the sextic equation
do j=0,6
 do i=0,j
  s(j) = s(j) + tt(1,j-i)*c(i) + 2.0*tt(2,j-i)*ff(i) - tt(3,j-i)*d(i) - tt(4,j-i)*e(i) - tt(5,j-i)*ff(i)
 end do
end do
! get the complex root pairs
call zroots(s,roots)
! then, solve the equation for the vector A_k using the roots with positive imaginary part.
k=1
do j=1,6
  if (aimag(roots(j)).gt.0.0) then
    defects%DL(inum)%pa(k) = roots(j)
    k=k+1
  end if
end do
! renumber them to avoid the symmetry degeneracy (see page 328 Head et al.)
v(1:3) = ec(5,5) + 2.0*defects%DL(inum)%pa(1:3)*ec(4,5) + ec(4,4)*defects%DL(inum)%pa(1:3)**2
zmin = 100.0
imin = 0
! where is the smallest value ?
do i=1,3
  if (abs(v(i)).lt.zmin) then
    imin=i
    zmin = abs(v(i))
  end if
end do
! is the 3rd one the smallest ? if not, then swap with the current 3rd one.
if (imin.ne.3) then
  pas = defects%DL(inum)%pa(imin)
  defects%DL(inum)%pa(imin)=defects%DL(inum)%pa(3)
  defects%DL(inum)%pa(3)=pas
end if
  pas = defects%DL(inum)%pa(1)
  defects%DL(inum)%pa(1)=defects%DL(inum)%pa(2)
  defects%DL(inum)%pa(2)=pas
! eliminate really small numbers
do i=1,3
  if (abs(aimag(defects%DL(inum)%pa(i))).lt.1.0e-8)  defects%DL(inum)%pa(i)=cmplx(real(defects%DL(inum)%pa(i)),0.0,dbl)
  if (abs(real(defects%DL(inum)%pa(i))).lt.1.0e-8)   defects%DL(inum)%pa(i)=cmplx(0.0,aimag(defects%DL(inum)%pa(i)),dbl)
end do
if (dinfo.eq.1) then
  write (*,*) ' sextic roots'
  do i=1,3
    write (*,*) defects%DL(inum)%pa(i)
  end do
  write (*,*) '---'
end if
!  compute the A_ka vectors (see description on page 328 of Head et al.)
pasq = defects%DL(inum)%pa**2
if (dinfo.eq.1) write (*,*) 'Aka vectors'
do k=1,3
  mat = zero
  mat(1,1) = ec(1,1)+2.D0*defects%DL(inum)%pa(k)*ec(1,6)+ec(6,6)*pasq(k)
  mat(2,2) = ec(6,6)+2.D0*defects%DL(inum)%pa(k)*ec(2,6)+ec(2,2)*pasq(k)
  mat(3,3) = ec(5,5)+2.D0*defects%DL(inum)%pa(k)*ec(4,5)+ec(4,4)*pasq(k)
  mat(2,3) = ec(5,6)+defects%DL(inum)%pa(k)*(ec(4,6)+ec(2,5))+ec(2,4)*pasq(k)
  mat(1,3) = ec(1,5)+defects%DL(inum)%pa(k)*(ec(1,4)+ec(5,6))+ec(4,6)*pasq(k)
  mat(1,2) = ec(1,6)+defects%DL(inum)%pa(k)*(ec(1,2)+ec(6,6))+ec(2,6)*pasq(k)
  if (k.eq.1) then
    aka(1,1) = mat(2,2)*mat(3,3)-mat(2,3)*mat(2,3)
    aka(1,2) = mat(1,3)*mat(2,3)-mat(1,2)*mat(3,3)
    aka(1,3) = mat(1,2)*mat(2,3)-mat(1,3)*mat(2,2)
  end if
  if (k.eq.2) then
    aka(2,1) = mat(1,3)*mat(2,3)-mat(1,2)*mat(3,3)
    aka(2,2) = mat(1,1)*mat(3,3)-mat(1,3)*mat(1,3)
    aka(2,3) = mat(1,3)*mat(1,2)-mat(1,1)*mat(2,3)
  end if
  if (k.eq.3) then
    aka(3,1) = mat(1,2)*mat(2,3)-mat(1,3)*mat(2,2)
    aka(3,2) = mat(1,3)*mat(1,2)-mat(1,1)*mat(2,3)
    aka(3,3) = mat(1,1)*mat(2,2)-mat(1,2)*mat(1,2)
  end if
  if (dinfo.eq.1) write (*,*) k,(aka(k,j),j=1,3)
end do
aka = transpose(aka)
! next, create the L_ialpha matrix
ind = (/ 6, 2, 4 /)
jnd = (/ 1, 6, 5 /)
Lia = zero
do i=1,3
 do j=1,3
  do k=1,3
   Lia(i,j) = Lia(i,j)+(ec(ind(i),jnd(k))+defects%DL(inum)%pa(j)*ec(ind(i),ind(k)))*aka(k,j)
  end do
 end do
end do
if (dinfo.eq.1)  call PrintMatrixcd('Lia ',Lia)
! and invert it
call cInvert(Lia,Mai)
if (dinfo.eq.1)  call PrintMatrixcd('Mai ',Mai)
! compute Bij (real matrix)
Bij = 0.D0
do i=1,3
 do j=1,3
  do k=1,3
   Bij(i,j) = Bij(i,j) - aimag(aka(i,k))*real(Mai(k,j)) - real(aka(i,k))*aimag(Mai(k,j))
  end do
 end do
end do
if (dinfo.eq.1)  call PrintMatrixd('Bij ',Bij)
! and invert to get Hij
call mInvert(Bij,Hij,.FALSE.)
if (dinfo.eq.1) call PrintMatrixd('Hij ',Hij)
! compute matrix (this is what actually gets to be used for the
! displacement field); needs to know the Burgers vector.
defects%DL(inum)%dismat = zero
do k=1,3
 do l=1,3
   do i=1,3
    do j=1,3
     defects%DL(inum)%dismat(k,l) = defects%DL(inum)%dismat(k,l) + defects%DL(inum)%burgd(i)*Hij(j,i)*Mai(l,j)*aka(k,l)
    end do
   end do
 end do
end do
! scale by 1/4pi
defects%DL(inum)%dismat = defects%DL(inum)%dismat*0.25D0/cPi
if (dinfo.eq.1)  call PrintMatrixcd('dismat',defects%DL(inum)%dismat)
! and return to calling routine
end subroutine makedislocation
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
makedislocation calls printmatrixcd, om2qu, transspace, print_orientation_d, minvert, zroots, quat_mult, calccross, cinvert, init_orientation_d, transfourthranktensor, qu2om, quat_lp, printmatrixd, calcangle, normvec
init_dislocation_data calls makedislocation
makestackingfault calls makedislocation
initializedefects calls init_dislocation_data, init_stacking_fault_data
init_stacking_fault_data calls makestackingfault