makeYSHdislocation – Fortran Program
makeYSHdislocation Subroutine
57 statements
Source File
public recursive subroutine makeYSHdislocation(i, dinfo, L)
Uses:
local
foilmodule
constants
crystal
Arguments
Type Intent Optional Attributes Name
integer(kind=irg) :: i
integer(kind=irg) :: dinfo
real(kind=sgl) :: L
Calls
Called By
Source Code
makeYSHdislocation
Source Code
recursive subroutine makeYSHdislocation(i,dinfo, L)
!DEC$ ATTRIBUTES DLLEXPORT :: makeYSHdislocation
!
! this routine pre-computes a number of parameters related to the
! geometry of the Yoffe&Shaibani&Hazzledine (YSH) surface-relaxed dislocation in an elastically
! isotropic matrix.  These parameters are then used in the CalcR routine.
!
! We implemented the YSH expressions instead of Yoffe's
! since the former are more easily handled for numerical computations.
! SH have redefined the x-y-z reference frame used by Yoffe to fall along
! the dislocation line itself.  As a result, the Burgers vector must be decomposed
! into a screw component and two edge components, one in the plane of the
! discontinuity, the other normal to that plane (which is by definition the x-axis).
! Check the SH paper for more details.
use local
use foilmodule
use constants
use crystal
IMPLICIT NONE
real(kind=sgl)  :: alpha, beta, L, tu(3), tx(3), ty(3), te(3), tb(3), bl
integer(kind=irg) :: i,dinfo
! first, determine the alpha angle between the
! negative z-axis, which is really the negative foil normal, and the line direction
! (make sure to reduce the angle to [0,90] interval).
alpha = CalcAngle(-foil%F,YD(i)%u,'d')*180.0/cPi
if (alpha.gt.90.0) then
  alpha = 180.0-alpha
  YD(i)%u = -YD(i)%u   ! the u-direction should point down into the foil
end if
write (*,*) 'Foil normal = ',foil%F
write (*,*) 'line direction = ',YD(i)%u
write (*,*) '  --> alpha angle = ',alpha
alpha = alpha*cPi/180.0
call TransSpace(YD(i)%u,tu,'d','c')
call NormVec(tu,'c')
call TransSpace(foil%F,ty,'d','c')
call NormVec(ty,'c')
call CalcCross(tu,ty,tx,'c','c',0)       ! x = u x F
call NormVec(tx,'c')
call CalcCross(tx,tu,te,'c','c',0)             ! e = x x u
call NormVec(te,'c')
call CalcCross(ty,tx,ty,'c','c',0)
call NormVec(ty,'c')
bl = CalcLength(YD(i)%burg,'d')
write (*,*) ' tx = ',tx
write (*,*) ' te = ',te
write (*,*) ' tu = ',tu
write (*,*) ' ty = ',ty
write (*,*) ' bl = ',bl
call TransSpace(YD(i)%burg,tb,'d','c')
call NormVec(tb,'c')
YD(i)%bx = bl * CalcDot(tb,tx,'c')   ! edge component normal to cut plane
YD(i)%be = bl * CalcDot(tb,te,'c')   ! edge component in cut plane
YD(i)%bs = bl * CalcDot(tb,tu,'c')  ! screw component
write (*,*) 'Burgers vector components (bx,be,bs) ',YD(i)%bx,YD(i)%be,YD(i)%bs
! we will also need to know the rotation matrix between the dislocation reference frame
! and the foil reference frame, so that we can transform the foil coordinates to defect
! coordinates...  We need the angle beta between the defect x axis (tx) and the foil x axis,
! which is the first column of the foil%a_fc matrix ...
ty(1:3) = foil%a_fc(1:3,1)
write (*,*) ' tx = ',tx
YD(i)%beta = CalcAngle(tx,ty,'d')
write (*,*) ' ty = ',ty
write (*,*) ' beta = ',YD(i)%beta
beta = YD(i)%beta
YD(i)%a_di(1,1:3) = (/ cos(beta), -sin(beta), 0.0 /)
YD(i)%a_di(2,1:3) = (/ sin(beta), cos(beta), 0.0 /)
YD(i)%a_di(3,1:3) = (/ 0.0, 0.0, 1.0 /)
YD(i)%a_id = transpose(YD(i)%a_di)
write (*,*) YD(i)%a_di
! finally some geometrical parameters needed for the displacement field computation...
YD(i)%alpha =  alpha
YD(i)%ca = cos(alpha)
YD(i)%sa = sin(alpha)
YD(i)%ta = tan(alpha)
YD(i)%cota = 1.0/YD(i)%ta
write (*,*) 'angulars = ',cos(alpha),sin(alpha),tan(alpha)
! that's it! the rest is handled in the CalcR routine.
end subroutine makeYSHdislocation
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
makeyshdislocation calls normvec, calclength, calcangle, calcdot, calccross, transspace
read_ysh_dislocation_data calls makeyshdislocation
dispfield calls read_ysh_dislocation_data