PoVRay_initFZ4 – Fortran Program
PoVRay_initFZ4 Subroutine
116 statements
Source File
public recursive subroutine PoVRay_initFZ4(dunit, rmode)
@author Marc De Graef, Carnegie Mellon University @brief initialize the PoVRay output for rotational group 4 @param dunit output unit number @param rmode 1(cubochoric)|2(homochoric)|3(stereographic)|4(Rodrigues) @date 09/09/16 MDG 1.0 original
Arguments
Type Intent Optional Attributes Name
integer(kind=irg), intent(in) :: dunit
integer(kind=irg), intent(in) :: rmode
Calls
Source Code
PoVRay_initFZ4
Source Code
recursive subroutine PoVRay_initFZ4(dunit, rmode)
!DEC$ ATTRIBUTES DLLEXPORT :: PoVRay_initFZ4
IMPLICIT NONE
integer(kind=irg),INTENT(IN)          :: dunit
integer(kind=irg),INTENT(IN)          :: rmode
real(kind=dbl)          :: eul(3), axang(4), rv(3), qu(4), h(3), rmax, dx, r, xmax, x, y, z, ho(3), cu(3), zsmall, &
                           eyepos(3), ac, dpos(104), tmp
real(kind=dbl)          :: euld(3), om(3,3), ro1(4), ro2(4), culast(3), holast(3), ro(4), rolast(4), splast(3), sp(3), xx
type(orientationtype)   :: ot
type(orientationtyped)  :: otd
integer(kind=irg)       :: i,j,k, icnt, imax, nt, ns, h_edge(2,52)
! the parameter a represents infinity as tan(178/2)
real(kind=dbl)          :: a = 57.289922125538D0, b = 1.0D0, c = 1.0D0, cpos(3,104), dt = 114.57984425107713D0, &
                           ds = 2.0D0, d = 1.7320508075688772D0, dd, zz = 0.D0, oo = 1.D0, dtor =  0.017453292D0
! define the coordinates of the tetragonal C4 (4) FZ in Rodrigues Space
do i=-6,6
  if (abs(i).ne.6) then
    cpos(1:3, 7+i) = (/ -a, dtan(dble(i)*30.D0*dtor*0.5D0) ,  c /)
  else
    cpos(1:3, 7+i) = (/ -a, a ,  c /)
    if (i.lt.0) cpos(2,7+i) = -cpos(2,7+i)
  end if
end do
do i=1,13
  cpos(1:3,13+i) = cpos(1:3,i)
  cpos(1,13+i) = -cpos(1,13+i)
end do
do i=1,26
  cpos(1:3,26+i) = cpos(1:3,i)
  tmp = cpos(1,26+i)
  cpos(1,26+i) = cpos(2,26+i)
  cpos(2,26+i) = tmp
end do
do i=1,52
  cpos(1:3,52+i) = cpos(1:3,i)
  cpos(3,52+i) = -cpos(3,52+i)
end do
! and normalize
do i=1,104
  dpos(i) = dsqrt(sum(cpos(1:3,i)*cpos(1:3,i)))
end do
ns = 200
dx = dt/float(ns-1)
! define the connectivity of all the edges
do i=1,13
  h_edge(1:2,i)    = (/    i, 13+i /)
  h_edge(1:2,13+i) = (/ 26+i, 39+i /)
  h_edge(1:2,26+i) = (/ 52+i, 65+i /)
  h_edge(1:2,39+i) = (/ 78+i, 91+i /)
end do
! first add the reference frame and any necessary wireframe diagrams
if (rmode.eq.1) then
  ac = 0.5D0 * LPs%ap
  call PoVRay_addReferenceFrame(dunit, ac)
  call PoVRay_addCubochoricCube(dunit)
end if
if (rmode.eq.2) then
  ac = 1.33067D0
  call PoVRay_addReferenceFrame(dunit, ac)
  call PoVRay_addWireFrameSphere(dunit, ac)
end if
if (rmode.eq.3) then
  ac = 1.0D0
  call PoVRay_addReferenceFrame(dunit, ac)
  call PoVRay_addWireFrameSphere(dunit, ac)
end if
if (rmode.eq.4) then
  ac = 1.0D0
  call PoVRay_addReferenceFrame(dunit, ac)
end if
if ((rmode.eq.1).or.(rmode.eq.2)) then
! create the top and bottom planes first
 dx = 1.D0/dble(ns)
 do i=1,52
  ro1(1:3) = cpos(1:3,h_edge(1,i))/dpos(i)
  ro1(4) = dpos(i)
  ro2(1:3) = cpos(1:3,h_edge(2,i))/dpos(i)
  ro2(4) = dpos(i)
  culast = ro2cu(ro1)
  holast = ro2ho(ro1)
  do j=1,ns+1
    ro(1:3) = dpos(i)*ro1(1:3) + dpos(i)*(ro2(1:3) - ro1(1:3)) * j * dx
    xx = dsqrt( sum (ro(1:3)**2) )
    ro(1:3) = ro(1:3)/xx
    ro(4) = xx
    cu = ro2cu(ro)
    ho = ro2ho(ro)
! and create a cylinder with these points
    if (rmode.eq.1) then
      call PoVRay_addCylinder(dunit, culast(1:3),cu(1:3),0.005D0,(/ 0.0, 0.0, 1.0 /))
    else
      call PoVRay_addCylinder(dunit, holast(1:3),ho(1:3),0.005D0,(/ 0.0, 0.0, 1.0 /))
    end if
    culast = cu
    holast = ho
  end do
 end do
end if
if ((rmode.eq.3).or.(rmode.eq.4)) then
! create the square edges first
 dx = 1.D0/dble(ns)
 do i=1,52
  ro1(1:3) = cpos(1:3,h_edge(1,i))/dpos(i)
  ro1(4) = dpos(i)
  ro2(1:3) = cpos(1:3,h_edge(2,i))/dpos(i)
  ro2(4) = dpos(i)
  rolast = ro1
  qu = ro2qu(ro1)
  splast(1:3) = qu(2:4)/ (1.D0 + qu(1))
  do j=1,ns+1
    ro(1:3) = dpos(i)*ro1(1:3) + dpos(i)*(ro2(1:3) - ro1(1:3)) * j * dx
    xx = dsqrt( sum (ro(1:3)**2) )
    ro(1:3) = ro(1:3)/xx
    ro(4) = xx
    qu = ro2qu(ro)
    sp(1:3) = qu(2:4)/ (1.D0 + qu(1))
! and create a cylinder with these points
    if (rmode.eq.3) then
       call PoVRay_addCylinder(dunit, splast(1:3),sp(1:3),0.005D0,(/ 0.0, 0.0, 1.0 /))
    else
       call PoVRay_addCylinder(dunit, rolast(1:3)*rolast(4),ro(1:3)*ro(4),0.005D0,(/ 0.0, 0.0, 1.0 /))
    end if
    rolast = ro
    splast = sp
  end do
 end do
end if
end subroutine PoVRay_initFZ4
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
povray_initfz4 calls float, ro2qu, povray_addcylinder, povray_addreferenceframe, povray_addwireframesphere, povray_addcubochoriccube, ro2cu, ro2ho, dtan
povray_addcubochoriccube calls povray_addcylinder