PoVRay_drawFZ – Fortran Program
PoVRay_drawFZ Subroutine
471 statements
Source File
public recursive subroutine PoVRay_drawFZ(dunit, rmode, cylr, FZtype, FZorder, MFZ)
@author Marc De Graef, Carnegie Mellon University @brief initialize the PoVRay output for any rotation group @details This routine draws the outline of either the Rodrigues Fundamental zone, or the Mackenzie Fundamental Zone (if MFZ is set and true). @param dunit output unit number @param rmode 1(cubochoric)|2(homochoric)|3(stereographic)|4(Rodrigues)|5(Euler) @param cylr cylinder radius @param FZtype Fundamental zone type @param FZorder order of the FZ point group @param MFZ (optional) Mackenzie FZ instead of regular FZ @date 09/10/16 MDG 1.0 original @date 11/23/16 MDG 1.1 added Euler representation
Arguments
Type Intent Optional Attributes Name
integer(kind=irg), intent(in) :: dunit
integer(kind=irg), intent(in) :: rmode
real(kind=dbl), intent(in) :: cylr
integer(kind=irg), intent(in) :: FZtype
integer(kind=irg), intent(in) :: FZorder
logical, intent(in), optional :: MFZ
Calls
Source Code
PoVRay_drawFZ
Source Code
recursive subroutine PoVRay_drawFZ(dunit, rmode, cylr, FZtype, FZorder, MFZ)
!DEC$ ATTRIBUTES DLLEXPORT :: PoVRay_drawFZ
IMPLICIT NONE
integer(kind=irg),INTENT(IN)          :: dunit
integer(kind=irg),INTENT(IN)          :: rmode
real(kind=dbl),INTENT(IN)             :: cylr
integer(kind=irg),INTENT(IN)          :: FZtype
integer(kind=irg),INTENT(IN)          :: FZorder
logical,OPTIONAL,INTENT(IN)           :: MFZ
real(kind=dbl)          :: eul(3), axang(4), rv(3), qu(4), h(3), rmax, dx, r, xmax, x, y, z, ho(3), cu(3), zsmall, &
                           eyepos(3), ac, sh(3), ron(4)
real(kind=dbl)          :: euld(3), om(3,3), ro1(4), ro2(4), culast(3), holast(3), ro(4), rolast(4), splast(3), sp(3), &
                           eu(3), eulast(3), xx
type(orientationtype)   :: ot
type(orientationtyped)  :: otd
integer(kind=irg),allocatable :: s_edge(:,:), t_edge(:,:)
real(kind=dbl),allocatable    :: cpos(:,:)
logical                 :: doMFZ, twostep
integer(kind=irg)       :: i,j,k, icnt, imax, nt, ns, dims(3)
real(kind=dbl)          :: d, dd, tpi, hpi
tpi = 2.D0 * cPi
hpi = 0.5D0 * cPi
doMFZ = .FALSE.
if(present(MFZ)) doMFZ = .TRUE.
write (*,*) 'inside PoVRay_drawFZ; MFZ = ', doMFZ, dunit, rmode, cylr, FZtype, FZorder
if (FZtype.eq.2) then
    if (FZorder.eq.6) then
    if (doMFZ) then
      twostep = .FALSE.
      dims = (/ 8, 12, 1 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ622(dims, cpos, s_edge, t_edge, ns, d, nt, MFZ)
    else
      twostep = .TRUE.
      dims = (/ 24, 24, 12 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ622(dims, cpos, s_edge, t_edge, ns, d, nt)
    end if
  end if
  if (FZorder.eq.4) then
    if (doMFZ) then
      twostep = .FALSE.
      dims = (/ 8, 12, 1 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ422(dims, cpos, s_edge, t_edge, ns, d, nt, MFZ)
    else
      twostep = .TRUE.
      dims = (/ 16, 16, 8 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ422(dims, cpos, s_edge, t_edge, ns, d, nt)
    end if
  end if
  if (FZorder.eq.3) then
    if (doMFZ) then
      twostep = .FALSE.
      dims = (/ 6, 9, 1 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ32(dims, cpos, s_edge, t_edge, ns, d, nt, MFZ)
    else
      twostep = .TRUE.
      dims = (/ 12, 12, 6 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ32(dims, cpos, s_edge, t_edge, ns, d, nt)
    end if
  end if
  if (FZorder.eq.2) then
    if (doMFZ) then
      twostep = .FALSE.
      dims = (/ 8, 12, 1 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ222(dims, cpos, s_edge, t_edge, ns, d, nt, MFZ)
    else
      twostep = .TRUE.
      dims = (/ 8, 8, 4 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ222(dims, cpos, s_edge, t_edge, ns, d, nt)
    end if
  end if
end if
if (FZtype.eq.3) then
! rotational group 23
    if (doMFZ) then
      twostep = .FALSE.
      dims = (/ 4, 6, 1 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ23(dims, cpos, s_edge, t_edge, ns, d, nt, MFZ)
    else
      twostep = .FALSE.
      dims = (/ 6, 12, 1 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ23(dims, cpos, s_edge, t_edge, ns, d, nt)
    end if
end if
if (FZtype.eq.4) then
! rotational group 432
    if (doMFZ) then
      twostep = .FALSE.
      dims = (/ 6, 9, 1 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ432(dims, cpos, s_edge, t_edge, ns, d, nt, MFZ)
    else
      twostep = .TRUE.
      dims = (/ 24, 12, 24 /)
      allocate(cpos(3,dims(1)), s_edge(2,dims(2)), t_edge(2,dims(3)))
      call PoVRay_getpos_FZ432(dims, cpos, s_edge, t_edge, ns, d, nt)
    end if
end if
! add the reference frame and any necessary wireframes
if (rmode.eq.1) then
  ac = 0.5D0 * LPs%ap
  call PoVRay_addReferenceFrame(dunit, ac, cylr)
  call PoVRay_addCubochoricCube(dunit)
end if
if (rmode.eq.2) then
  ac = 1.33067D0
  call PoVRay_addReferenceFrame(dunit, ac, cylr)
  call PoVRay_addWireFrameSphere(dunit, ac)
end if
if (rmode.eq.3) then
  ac = 1.0D0
  call PoVRay_addReferenceFrame(dunit, ac, cylr)
  call PoVRay_addWireFrameSphere(dunit, ac)
end if
if (rmode.eq.4) then
  ac = 1.0D0
  call PoVRay_addReferenceFrame(dunit, ac, cylr)
end if
if (rmode.eq.5) then
  call PoVRay_addEulerBox(dunit)
end if
! and next, draw the outline of the FZ or MFZ
if ((rmode.eq.1).or.(rmode.eq.2)) then
! create the square edges first
 dx = 1.D0/dble(ns)
 do i=1,dims(2)
  ro1(1:3) = cpos(1:3,s_edge(1,i))
  ro1(4) = d
  ro2(1:3) = cpos(1:3,s_edge(2,i))
  ro2(4) = d
  culast = ro2cu(ro1)
  holast = ro2ho(ro1)
  do j=1,ns+1
    ro(1:3) = d*ro1(1:3) + d*(ro2(1:3) - ro1(1:3)) * j * dx
    xx = dsqrt( sum (ro(1:3)**2) )
    ro(1:3) = ro(1:3)/xx
    ro(4) = xx
    cu = ro2cu(ro)
    ho = ro2ho(ro)
! and create a cylinder with these points
    if (rmode.eq.1) then
      call PoVRay_addCylinder(dunit, culast(1:3),cu(1:3),cylr,(/ 0.0, 0.0, 1.0 /))
    else
      call PoVRay_addCylinder(dunit, holast(1:3),ho(1:3),cylr,(/ 0.0, 0.0, 1.0 /))
    end if
    culast = cu
    holast = ho
  end do
 end do
 if (twostep) then
   dx = 1.D0/dble(nt)
   do i=1,dims(3)
    ro1(1:3) = cpos(1:3,t_edge(1,i))
    ro1(4) = d
    ro2(1:3) = cpos(1:3,t_edge(2,i))
    ro2(4) = d
    culast = ro2cu(ro1)
    holast = ro2ho(ro1)
    do j=1,nt+1
      ro(1:3) = d*ro1(1:3) + d*(ro2(1:3) - ro1(1:3)) * j * dx
      xx = dsqrt( sum (ro(1:3)**2) )
      ro(1:3) = ro(1:3)/xx
      ro(4) = xx
      cu = ro2cu(ro)
      ho = ro2ho(ro)
  ! and create a cylinder with these points
      if (rmode.eq.1) then
        call PoVRay_addCylinder(dunit, culast(1:3),cu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      else
        call PoVRay_addCylinder(dunit, holast(1:3),ho(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      end if
      culast = cu
      holast = ho
    end do
   end do
  end if
end if
if ((rmode.eq.3).or.(rmode.eq.4)) then
 dx = 1.D0/dble(ns)
 do i=1,dims(2)
  ro1(1:3) = cpos(1:3,s_edge(1,i))
  ro1(4) = d
  ro2(1:3) = cpos(1:3,s_edge(2,i))
  ro2(4) = d
  rolast = ro1
  qu = ro2qu(ro1)
  splast(1:3) = qu(2:4)/ (1.D0 + qu(1))
  do j=1,ns+1
    ro(1:3) = d*ro1(1:3) + d*(ro2(1:3) - ro1(1:3)) * j * dx
    xx = dsqrt( sum (ro(1:3)**2) )
    ro(1:3) = ro(1:3)/xx
    ro(4) = xx
    qu = ro2qu(ro)
    sp(1:3) = qu(2:4)/ (1.D0 + qu(1))
! and create a cylinder with these points
    if (rmode.eq.3) then
       call PoVRay_addCylinder(dunit, splast(1:3),sp(1:3),cylr,(/ 0.0, 0.0, 1.0 /))
    else
       call PoVRay_addCylinder(dunit, rolast(1:3)*rolast(4),ro(1:3)*ro(4),cylr,(/ 0.0, 0.0, 1.0 /))
    end if
    rolast = ro
    splast = sp
  end do
 end do
 if (twostep) then
   dx = 1.D0/dble(nt)
   do i=1,dims(3)
    ro1(1:3) = cpos(1:3,t_edge(1,i))
    ro1(4) = d
    ro2(1:3) = cpos(1:3,t_edge(2,i))
    ro2(4) = d
    rolast = ro1
    qu = ro2qu(ro1)
    splast(1:3) = qu(2:4)/ (1.D0 + qu(1))
    do j=1,nt+1
      ro(1:3) = d*ro1(1:3) + d*(ro2(1:3) - ro1(1:3)) * j * dx
      xx = dsqrt( sum (ro(1:3)**2) )
      ro(1:3) = ro(1:3)/xx
      ro(4) = xx
      qu = ro2qu(ro)
      sp(1:3) = qu(2:4)/ (1.D0 + qu(1))
  ! and create a cylinder with these points
      if (rmode.eq.3) then
         call PoVRay_addCylinder(dunit, splast(1:3),sp(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      else
         call PoVRay_addCylinder(dunit, rolast(1:3)*rolast(4),ro(1:3)*ro(4),cylr,(/ 1.0, 0.0, 0.0 /))
      end if
      rolast = ro
      splast = sp
    end do
   end do
 end if
end if
! and next, draw the outline of the FZ or MFZ
if (rmode.eq.5) then
  sh = (/ cPi, cPi/2.D0, cPi /)
! create the square edges first
 dx = 1.D0/dble(ns)
 do i=1,dims(2)
  ro1(1:3) = cpos(1:3,s_edge(1,i))
  ro1(4) = d
  ro2(1:3) = cpos(1:3,s_edge(2,i))
  ro2(4) = d
  eulast = ro2eu(ro1)
  eulast(1) = mod(eulast(1)+10.D0*cPi,2.D0*cPi)
  eulast(2) = mod(eulast(2)+10.D0*cPi,cPi)
  eulast(3) = mod(eulast(3)+10.D0*cPi,2.D0*cPi)
  eulast = eulast - sh
  do j=1,ns+1
    ro(1:3) = d*ro1(1:3) + d*(ro2(1:3) - ro1(1:3)) * j * dx
    xx = dsqrt( sum (ro(1:3)**2) )
    ro(1:3) = ro(1:3)/xx
    ro(4) = xx
    eu = ro2eu(ro)
    eu(1) = mod(eu(1)+10.D0*cPi,2.D0*cPi)
    eu(2) = mod(eu(2)+10.D0*cPi,cPi)
    eu(3) = mod(eu(3)+10.D0*cPi,2.D0*cPi)
    eu = eu - sh
! and create a cylinder with these points
    if (maxval(abs(eulast-eu)).lt.cPi) then
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 0.0, 0.0, 1.0 /))
    end if
    eulast = eu
  end do
 end do
 if (twostep) then
   dx = 1.D0/dble(nt)
   do i=1,dims(3)
    ro1(1:3) = cpos(1:3,t_edge(1,i))
    ro1(4) = d
    ro2(1:3) = cpos(1:3,t_edge(2,i))
    ro2(4) = d
    eulast = ro2eu(ro1)
    eulast(1) = mod(eulast(1)+10.D0*cPi,2.D0*cPi)
    eulast(2) = mod(eulast(2)+10.D0*cPi,cPi)
    eulast(3) = mod(eulast(3)+10.D0*cPi,2.D0*cPi)
    eulast = eulast - sh
    do j=1,nt+1
      ro(1:3) = d*ro1(1:3) + d*(ro2(1:3) - ro1(1:3)) * j * dx
      xx = dsqrt( sum (ro(1:3)**2) )
      ro(1:3) = ro(1:3)/xx
      ro(4) = xx
      eu = ro2eu(ro)
      eu(1) = mod(eu(1)+10.D0*cPi,2.D0*cPi)
      eu(2) = mod(eu(2)+10.D0*cPi,cPi)
      eu(3) = mod(eu(3)+10.D0*cPi,2.D0*cPi)
      eu = eu - sh
  ! and create a cylinder with these points
      if (maxval(abs(eulast-eu)).lt.cPi) then
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      end if
      eulast = eu
    end do
   end do
  end if
! for the Euler representation of the Rodrigues fundamental zones we also need to draw
! a few additional lines to complete the volume appearance of the FZ; this depends on
! the order of the FZ, naturally, so we have a couple of possible cases...
! the diagonal lines in the Phi=0 plane are the most important lines; they should be drawn
! for all the rotation groups except for the identity
  if ((FZtype.ge.1).and.(FZtype.le.2)) then
    if (FZorder.ne.0) then  ! we have cyclic or dihedral
      xx = cPi/dble(FZorder)
! draw four diagonal lines
      eu(1:3) = (/ xx, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ 0.D0, 0.D0, xx /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi-xx, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ 0.D0, 0.D0, tpi-xx /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, xx /) - sh
      eulast(1:3) = (/ xx, 0.D0, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, tpi-xx /) - sh
      eulast(1:3) = (/ tpi-xx, 0.D0, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
! for cyclic groups we also need to draw the diagonals in the top surface
! and the vertical lines connecting bottom and top planes
      if (FZtype.eq.1) then
! top plane
        eu(1:3) = (/ xx, cPi, 0.D0 /) - sh
        eulast(1:3) = (/ 0.D0, cPi, xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi-xx, cPi, 0.D0 /) - sh
        eulast(1:3) = (/ 0.D0, cPi, tpi-xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi, cPi, xx /) - sh
        eulast(1:3) = (/ xx, cPi, tpi /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi, cPi, tpi-xx /) - sh
        eulast(1:3) = (/ tpi-xx, cPi, tpi /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
! verticals
        eu(1:3) = (/ xx, 0.D0, 0.D0 /) - sh
        eulast(1:3) = (/ xx, cPi, 0.D0 /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ 0.D0, 0.D0, xx /) - sh
        eulast(1:3) = (/ 0.D0, cPi, xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi-xx, 0.D0, 0.D0 /) - sh
        eulast(1:3) = (/ tpi-xx, cPi, 0.D0 /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ 0.D0, 0.D0, tpi-xx /) - sh
        eulast(1:3) = (/ 0.D0, cPi, tpi-xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi, 0.D0, xx /) - sh
        eulast(1:3) = (/ tpi, cPi, xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ xx, 0.D0, tpi /) - sh
        eulast(1:3) = (/ xx, cPi, tpi /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi, 0.D0, tpi-xx /) - sh
        eulast(1:3) = (/ tpi, cPi, tpi-xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi-xx, 0.D0, tpi /) - sh
        eulast(1:3) = (/ tpi-xx, cPi, tpi /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      end if
      if (FZtype.eq.2) then
! in this case, the verticals need to be drawn but only up to the level of the FZ surface
        eu(1:3) = (/ xx, 0.D0, 0.D0 /) - sh
        eulast(1:3) = (/ xx, hPi, 0.D0 /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ 0.D0, 0.D0, xx /) - sh
        eulast(1:3) = (/ 0.D0, hPi, xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi-xx, 0.D0, 0.D0 /) - sh
        eulast(1:3) = (/ tpi-xx, hPi, 0.D0 /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ 0.D0, 0.D0, tpi-xx /) - sh
        eulast(1:3) = (/ 0.D0, hPi, tpi-xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi, 0.D0, xx /) - sh
        eulast(1:3) = (/ tpi, hPi, xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ xx, 0.D0, tpi /) - sh
        eulast(1:3) = (/ xx, hPi, tpi /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi, 0.D0, tpi-xx /) - sh
        eulast(1:3) = (/ tpi, hPi, tpi-xx /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
        eu(1:3) = (/ tpi-xx, 0.D0, tpi /) - sh
        eulast(1:3) = (/ tpi-xx, hPi, tpi /) - sh
        call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      end if
    end if
  end if
  if (FZtype.eq.4) then
      xx = cPi/dble(4)
! draw four diagonal lines
      eu(1:3) = (/ xx, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ 0.D0, 0.D0, xx /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi-xx, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ 0.D0, 0.D0, tpi-xx /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, xx /) - sh
      eulast(1:3) = (/ xx, 0.D0, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, tpi-xx /) - sh
      eulast(1:3) = (/ tpi-xx, 0.D0, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
! and verticals
      hPi = hPi * 0.5D0
      eu(1:3) = (/ xx, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ xx, hPi, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ 0.D0, 0.D0, xx /) - sh
      eulast(1:3) = (/ 0.D0, hPi, xx /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi-xx, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ tpi-xx, hPi, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ 0.D0, 0.D0, tpi-xx /) - sh
      eulast(1:3) = (/ 0.D0, hPi, tpi-xx /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, xx /) - sh
      eulast(1:3) = (/ tpi, hPi, xx /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ xx, 0.D0, tpi /) - sh
      eulast(1:3) = (/ xx, hPi, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, tpi-xx /) - sh
      eulast(1:3) = (/ tpi, hPi, tpi-xx /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi-xx, 0.D0, tpi /) - sh
      eulast(1:3) = (/ tpi-xx, hPi, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
 ! and the closing segments
      eu(1:3) = (/ xx, hPi, 0.D0 /) - sh
      eulast(1:3) = (/ 0.D0, hPi, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ 0.D0, hPi, xx /) - sh
      eulast(1:3) = (/ 0.D0, hPi, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi-xx, hPi, 0.D0 /) - sh
      eulast(1:3) = (/ tpi, hPi, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ 0.D0, hPi, tpi-xx /) - sh
      eulast(1:3) = (/ 0.D0, hPi, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, hPi, xx /) - sh
      eulast(1:3) = (/ tpi, hPi, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ xx, hPi, tpi /) - sh
      eulast(1:3) = (/ 0.D0, hPi, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, hPi, tpi-xx /) - sh
      eulast(1:3) = (/ tpi, hPi, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi-xx, hPi, tpi /) - sh
      eulast(1:3) = (/ tpi, hPi, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
! and finally the corner posts
      eu(1:3) = (/ 0.D0, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ hPi, 0.D0, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ 0.D0, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ 0.D0, hPi, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ 0.D0, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ 0.D0, 0.D0, hPi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ tpi - hPi, 0.D0, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ tpi, hPi, 0.D0 /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, 0.D0 /) - sh
      eulast(1:3) = (/ tpi, 0.D0, hPi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, tpi /) - sh
      eulast(1:3) = (/ tpi - hPi, 0.D0, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, tpi /) - sh
      eulast(1:3) = (/ tpi, hPi, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ tpi, 0.D0, tpi /) - sh
      eulast(1:3) = (/ tpi, 0.D0, tpi-hPi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ 0.D0, 0.D0, tpi /) - sh
      eulast(1:3) = (/ 0.D0 + hPi, 0.D0, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ 0.D0, 0.D0, tpi /) - sh
      eulast(1:3) = (/ 0.D0, hPi, tpi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
      eu(1:3) = (/ 0.D0, 0.D0, tpi /) - sh
      eulast(1:3) = (/ 0.D0, 0.D0, tpi-hPi /) - sh
      call PoVRay_addCylinder(dunit,eulast(1:3),eu(1:3),cylr,(/ 1.0, 0.0, 0.0 /))
  end if
end if
end subroutine PoVRay_drawFZ
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
povray_drawfz calls ro2eu, ro2qu, povray_getpos_fz23, povray_addeulerbox, povray_addcubochoriccube, povray_getpos_fz622, povray_getpos_fz32, povray_addwireframesphere, povray_getpos_fz422, povray_addreferenceframe, ro2cu, ro2ho, povray_addcylinder, povray_getpos_fz432, povray_getpos_fz222
povray_addcubochoriccube calls povray_addcylinder