read_STEM_data – Fortran Program
read_STEM_data Subroutine
71 statements
Source File
public recursive subroutine read_STEM_data(STEM, cell, F, Dyn, STEMnmlfile, khead, reflist, geometry, nn, g, kt, numk, beamdiv)
Uses:
io
files
kvectors
gvectors
@author Marc De Graef, Carnegie Mellon University @brief read detector and other parameters for the STEM case @param STEM STEM structure @param cell unit cell pointer @param F foil normal @param Dyn dynamical scattering structure @param STEMnmlfile filename of the namelist file @param khead top of kvector list @param reflist top of reflection list @param geometry 'SR' for systematic row or 'ZA' for zone axis @param nn number of reflections @param g fundamental g-vector for systematic row @param kt tangential wave vector component @param numk number of distinct wave vectors (optional) @param beamdiv beam divergence parameter (optional) @date 04/29/11 MDG 1.0 original @date 06/12/13 MDG 2.0 rewrite @date 11/26/13 MDG 2.1 made geometry an input parameter instead of part of the STEMdata namelist @date 06/10/14 MDG 3.0 added STEM, cell, foil, and Dyn arguments
Arguments
Type Intent Optional Attributes Name
type(STEMtype), intent(inout) :: STEM
type(unitcell), pointer :: cell
real(kind=dbl), intent(inout) :: F(3)
type(DynType), intent(inout) :: Dyn
character(len=fnlen), intent(in) :: STEMnmlfile
type(kvectorlist), pointer :: khead
type(reflisttype), pointer :: reflist
character(len=2), intent(in) :: geometry
integer(kind=irg), intent(in) :: nn
integer(kind=irg), intent(in) :: g(3)
real(kind=sgl), intent(in) :: kt
integer(kind=irg), intent(in), optional :: numk
real(kind=sgl), intent(out), optional :: beamdiv
Calls
Source Code
read_STEM_data
Source Code
recursive subroutine read_STEM_data(STEM,cell,F,Dyn,STEMnmlfile,khead,reflist,geometry,nn,g,kt,numk,beamdiv)
!DEC$ ATTRIBUTES DLLEXPORT :: read_STEM_data
use io
use files
use kvectors
use gvectors
IMPLICIT NONE
type(STEMtype),INTENT(INOUT)                    :: STEM
type(unitcell),pointer                          :: cell
real(kind=dbl),INTENT(INOUT)                    :: F(3)
type(DynType),INTENT(INOUT)                     :: Dyn
character(fnlen),INTENT(IN)                     :: STEMnmlfile
type(kvectorlist),pointer                       :: khead
type(reflisttype),pointer                       :: reflist
character(2),INTENT(IN)                         :: geometry  ! 'SR' or 'ZA'
integer(kind=irg),INTENT(IN)                    :: nn
integer(kind=irg),INTENT(IN)                    :: g(3)
real(kind=sgl),INTENT(IN)                       :: kt
integer(kind=irg),INTENT(IN),OPTIONAL           :: numk
real(kind=sgl),INTENT(OUT),OPTIONAL             :: beamdiv
integer(kind=irg)                               :: numberofsvalues,numCL
real(kind=sgl)                                  :: BFradius,ADFinnerradius,ADFouterradius,beamconvergence,cameralength, &
                                                        diffaprad, diffapcenter,CLarray(20)
character(fnlen)                                :: weightoutput
namelist / STEMdata / BFradius, ADFinnerradius, ADFouterradius, cameralength, numCL, &
                      beamconvergence, numberofsvalues, diffaprad, diffapcenter, weightoutput, CLarray
! set default values (based on OSU Tecnai F20)
BFradius = 3.5                  ! mm
ADFinnerradius = 3.5            ! mm
ADFouterradius = 10.0           ! mm
cameralength = 100.0            ! mm
numCL = 0                       ! number of camera lengths to be used  (if zero, then use cameralength instead)
CLarray = 0.0                   ! values for the camera lengths
beamconvergence = 2.0           ! mrad
numberofsvalues = 33            ! integer
diffaprad = 0.0                 ! diffraction aperture radius in mrad, 0.0 if no aperture is present
diffapcenter = 0.0              ! position of center of diffraction aperture in mrad along systematic row
weightoutput = ''               ! string with filename root for graphical output of weight profiles, empty if not needed
! read the namelist file
call Message('opening '//trim(STEMnmlfile), frm = "(/A)")
open(UNIT=dataunit,FILE=trim(EMsoft_toNativePath(STEMnmlfile)),DELIM='APOSTROPHE')
read(UNIT=dataunit,NML=STEMdata)
close(UNIT=dataunit)
if (PRESENT(beamdiv)) beamdiv=beamconvergence
! set the parameters
  STEM%BFradius = BFradius
  STEM%ADFinnerradius = ADFinnerradius
  STEM%ADFouterradius = ADFouterradius
  STEM%kt = kt
  STEM%cameralength = cameralength
  STEM%beamconvergence = beamconvergence
  if (numCL.ne.0) then
    STEM%numCL = numCL
    STEM%CLarray = CLarray
  else
    STEM%numCL = 1
    STEM%CLarray = cameralength
  end if
! make sure the number of s values is an odd number
  if (mod(numberofsvalues,2).eq.0) numberofsvalues=numberofsvalues+1
  STEM%numberofsvalues = numberofsvalues
  STEM%diffapmrad = diffaprad
  STEM%diffapmcenter = diffapcenter
  STEM%weightoutput = weightoutput
  STEM%geometry = geometry
  if (PRESENT(numk)) then
    STEM%numk = numk
  else
    STEM%numk = STEM%numberofsvalues
  end if
! and initialize all other STEM related arrays
if (.not.PRESENT(beamdiv)) then
  if (geometry.eq.'SR') then
    call init_STEM(STEM,cell,nn,g)
  else
    call init_STEM_ZA(STEM,cell,F,Dyn,khead,reflist,nn)
  end if
end if
end subroutine read_STEM_data
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
read_stem_data calls emsoft_tonativepath, message, init_stem_za, init_stem
init_stem_za calls float, transspace, calclength, sngl, calcsg, normvec
init_stem calls message, float, calclength, calcdiffangle