SampleRFZ – Fortran Program
SampleRFZ Subroutine
63 statements
Source File
public recursive subroutine SampleRFZ(nsteps, pgnum, gridtype, FZcnt, FZlist)
Uses:
typedefs
constants
rotations
@author Marc De Graef, Carnegie Mellon University @brief Generate a uniform sampling of a Rodriguess FZ
Note
This routine fills in a linked list FZlist of Rodrigues points that are inside a specific fundamental zone determined by the sample point group; this list can then be further dealt with in the calling program.
Here's how you would use this routine in a main program:
use so3
integer(kind=irg) :: FZcnt, nsteps, pgnum type(FZpointd),pointer :: FZlist, FZtmp
nullify(FZlist) FZcnt = 0 nsteps = 10 pgnum = 32 call sampleRFZ(nsteps, pgnum, FZcnt, FZlist)
Then you can access all the entries in the list and, for instance, convert them to Euler angles...
FZtmp => FZlist ! point to the top of the list do i = 1, FZcnt ! loop over all entries eu = ro2eu(FZtmp%rod) ! convert to Euler angles do something with eu ! for instance, write eu to a file FZtmp => FZtmp%next ! point to the next entry end do
If you just want to look at the first 10 entries on the list and show all other orientation representations:
type(orientationtyped):: ot
FZtmp => FZlist do i = 1,10 ot = init_orientation(FZtmp%rod,'ro') call print_orientation(ot) FZtmp => FZtmp%next end do @param nsteps number of steps along semi-edge in cubochoric grid @param pgnum point group number to determine the appropriate Rodrigues fundamental zone @param gridtype (input) 0 for origin-centered grid; 1 for grid with origin at box center @param FZcnt (output) number of points inside fundamental zone @param FZlist (output) linked list of points inside fundamental zone @date 05/12/14 MDG 1.0 original @date 10/02/14 MDG 2.0 rewrite, removed all globals, added function arguments @date 09/15/15 MDG 2.1 removed explicit origin allocation; changed while to do loops. @date 01/17/15 MDG 2.2 added gridtype option @date 05/22/16 MDG 2.3 correction for monoclinic symmetry with twofold axis along b, not c !!!
Arguments
Type Intent Optional Attributes Name
integer(kind=irg), intent(in) :: nsteps
integer(kind=irg), intent(in) :: pgnum
integer(kind=irg), intent(in) :: gridtype
integer(kind=irg), intent(out) :: FZcnt
type(FZpointd), intent(out), pointer :: FZlist
Calls
Source Code
SampleRFZ
Source Code
recursive subroutine SampleRFZ(nsteps,pgnum,gridtype,FZcnt,FZlist)
!DEC$ ATTRIBUTES DLLEXPORT :: SampleRFZ
use typedefs
use constants
use rotations
IMPLICIT NONE
integer(kind=irg), INTENT(IN)        :: nsteps
integer(kind=irg), INTENT(IN)        :: pgnum
integer(kind=irg), INTENT(IN)        :: gridtype
integer(kind=irg),INTENT(OUT)        :: FZcnt                ! counts number of entries in linked list
type(FZpointd),pointer,INTENT(OUT)   :: FZlist               ! pointers
real(kind=dbl)                       :: x, y, z, rod(4), delta, shift, sedge, ztmp
type(FZpointd), pointer              :: FZtmp, FZtmp2
integer(kind=irg)                    :: FZtype, FZorder, i, j, k
logical                              :: b
! cube semi-edge length s = 0.5D0 * LPs%ap
! step size for sampling of grid; total number of samples = (2*nsteps+1)**3
sedge = 0.5D0 * LPs%ap
delta = sedge / dble(nsteps)
if (gridtype.eq.0) then
  shift = 0.0D0
else
  shift = 0.5D0
end if
! set the counter to zero
FZcnt = 0
! make sure the linked lists are empty
if (associated(FZlist)) then
  FZtmp => FZlist%next
  FZtmp2 => FZlist
  do
    deallocate(FZtmp2)
    if (.not. associated(FZtmp) ) EXIT
    FZtmp2 => FZtmp
    FZtmp => FZtmp%next
  end do
  nullify(FZlist)
else
  nullify(FZlist)
end if
! determine which function we should call for this point group symmetry
FZtype = FZtarray(pgnum)
FZorder = FZoarray(pgnum)
! note that when FZtype is cyclic (1) and FZorder is 2, then we must rotate the
! rotation axis to lie along the b (y) direction, not z !!!!
! loop over the cube of volume pi^2; note that we do not want to include
! the opposite edges/facets of the cube, to avoid double counting rotations
! with a rotation angle of 180 degrees.  This only affects the cyclic groups.
 do i=-nsteps+1,nsteps
  x = (dble(i)+shift)*delta
  do j=-nsteps+1,nsteps
   y = (dble(j)+shift)*delta
   do k=-nsteps+1,nsteps
    z = (dble(k)+shift)*delta
! make sure that this point lies inside the cubochoric cell
    if (maxval( (/ abs(x), abs(y), abs(z) /) ).le.sedge) then
! convert to Rodrigues representation
      rod = cu2ro( (/ x, y, z /) )
! If insideFZ=.TRUE., then add this point to the linked list FZlist and keep
! track of how many points there are on this list
       b = IsinsideFZ(rod,FZtype,FZorder)
       if (b) then
        if (.not.associated(FZlist)) then
          allocate(FZlist)
          FZtmp => FZlist
! in DEBUG mode, there is a strange error here ...
! if gridtype = 0 then we must add the identity rotation here
! currently, the identity is not automatically recognized since the
! returns from several rotation routines also equal the identity when
! the point is actually invalid...
!          if (gridtype.eq.0) then
!            FZcnt = 1
!            FZtmp%rod = (/ 0.D0, 0.D0, 1.D0, 0.D0 /)
!            allocate(FZtmp%next)
!            FZtmp => FZtmp%next
!            nullify(FZtmp%next)
!          end if
        else
          allocate(FZtmp%next)
          FZtmp => FZtmp%next
        end if
        nullify(FZtmp%next)
! if monoclinic, then reorder the components !!!
!        if ((FZtype.eq.1).and.(FZorder.eq.2)) then
!          ztmp = rod(3)
!          rod(3) = rod(1)
!          rod(1) = rod(2)
!          rod(2) = ztmp
!        end if
        FZtmp%rod = rod
        FZcnt = FZcnt + 1
       end if
    end if
  end do
 end do
end do
end subroutine SampleRFZ
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
samplerfz calls isinsidefz, cu2ro, fztarray, fzoarray
isinsidefz calls insidecubicfz, insidecubehexfz, insidecyclicfz, insidedihedralfz