SENZADERGLOB – Fortran Program
SENZADERGLOB Subroutine
672 statements
Source File
public subroutine SENZADERGLOB(ipar, fparebsd, initmeanval, ninit, nipar, nfpar, expt, accum_e, mLPNH, mLPSH, verbose, calfun, N, XSUP, XINF)
Uses:
typedefs
Arguments
Type Intent Optional Attributes Name
integer(kind=8), intent(in) :: ipar(nipar)
real(kind=sgl), intent(inout) :: fparebsd(nfpar)
real(kind=sgl), intent(in) :: initmeanval(ninit)
integer(kind=irg), intent(in) :: ninit
integer(kind=irg), intent(in) :: nipar
integer(kind=irg), intent(in) :: nfpar
real(kind=sgl), intent(in) :: expt(ipar(2)*ipar(3))
real(kind=sgl), intent(in) :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
real(kind=sgl), intent(in) :: mLPNH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(10),ipar(7))
real(kind=sgl), intent(in) :: mLPSH(-ipar(6):ipar(6),-ipar(6):ipar(6),ipar(10),ipar(7))
logical, intent(in), optional :: verbose
procedure(func) :: calfun
integer :: N
double precision, intent(in) :: XSUP(N)
double precision, intent(in) :: XINF(N)
Calls
Common Blocks
NUMNEW2 CALFANR2
Source Code
SENZADERGLOB
Common Blocks
common /NUMNEW2/
Type Attributes Name Initial
integer :: NF
common /CALFANR2/
Type Attributes Name Initial
integer :: NORMADUE
Source Code
SUBROUTINE SENZADERGLOB(ipar,fparebsd,initmeanval,ninit,nipar,nfpar,&
                        expt,accum_e,mLPNH,mLPSH,verbose,calfun,N,XSUP,XINF)
    !USE IMSLF90
    use typedefs
    IMPLICIT NONE
    INTEGER, PARAMETER                :: IRUNS      = 10
    PROCEDURE(func)                    :: calfun
      integer(8),intent(in)                :: ipar(nipar)
      real(sgl),intent(inout)              :: fparebsd(nfpar)
      real(sgl),intent(in)                 :: initmeanval(ninit)
      integer(irg),intent(in)              :: ninit
      integer(irg),intent(in)              :: nipar
      integer(irg),intent(in)              :: nfpar
      real(sgl),intent(in)                 :: expt(ipar(2)*ipar(3))
      real(sgl),intent(in)                 :: accum_e(ipar(4),-ipar(5):ipar(5),-ipar(5):ipar(5))
      real(sgl),intent(in)                 :: mLPNH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(10), ipar(7))
      real(sgl),intent(in)                 :: mLPSH(-ipar(6):ipar(6), -ipar(6):ipar(6), ipar(10), ipar(7))
      logical,intent(in),optional          :: verbose
      DOUBLE PRECISION,  INTENT(IN)        :: XINF(N), XSUP(N)
!    INCLUDE 'TYPEDECL.FI'
    INTEGER                        :: N, NF, NFAILS, IDIMWKS, NUMFAL, IOTT, ISTOP
    INTEGER                        :: VECTNF(IRUNS), VECTNFOTT(IRUNS)
    INTEGER                        :: LSTOT, NFTOT, NPCTOT, NLMTOT, IT, IMAX
    INTEGER                        :: LS, NPC, NLM, ICONTFAL, IDFAL, NUMITER
    INTEGER                        :: NUMCAS, K, I, J, MAXLS, MODLS
    INTEGER                        :: MAXITER, MAXNF, PRINT_LEVEL, nfott, SUMNF
    INTEGER*4                    :: IVAR, IVAR2
    TYPE(COMP_WKS_TYP),ALLOCATABLE    :: WKS(:)
    DOUBLE PRECISION,  ALLOCATABLE    :: X(:), XOTT(:), DOLDALFA(:)
    DOUBLE PRECISION,  ALLOCATABLE    :: Z(:), VETT(:), XPROP(:), D(:)
    DOUBLE PRECISION,  ALLOCATABLE  :: RA(:), RB(:)
    INTEGER            ,  ALLOCATABLE    :: IPERM(:)
    DOUBLE PRECISION                :: VECTFVAL(IRUNS), VECTF_OTT(IRUNS)
    DOUBLE PRECISION                :: TOL, FMAX_EFF, fglob
    DOUBLE PRECISION                :: RFAL, RNUMFAL, RMED, RMED2, f_ott, FOTT, F, ALFAMAX, ALFAOTT
    DOUBLE PRECISION                :: FPROP, VAR2, VAR1, ALFA, ZETA, TRES, DIFF
    DOUBLE PRECISION                :: FSTOP, FSTOPTOL, FFSTOP
    DOUBLE PRECISION                :: TEMPERATURA, SUMITER, SUMTIME
    DOUBLE PRECISION                :: F_MIN, F_MIN1, F_MAX, F_MINTOT, F_MINOTT, TCOEFF, FMIN, FMAX
    REAL                            :: RRAND
    LOGICAL                            :: L_F_DISTANTI, L_F_VICINI, NON_MINIMIZZ, SOLOSULPEGG, NORMADUE
    LOGICAL, ALLOCATABLE            :: MASCH(:)
    CHARACTER ( LEN = 40 )            :: nomefun
    CHARACTER ( LEN = 2  )            :: CSTEP
    COMMON/NUMNEW2/        NF
    COMMON/CALFANR2/    NORMADUE
    NFOTT  = 0
!    CALL     NINIT(N)
!    CALL FUNCTINIT(N,XINF,XSUP,nomefun,fglob)
        fglob = 0.D0
!-----------------------------------------------
!    SETTA LE TOLLERANZE E I MASSIMI
!-----------------------------------------------
    TOL         = 1.0D-4
    FSTOPTOL    = 1.0D-15
    MAXITER     = 100000000
    MAXNF       = 1000*n
    NUMFAL        = 0
    PRINT_LEVEL = 0
    TCOEFF      = 1.0D0
!--------------------------------------------------------
!    modificato il 23/9/2003
!--------------------------------------------------------
!    IDIMWKS     = 20 !MIN(10*N,10)
!    IDIMWKS     = MAX(10,N)
    IDIMWKS     = MIN(20,MAX(10,N))
!--------------------------------------------------------
    SOLOSULPEGG = .FALSE.
    NORMADUE    = .FALSE.
!-----------------------------------------------
    ALLOCATE(X(N),XOTT(N),Z(N),VETT(N),XPROP(N))
    ALLOCATE(DOLDALFA(N),D(N))
    ALLOCATE(RA(IDIMWKS),RB(IDIMWKS),IPERM(IDIMWKS))
!
!    -------
!     Iniz.
!    -------
!
    LSTOT  = 0
    NFTOT  = 0
    NFOTT  = 0
    NPCTOT = 0
    NLMTOT = 0
    CALL RANDOM_SEED()
    DO 171 IT=1,IRUNS
        ALLOCATE(WKS(IDIMWKS),MASCH(IDIMWKS))
        DO I = 1,IDIMWKS
            ALLOCATE(WKS(I)%X(N))
            ALLOCATE(WKS(I)%D(N))
            ALLOCATE(WKS(I)%DOLDALFA(N))
        ENDDO
        MASCH    = .FALSE.
        LS       = 0
        NF       = 0
        NFOTT    = 0
        NPC      = 0
        NLM      = 0
        RFAL     = 0.0D0
        RNUMFAL  = 0.0D0
        ICONTFAL = 0
        IDFAL    = 0
        NUMITER  = 0
        ivar     = 2*it + 3*(it+7)
        ivar2    = 3*it + 2*(it+9) -5
        RMED     = 0.D0
        RMED2    = 0.D0
!    -------------------------------------
!      Generazione del campione originale
!    -------------------------------------
        FOTT     = 1.D+32
!--------------------------------------------------------
!    modificato il 23/9/2003
!--------------------------------------------------------
        NUMCAS   = 30
!        NUMCAS   = 1
!--------------------------------------------------------
        IF(PRINT_LEVEL >= 0) THEN
            WRITE(*,2070)
            WRITE(*,2080)
            WRITE(1,2070)
            WRITE(1,2080)
        ENDIF
        DO K=1,NUMCAS
3000        CONTINUE
            DO I=1,N
                CALL RANDOM_NUMBER(RRAND)
                VETT(I)=DBLE(RRAND) !RAN(IVAR2)
                !VETT(I)=RAN(IVAR2)
                XPROP(I)=XINF(I)+VETT(I)*(XSUP(I)-XINF(I))
            ENDDO
            if (K .eq. 1) then
                XPROP = 0.5D0
            end if
            !CALL FUNCT(XPROP,N,FPROP)
            call  calfun(nipar, nfpar, ninit, ipar, fparebsd, initmeanval, expt, accum_e, mLPNH, mLPSH, &
                                N, XPROP, FPROP, verbose)
            NPC=NPC+1
            NF=NF+1
            RMED=((NPC-1.0D0)*RMED+FPROP)/NPC
            IF(NPC.LE.2) THEN
                RMED2=RMED2+FPROP**2
            ELSE
                RMED2=((NPC-2.)*RMED2+FPROP**2)/(NPC-1.0D0)
            ENDIF
            IF(FPROP.LT.FOTT) THEN
                CALL AGGIORNO_OTTIMO(N,XPROP,FPROP,XOTT,FOTT)
            ENDIF
            IF(PRINT_LEVEL >= 0) THEN
                WRITE(*,2130) NUMITER, NF, FPROP,'--'
                WRITE(1,2130) NUMITER, NF, FPROP,'--'
            ENDIF
        ENDDO
        IF(PRINT_LEVEL >= 2) THEN
            write(*,*)'fine generazione random iniziale nf = ', nf
            write(1,*)'fine generazione random iniziale nf = ', nf
        ENDIF
        VAR2=RMED2-(RMED**2)*(NPC/(NPC-1.))
!---------------------------------------------------------
!    RIEMPIO IL WKS DI IDIMWKS PUNTI
!    CHE SODDISFANO IL TEST DEL S.A.
!---------------------------------------------------------
!    alfa     = 1.0d0
!    DOLDALFA = ALFA
    DO I=1,N
        DOLDALFA(I)=1.0D0*DMAX1(1.D-3,DMIN1(1.D+3,.5D0*DABS(XPROP(I))))
!        DOLDALFA(I)=1.D0
    END DO
    D        = 1.0D0
    xprop    = xott
    fprop    = fott
!    fmax_eff = fott
    if(print_level >= 2) then
        write(*,*) 'ricerca lungo assi'
    endif
    CALL RICERCA_LUNGO_ASSI(N,XPROP,FPROP,ALFA,DOLDALFA,D,FSTOP,XINF,XSUP,Fmax_eff,&
              ipar,fparebsd,initmeanval,ninit,nipar,nfpar,expt,accum_e,mLPNH,mLPSH,verbose,calfun)
    if(print_level >= 2) then
        write(*,*) 'fine ricerca lungo assi'
    endif
    WKS(1)%X       = XPROP
    WKS(1)%FOB     = FPROP
    WKS(1)%ALFAMAX = ALFA
    WKS(1)%DOLDALFA= DOLDALFA
    if(DOT_PRODUCT(DOLDALFA,DOLDALFA) < 0.0d0) then
        write(*,*) '---- 1 ----'
    endif
    WKS(1)%ALFANR2 = DSQRT(DOT_PRODUCT(DOLDALFA,DOLDALFA))
    WKS(1)%D       = D
    WKS(1)%FSTOP   = FSTOP
    WKS(1)%NUMCOST = 0
    IF(FPROP.LT.FOTT) THEN
        CALL AGGIORNO_OTTIMO(N,XPROP,FPROP,XOTT,FOTT)
    ENDIF
    IF(PRINT_LEVEL >= 0) THEN
        WRITE(*,2130) NUMITER, NF, FOTT,'IN'
        WRITE(1,2130) NUMITER, NF, FOTT,'IN'
    ENDIF
    DO I = 2,IDIMWKS
        ZETA = 1.0D0
        TRES = 0.0D0
        DO WHILE (ZETA.GT.TRES)
            CALL RANDOM_NUMBER(RRAND)
            ZETA=DBLE(RRAND) !RAN(IVAR)
            !ZETA=RAN(IVAR)
3010        CONTINUE
            DO J = 1,N
                CALL RANDOM_NUMBER(RRAND)
                VETT(J)=DBLE(RRAND) !RAN(IVAR2)
                !VETT(J)=RAN(IVAR2)
                XPROP(J)=XINF(J)+VETT(J)*(XSUP(J)-XINF(J))
            ENDDO
            !CALL FUNCT(XPROP,N,FPROP)
            call  calfun(nipar, nfpar, ninit, ipar, fparebsd, initmeanval, expt, accum_e, mLPNH, mLPSH, &
                                N, XPROP, FPROP, verbose)
            NPC = NPC+1
            NF  = NF+1
            RMED =((NPC-1.)*RMED+FPROP)/NPC
            RMED2=((NPC-2.)*RMED2+FPROP**2)/(NPC-1.)
            VAR2 =RMED2-(RMED**2)*(NPC/(NPC-1.))
            DIFF=RMED-FOTT
            TRES=DEXP(-TCOEFF*(RFAL/DIFF)*(FPROP-FOTT))
!--------------------------------------------------------
!    modificato il 23/9/2003
!--------------------------------------------------------
            IF(FPROP.LE.FOTT) THEN
                TRES = 1.0D0
            ENDIF
!            TRES = 1.0D0
!--------------------------------------------------------
        ENDDO
!        DO J=1,N
!            DOLDALFA(J)=1.0D0*DMAX1(1.D-3,DMIN1(1.D+3,.5D0*DABS(XPROP(J))))
!            DOLDALFA(J)=1.0D0
!        END DO
        ALFA      =  WKS(1)%ALFAMAX
        DOLDALFA  =  WKS(1)%DOLDALFA
        DO J = 2,I-1
           IF(ALFA.LT.WKS(J)%ALFAMAX) THEN
                ALFA      =  WKS(J)%ALFAMAX
                DOLDALFA  =  WKS(J)%DOLDALFA
           ENDIF
        ENDDO
!        DO K = 1,N
!            ALFA=WKS(1)%DOLDALFA(K)
!            DO J = 2,I-1
!               IF(ALFA.LT.WKS(J)%DOLDALFA(K)) THEN
!                   ALFA      =  WKS(J)%DOLDALFA(K)
!               ENDIF
!            ENDDO
!            DOLDALFA(K) = ALFA
!        ENDDO
        D        = 1.0D0
!        fmax_eff = fprop
        CALL RICERCA_LUNGO_ASSI(N,Xprop,Fprop,ALFA,DOLDALFA,D,FSTOP,XINF,XSUP,Fmax_eff,&
        ipar,fparebsd,initmeanval,ninit,nipar,nfpar,expt,accum_e,mLPNH,mLPSH,verbose,calfun)
        WKS(I)%X       = XPROP
        WKS(I)%FOB     = FPROP
        WKS(I)%ALFAMAX = ALFA
        WKS(I)%DOLDALFA= DOLDALFA
        if(DOT_PRODUCT(DOLDALFA,DOLDALFA) < 0.0d0) then
            write(*,*) '---- 2 ----'
        endif
        WKS(I)%ALFANR2 = DSQRT(DOT_PRODUCT(DOLDALFA,DOLDALFA))
        WKS(I)%D       = D
        WKS(I)%FSTOP   = FSTOP
        WKS(I)%NUMCOST = 0
        IF(FPROP.LT.FOTT) THEN
            CALL AGGIORNO_OTTIMO(N,XPROP,FPROP,XOTT,FOTT)
        ENDIF
        IF(PRINT_LEVEL >= 0) THEN
            WRITE(*,2130) NUMITER, NF, FOTT,'IN'
            WRITE(1,2130) NUMITER, NF, FOTT,'IN'
        ENDIF
    ENDDO
!--------------------------------------------------------
!    modificato il 23/9/2003
!--------------------------------------------------------
!    OPEN(99,FILE='MIN_LOCALI.txt',STATUS='REPLACE')
!    DO I = 1,IDIMWKS
!        WRITE(99,*) WKS(I)%X
!        WRITE(99,*) 'FOB = ',WKS(I)%FOB
!        WRITE(99,*) '--------------------------------'
!    ENDDO
!    CLOSE(99)
!    STOP
!--------------------------------------------------------
    DO I=1,N
        X(I)=XOTT(I)
    ENDDO
    MAXLS=100000000
    MODLS=1
!    --------------------
!      Ciclo principale
!    --------------------
    IF(PRINT_LEVEL >= 0) THEN
        WRITE(*,2070)
        WRITE(*,2080)
        WRITE(1,2070)
        WRITE(1,2080)
    ENDIF
2070 FORMAT('    ITER      NFTOT       FOTT      SALTO       ALFA       FMIN        FMAX')
2080 FORMAT('-----------------------------------------------------------------------------')
!              123456  123456789012  +1.2345E-02    OK     +1.2345E-02 +1.2345E-02 +1.2345E-02
2090 FORMAT(1X,  I6, 2X,  I12,  2X,  ES11.4, 4X, A2, 5X,  ES11.4, 1X,   ES11.4, 1X, ES11.4)
2130 FORMAT(1X,  I6, 2X,  I12,  2X,  ES11.4, 4X, A2)
100    FORMAT(/,1X,' GENERAZ.  N = ', I9,/)
101    FORMAT(/,1X,'  Attuale valore ottimo = ',D13.6,/)
102    FORMAT(3(:,1X,'XOTT(',I1,') =',D13.6,1X))
109    FORMAT(3(:,1X,'XOTT(',I2,') =',D13.6,1X))
6    FORMAT(/,1X,' NF=',I15,4X,' NPC=',I7,4X,' NLM=',I7,4X,' LS=',I7,/)
96    FORMAT(/,1X,'   MED = ',D13.6,'    VAR = ',D13.6,/)
    CSTEP ='  '
7    CONTINUE
8    CONTINUE
!--------------------------------------
!    stopping criterion
!--------------------------------------
!    calcola il max tra gli alfamax
!   o alfanr2 a seconda che normadue
!    sia falso o veroo
!--------------------------------------
    ALFA     = 0.0D0
    FSTOP    = 0.0D0
    FMIN     = 1.0D+30
    FMAX     =-1.0D+30
    DO I = 1,IDIMWKS
        IF(.NOT.MASCH(I)) THEN
            IF(WKS(I)%FSTOP > FSTOP) FSTOP = WKS(I)%FSTOP
            IF(NORMADUE) THEN
                IF(ALFA.LT.WKS(I)%ALFANR2) THEN
                    ALFA     = WKS(I)%ALFANR2
                ENDIF
            ELSE
                IF(ALFA.LT.WKS(I)%ALFAMAX) THEN
                    ALFA     = WKS(I)%ALFAMAX
                ENDIF
            ENDIF
!            IF(WKS(I)%FOB > FMAX) FMAX = WKS(I)%FOB
        ENDIF
        IF(WKS(I)%FOB > FMAX) FMAX = WKS(I)%FOB
        IF(WKS(I)%FOB < FMIN) THEN
            FMIN = WKS(I)%FOB
            IF(NORMADUE) THEN
                ALFAOTT = WKS(I)%ALFANR2
            ELSE
                ALFAOTT = WKS(I)%ALFAMAX
            ENDIF
        ENDIF
    ENDDO
    ALFAMAX = ALFA
    IF(PRINT_LEVEL >= 1) THEN
        WRITE(*,2070)
        WRITE(*,2080)
        WRITE(1,2070)
        WRITE(1,2080)
    ENDIF
    IF(PRINT_LEVEL >= 0) THEN
        WRITE(*,2090) NUMITER, NF, FOTT,CSTEP,ALFA,FMIN,FMAX
        WRITE(1,2090) NUMITER, NF, FOTT,CSTEP,ALFA,FMIN,FMAX
    ENDIF
    IF((ALFAMAX <= TOL).OR.(FSTOP <= FSTOPTOL).OR. &
       ((FOTT-FGLOB)/max(1.0d0,abs(fglob)) < tol)) THEN
        IF(NFOTT == 0) THEN
            NFOTT = NF
            F_OTT = FOTT
        ENDIF
    ENDIF
    !IF(NF >= MAXNF) THEN
    IF((ALFAMAX <= TOL).OR.(FSTOP <= FSTOPTOL).OR.(NUMITER >= MAXITER).OR.(NF >= MAXNF)) THEN
        IF(PRINT_LEVEL >= 0) THEN
            write(*,*) 'alfamax = ',alfamax
            write(1,*) 'alfamax = ',alfamax
            write(*,*) '  fstop = ',fstop
            write(1,*) '  fstop = ',fstop
            WRITE(1,100) NUMITER
            WRITE(*,100) NUMITER
            WRITE(1,*) FOTT
            WRITE(*,*) FOTT
            WRITE(1,101) FOTT
            WRITE(*,101) FOTT
            IF(N.LT.10) WRITE(1,102) (J,XOTT(J),J=1,N)
            IF(N.LT.10) WRITE(*,102) (J,XOTT(J),J=1,N)
            IF((N.GT.9).AND.(N.LT.100)) WRITE(1,109) (J,XOTT(J),J=1,N)
            IF((N.GT.9).AND.(N.LT.100)) WRITE(*,109) (J,XOTT(J),J=1,N)
            WRITE(1,6) NF,NPC,NLM,LS
            WRITE(6,6) NF,NPC,NLM,LS
            if(var2 < 0.0d0) then
                write(*,*) '---- 3 ----'
            endif
            VAR1=DSQRT(VAR2)
            WRITE(6,96) RMED,VAR1
            WRITE(1,96) RMED,VAR1
        ENDIF
        GO TO 170
    ENDIF
    !IF (FMIN /= FOTT) PAUSE
    IF(PRINT_LEVEL >= 1) THEN
        WRITE(*,*)'/---------------------------------\'
        WRITE(1,*)'/---------------------------------\'
        WRITE(*,*)'ALFAOTT = ',ALFAOTT,' FOTT = ',FOTT
        WRITE(1,*)'ALFAOTT = ',ALFAOTT,' FOTT = ',FOTT
!        WRITE(*,*) XOTT
!        WRITE(1,*) XOTT
        WRITE(*,*)'\---------------------------------/'
        WRITE(1,*)'\---------------------------------/'
        WRITE(*,*)
        WRITE(1,*)
    ENDIF
!--------------------------------------
    NUMITER = NUMITER + 1
    IF(PRINT_LEVEL >= 0) THEN
        IF(MOD(NUMITER,30)==0) THEN
            WRITE(*,2070)
            WRITE(*,2080)
            WRITE(1,2070)
            WRITE(1,2080)
        ENDIF
    ENDIF
!--------------------------------------
!    genera zeta random tra 0 e 1
!    e un punto xprop su cui calcolare
!    la f.ob.
!--------------------------------------
    CALL RANDOM_NUMBER(RRAND)
    ZETA=DBLE(RRAND) !RAN(IVAR)
    !ZETA=RAN(IVAR)
3020 CONTINUE
    DO I=1,N
        CALL RANDOM_NUMBER(RRAND)
        VETT(I)=DBLE(RRAND) !RAN(IVAR2)
        !VETT(I)=RAN(IVAR2)
        XPROP(I)=XINF(I)+VETT(I)*(XSUP(I)-XINF(I))
    ENDDO
    !CALL FUNCT(XPROP,N,FPROP)
    call  calfun(nipar, nfpar, ninit, ipar, fparebsd, initmeanval, expt, accum_e, mLPNH, mLPSH, &
                                N, XPROP, FPROP, verbose)
    NPC=NPC+1
    NF=NF+1
103    FORMAT(/,1X,'      Proposta di salto')
105    FORMAT(/,1X,'   Zeta =',D13.6,'   Tres =',D13.6,/)
!    ----------------------------
!      Calcolo media, varianza e
!      la temperatura del SA
!    ----------------------------
    RMED  = ((NPC-1.)*RMED+FPROP)/NPC
    RMED2 = ((NPC-2.)*RMED2+FPROP**2)/(NPC-1.)
    VAR2  = RMED2-(RMED**2)*(NPC/(NPC-1.))
    DIFF  = RMED-FOTT
    TRES  = DEXP(-TCOEFF*(RFAL/DIFF)*(FPROP-FOTT))
    temperatura = diff/rfal
    IF(FPROP.LE.FOTT) TRES=1.0D0
!--------------------------------------
!    se zeta e' minore o uguale a tres
!    allora accetta il punto e fa
!    partire una min. locale
!--------------------------------------
!    IF(.FALSE.) THEN
    IF(ZETA.LE.TRES) THEN
        NUMFAL = 0
        IF(PRINT_LEVEL >= 2) THEN
            WRITE(1,405)
            WRITE(*,405)
        ENDIF
405        FORMAT(1X,'    Proposta di salto accettata ',/)
        DO I=1,N
            X(I)=XPROP(I)
        ENDDO
        NLM     = NLM+1
!--------------------------------------
!        calcola l'indice imax della
!        componente di wks contenente
!        il valore di fob piu' alto
!--------------------------------------
        FMAX    =-1.0D+30
        DO I = 1,IDIMWKS
!            IF((WKS(I)%FOB > FMAX)) THEN
            IF((WKS(I)%FOB > FMAX) .AND. (.NOT.MASCH(I))) THEN
                FMAX = WKS(I)%FOB
                IMAX = I
            ENDIF
        ENDDO
        ALFA  = WKS(1)%ALFAMAX
        FSTOP = WKS(1)%FSTOP
        DO J = 2,IDIMWKS
            IF(FSTOP.LT.WKS(J)%FSTOP) FSTOP = WKS(J)%FSTOP
            IF(ALFA.LT.WKS(J)%ALFAMAX) THEN
                ALFA      =  WKS(J)%ALFAMAX
                DOLDALFA  =  WKS(J)%DOLDALFA
            ENDIF
        ENDDO
!        DO K = 1,N
!            ALFA=WKS(1)%DOLDALFA(K)
!            DO J = 1,IDIMWKS
!               IF(ALFA.LT.WKS(J)%DOLDALFA(K)) THEN
!                   ALFA      =  WKS(J)%DOLDALFA(K)
!               ENDIF
!            ENDDO
!            DOLDALFA(K) = ALFA
!        ENDDO
        ALFA = ALFAMAX
!        IF(NORMADUE) THEN
!            ALFA = WKS(IMAX)%ALFANR2
!        ELSETABELLA
!            ALFA = WKS(IMAX)%ALFAMAX
!        ENDIF
        CALL INTERFACCIA(N,X,F,ALFA,DOLDALFA,D,FFSTOP,FSTOP,XINF,XSUP,FOTT,ALFAMAX,ALFAOTT,XOTT,WKS,IDIMWKS,ISTOP,MASCH,MAXNF,fglob,&
        ipar,fparebsd,initmeanval,ninit,nipar,nfpar,expt,accum_e,mLPNH,mLPSH,verbose,calfun)
        IF(F.LT.FOTT) THEN
            CALL AGGIORNO_OTTIMO(N,X,F,XOTT,FOTT)
            ISTOP = 1
        ENDIF
        IF((F.LT.WKS(IMAX)%FOB).AND.(ISTOP.NE.2)) THEN
!--------------------------------------
!            se la min. produce un punto
!            migliore del peggiore
!            lo sostituisce
!--------------------------------------
            WKS(IMAX)%X       = X
            WKS(IMAX)%FOB     = F
            WKS(IMAX)%ALFAMAX = ALFA
            WKS(IMAX)%DOLDALFA= DOLDALFA
            WKS(IMAX)%D          = D
            WKS(IMAX)%FSTOP      = FFSTOP
            if(DOT_PRODUCT(DOLDALFA,DOLDALFA) < 0.0d0) then
                write(*,*) '---- 4 ----'
            endif
            WKS(IMAX)%ALFANR2 = DSQRT(DOT_PRODUCT(DOLDALFA,DOLDALFA))
            WKS(IMAX)%NUMCOST = 0
            CSTEP = 'OK'
            MASCH(IMAX) = .FALSE.
            GO TO 7
        ELSE
!--------------------------------------
!            non accetta il punto
!            prodotto dalla minimizzazione
!--------------------------------------
            RNUMFAL  = RNUMFAL  + 1.0D0
            ICONTFAL = ICONTFAL + 1
            RFAL     = RFAL     + 1.0D0/RNUMFAL
            IDFAL    = 1
            CSTEP = 'NO'
        ENDIF
    ELSE
!--------------------------------------
!    altrimenti (zeta > tres) scarta
!    il punto proposto e aggiorna
!    il cont. numfal
!--------------------------------------
        NUMFAL   = NUMFAL   + 1
!        RNUMFAL  = RNUMFAL  + 1.0D0
!        ICONTFAL = ICONTFAL + 1
!        RFAL     = RFAL     + 1.0D0/RNUMFAL
!        IDFAL    = 1
    ENDIF
!====================================================
!   QUI DEVO FARE UNA RICERCA LUNGO GLI ASSI
!    SU I PUNTI DEL WKS.
!   SOLOSULPEGG = .TRUE.  --> LA FA SOLO SU QUELLO
!                               CON ALFA PEGGIORE
!                = .FALSE. --> LA FA SU TUTTI
!====================================================
    if(.NOT.SOLOSULPEGG) then !fai la ricerca lungo gli assi per tutti
                              !i punti dell'array
        IF(NUMFAL >= 0) THEN
            NUMFAL  = 0
            FMAX_EFF    =-1.0D+30
            DO J = 1,IDIMWKS
!                IF(.NOT.MASCH(J)) THEN
                    IF(WKS(J)%FOB > FMAX_EFF) THEN
                        FMAX_EFF = WKS(J)%FOB
                    ENDIF
!                ENDIF
                IF(WKS(J)%FOB <= FOTT) IOTT = J
                RA(J)    = WKS(J)%FOB
                IPERM(J) = J
            ENDDO
!-------------------------------------------------
! ORDINO RA E RESTITUISCE RB ORDINATO
! IN IPERM CI SONO LE POSIZIONI DEGLI ELEMENTI
! DI RB IN RA
!-------------------------------------------------
            call qsortd(RA,IPERM,IDIMWKS)
            DO I = 1,IDIMWKS
                RB(I) = RA(IPERM(I))
            ENDDO
            !CALL DSVRGP(IDIMWKS,RA,RB,IPERM)
!            MASCH = .FALSE.
            I = 1
            J = 2
            DO WHILE ( J <= IDIMWKS )
                !CONFRONTO J,I --> MASCH
                IF (.NOT.MASCH(IPERM(J))) THEN
                    L_F_VICINI = (DABS(RB(I)-RB(J))/(DMAX1(1.D-8,DABS(RB(J)) )) ).LE.1.D-1
!                    L_F_VICINI = L_F_VICINI.AND.((DSQRT(&
!                        DOT_PRODUCT(WKS(IPERM(I))%X-WKS(IPERM(J))%X,WKS(IPERM(I))%X-WKS(IPERM(J))%X)) <= 1.D-2)& !ERA 1.D-1
!                        .OR. (WKS(IPERM(J))%ALFAMAX.LE.1.D-1*WKS(IPERM(I))%ALFAMAX))
                    L_F_VICINI = L_F_VICINI.AND.((DSQRT(                                                    &
                        DOT_PRODUCT(WKS(IPERM(I))%X-WKS(IPERM(J))%X,WKS(IPERM(I))%X-WKS(IPERM(J))%X)) <= 1.D-1))
    !                MASCH(IPERM(J)) = MASCH(IPERM(J)).OR.L_F_VICINI
                    IF (L_F_VICINI) THEN
                        IF ( (WKS(IPERM(J))%ALFAMAX <= WKS(IPERM(I))%ALFAMAX) .OR. (I == 1) ) THEN
                            MASCH(IPERM(J))=.TRUE.
                            J = J+1
                        ELSE
                            MASCH(IPERM(I)) =.TRUE.
                            I = J
                            J = J+1
                        ENDIF
                    ELSE
                        I = J
                        J = J+1
                    ENDIF
                ELSE
                    J = J+1
                ENDIF
            ENDDO
            DO I = 1,IDIMWKS
                IF(NORMADUE) THEN
                    ALFA     = WKS(I)%ALFANR2
                ELSE
                    ALFA     = WKS(I)%ALFAMAX
                ENDIF
                DOLDALFA = WKS(I)%DOLDALFA
                D        = WKS(I)%D
                X        = WKS(I)%X
                F        = WKS(I)%FOB
                IF(I.NE.IOTT) THEN
                    RA(I) = (F-FOTT)/DMAX1(1.D-3,DMIN1(DABS(F),DABS(FOTT)) )
                    RB(I) = DSQRT(DOT_PRODUCT(X-XOTT,X-XOTT))
                    L_F_DISTANTI = ((F-FOTT)/DMAX1(1.D-3,DMIN1(DABS(F),DABS(FOTT)) ) ).GE.1.D+1
!                    L_F_DISTANTI = L_F_DISTANTI.AND.(ALFA <= 1.D-4)
                    L_F_DISTANTI = L_F_DISTANTI.AND.(ALFA <= 1.D+1*ALFAOTT)
                    L_F_VICINI = ((F-FOTT)/DMAX1(1.D-3,DABS(FOTT) ) ).LE.1.D-1
!                    L_F_VICINI = L_F_VICINI.AND.((DSQRT(DOT_PRODUCT(X-XOTT,X-XOTT)) <= 1.D-1) &
!                                .OR. (ALFA.LE.1.D-1*ALFAOTT))
                    L_F_VICINI = L_F_VICINI.AND.( (DSQRT(DOT_PRODUCT(X-XOTT,X-XOTT)) <= 1.D-1))
                    NON_MINIMIZZ = L_F_DISTANTI .OR. L_F_VICINI
!                    NON_MINIMIZZ = L_F_DISTANTI.AND.(ALFA.LE.1.D-4)
                ELSE
                    NON_MINIMIZZ = .FALSE.
                    RA(I) = -1.D0
                    RB(I) = -1.D0
                ENDIF
                MASCH(I) = MASCH(I) .OR. NON_MINIMIZZ
!            ENDDO
!--------------------------------------------
!    apro il file per fare i controlli
!    sull'alfamax
!--------------------------------------------
            IF (PRINT_LEVEL >= 1) THEN
                open(99,FILE='alfamax.txt',STATUS='REPLACE')
                DO J = 1,IDIMWKS
                    write(99,1999) J,wks(J)%alfamax,wks(J)%fob,masch(J), RA(J), RB(J)
                    write(*,1999) J,wks(J)%alfamax,wks(J)%fob,masch(J), RA(J), RB(J)
                enddo
            1999 format(1x,i3,1x,es18.10,1x,es18.10,1x,l1,1x, es9.2, 1x, es9.2)
            !--------------------------------------------
            !    apro il file per fare i controlli
            !    sull'alfamax
            !--------------------------------------------
                close(99)
                !pause
            ENDIF
!            DO I = 1,IDIMWKS
                IF(NORMADUE) THEN
                    ALFA     = WKS(I)%ALFANR2
                ELSE
                    ALFA     = WKS(I)%ALFAMAX
                ENDIF
                DOLDALFA = WKS(I)%DOLDALFA
                D        = WKS(I)%D
                X        = WKS(I)%X
                F        = WKS(I)%FOB
!                IF(.TRUE.) THEN
!                IF((ALFA.GT.TOL).AND..NOT.MASCH(I))    THEN
!                IF((ALFA.GT.TOL).AND..NOT.MASCH(I).AND. (ALFA.GT.1.D-3*ALFAMAX))    THEN
                IF(     ((ALFA.GT.TOL).AND..NOT.MASCH(I).AND. (ALFA.GT.1.D-1*ALFAMAX)).OR. &
                        ((ALFA.GT.TOL).AND..NOT.MASCH(I).AND. (I == IOTT)))    THEN
                    MASCH(I) = .FALSE.
!                    FMAX_EFF = F
!                    WRITE(*,*)'X=',X
!                    WRITE(*,*)'F=',F
                    CALL RICERCA_LUNGO_ASSI(N,X,F,ALFA,DOLDALFA,D,FSTOP,XINF,XSUP,FMAX_EFF,&
                    ipar,fparebsd,initmeanval,ninit,nipar,nfpar,expt,accum_e,mLPNH,mLPSH,verbose,calfun)
                    if(f > fmax_eff) then
                        write(*,*) '---> 1 <--- diff = ',f-fmax_eff
!                        pause
                    endif
!                    WRITE(*,*)'X=',X
!                    WRITE(*,*)'F=',F
                    WKS(I)%X       = X
                    WKS(I)%FOB     = F
!                    PAUSE
                    !IF(WKS(I)%ALFAMAX > ALFA) THEN
                    !    WRITE(*,*) '\/\/\/\/\/ ',F,' \/\/\/\/\/\ ',FMAX_EFF !/\/\/\/\/', I
                    !ENDIF
                    IF(ALFA >= WKS(I)%ALFAMAX) THEN
                        WKS(I)%NUMCOST = WKS(I)%NUMCOST + 1
                    ELSE
                        WKS(I)%NUMCOST = 0
                    ENDIF
                    WKS(I)%ALFAMAX = ALFA
                    WKS(I)%DOLDALFA= DOLDALFA
                    WKS(I)%D       = D
                    WKS(I)%FSTOP   = FSTOP
                    if(DOT_PRODUCT(DOLDALFA,DOLDALFA) < 0.0d0) then
                        write(*,*) '---- 5 ----'
                    endif
                    WKS(I)%ALFANR2 = DSQRT(DOT_PRODUCT(DOLDALFA,DOLDALFA))
                    IF(F.LT.FOTT) THEN
                        CALL AGGIORNO_OTTIMO(N,X,F,XOTT,FOTT)
                    ENDIF
                    IF(WKS(I)%NUMCOST <= -1) THEN
                        DO WHILE (ALFA >= WKS(I)%ALFAMAX)
                            CALL RICERCA_LUNGO_ASSI(N,X,F,ALFA,DOLDALFA,D,FSTOP,XINF,XSUP,FMAX_EFF,&
                        ipar,fparebsd,initmeanval,ninit,nipar,nfpar,expt,accum_e,mLPNH,mLPSH,verbose,calfun)
                            if(f > fmax_eff) then
                                write(*,*) '---> 2 <---'
!                                pause
                            endif
                            WKS(I)%X       = X
                            WKS(I)%FOB     = F
                            WKS(I)%ALFAMAX = ALFA
                            WKS(I)%DOLDALFA= DOLDALFA
                            WKS(I)%D       = D
                            WKS(I)%FSTOP   = FSTOP
                            if(DOT_PRODUCT(DOLDALFA,DOLDALFA) < 0.0d0) then
                                write(*,*) '---- 6 ----'
                            endif
                            WKS(I)%ALFANR2 = DSQRT(DOT_PRODUCT(DOLDALFA,DOLDALFA))
                            WRITE(*,*) ALFA,F
                        ENDDO
                        WKS(I)%NUMCOST = 0
                    ENDIF
                ELSE
                    IF(.FALSE.) THEN
!                    IF(NON_MINIMIZZ) THEN
                        IF(PRINT_LEVEL >= 10) THEN
                            WRITE(1,*) 'SOSTITUISCO IL PUNTO ',I
                        ENDIF
                        CALL GENERA_PUNTO_SA(N,XPROP,FPROP,XINF,XSUP,FOTT,TCOEFF,IVAR,IVAR2, &
                                     VAR2,RMED,RMED2,NLM,NUMFAL,RFAL,RNUMFAL,ICONTFAL,IDFAL,NPC,NF,&
                            ipar,fparebsd,initmeanval,ninit,nipar,nfpar,expt,accum_e,mLPNH,mLPSH,verbose,&
                              calfun)
                        ALFA     = 0.0D0
                        FSTOP    = 0.0D0
                        DO J = 1,IDIMWKS
                            IF(.NOT.MASCH(J)) THEN
                                IF(WKS(J)%FSTOP > FSTOP) FSTOP = WKS(J)%FSTOP
                                IF(NORMADUE) THEN
                                    IF(ALFA.LT.WKS(J)%ALFANR2) THEN
                                        ALFA     = WKS(J)%ALFANR2
                                    ENDIF
                                ELSE
                                    IF(ALFA.LT.WKS(J)%ALFAMAX) THEN
                                        ALFA     = WKS(J)%ALFAMAX
                                    ENDIF
                                ENDIF
                            ENDIF
                        ENDDO
!                        ALFAMAX = ALFA
                        ALFA = ALFAMAX
                        CALL INTERFACCIA(N,XPROP,FPROP,ALFA,DOLDALFA,D,FFSTOP,FSTOP,XINF,    &
                            XSUP,FOTT,ALFAMAX,ALFAOTT,XOTT,WKS,IDIMWKS,ISTOP,MASCH,MAXNF,fglob,&
                        ipar,fparebsd,initmeanval,ninit,nipar,nfpar,expt,accum_e,mLPNH,mLPSH,verbose,&
                        calfun)
                        WKS(I)%X       = XPROP
                        WKS(I)%FOB     = FPROP
                        WKS(I)%ALFAMAX = ALFA
                        WKS(I)%DOLDALFA= DOLDALFA
                        WKS(I)%D       = D
                        WKS(I)%FSTOP   = FFSTOP
                        if(DOT_PRODUCT(DOLDALFA,DOLDALFA) < 0.0d0) then
                            write(*,*) '---- 7 ----'
                        endif
                        WKS(I)%ALFANR2 = DSQRT(DOT_PRODUCT(DOLDALFA,DOLDALFA))
                        IF(FPROP.LT.FOTT) THEN
                            CALL AGGIORNO_OTTIMO(N,XPROP,FPROP,XOTT,FOTT)
                        ENDIF
                        MASCH(I) = .FALSE.
                    ELSE
                        MASCH(I) = .TRUE.
                    ENDIF
                ENDIF
            ENDDO
        ENDIF
    else !fai la ricerca lungo gli assi solo per
         !il punto con l'alfa maggiore
        ALFA     = 0.0D0
        FMIN     = 1.0D+30
        FMAX     =-1.0D+30
        DO I = 1,IDIMWKS
            IF(.NOT.MASCH(I)) THEN
                IF(NORMADUE) THEN
                    IF(ALFA.LT.WKS(I)%ALFANR2) THEN
                        ALFA     = WKS(I)%ALFANR2
                        DOLDALFA = WKS(I)%DOLDALFA
                        IMAX     = I
                    ENDIF
                ELSE
                    IF(ALFA.LT.WKS(I)%ALFAMAX) THEN
                        ALFA     = WKS(I)%ALFAMAX
                        DOLDALFA = WKS(I)%DOLDALFA
                        IMAX     = I
                    ENDIF
                ENDIF
                IF(WKS(I)%FOB < FMIN) FMIN = WKS(I)%FOB
                IF(WKS(I)%FOB > FMAX) FMAX = WKS(I)%FOB
            ENDIF
        ENDDO
        D    = WKS(IMAX)%D
        X    = WKS(IMAX)%X
        F    = WKS(IMAX)%FOB
        CALL RICERCA_LUNGO_ASSI(N,X,F,ALFA,DOLDALFA,D,FSTOP,XINF,XSUP,FMAX_EFF,&
        ipar,fparebsd,initmeanval,ninit,nipar,nfpar,expt,accum_e,mLPNH,mLPSH,verbose,calfun)
        if(f > fmax_eff) then
            write(*,*) '---> 3 <---'
!            pause
        endif
        WKS(IMAX)%X       = X
        WKS(IMAX)%FOB     = F
        WKS(IMAX)%ALFAMAX = ALFA
        WKS(IMAX)%DOLDALFA= DOLDALFA
        WKS(IMAX)%D       = D
        WKS(IMAX)%FSTOP   = FSTOP
        if(DOT_PRODUCT(DOLDALFA,DOLDALFA) < 0.0d0) then
            write(*,*) '---- 8 ----'
        endif
        WKS(IMAX)%ALFANR2 = DSQRT(DOT_PRODUCT(DOLDALFA,DOLDALFA))
        IF(F.LT.FOTT) THEN
            CALL AGGIORNO_OTTIMO(N,X,F,XOTT,FOTT)
        ENDIF
    endif
    IF(CSTEP.NE.'NO') CSTEP = 'KO'
    GO TO 8
170 CONTINUE
    IF(NFOTT == 0) THEN
        NFOTT = NF
        F_OTT = FOTT
    ENDIF
    LSTOT  = LSTOT  + LS
    NFTOT  = NFTOT  + NF
    NPCTOT = NPCTOT + NPC
    NLMTOT = NLMTOT + NLM
    VECTNF(IT)   = NF
    VECTFVAL(IT) = FOTT
    VECTNFOTT(IT)= NFOTT
    VECTF_OTT(IT)= F_OTT
    DO I = 1,IDIMWKS
        DEALLOCATE(WKS(I)%X)
        DEALLOCATE(WKS(I)%DOLDALFA)
        DEALLOCATE(WKS(I)%D)
    ENDDO
    DEALLOCATE(WKS,MASCH)
171 CONTINUE
    sumiter  = 0.D0 ; sumnf = 0 ; sumtime = 0.0D0
    f_min1   = 1.D+30
    f_minott = 0.D0
    f_min    = 1.D+30
    f_mintot = 0.D0
    f_max    = -1.D+30
    DO IT=1,Iruns
        SUMNF = SUMNF + VECTNFOTT(IT)
        f_mintot = f_mintot + vectfVAL(IT)
        f_minott = f_minott + vectf_ott(IT)
        IF (f_min.GT.vectfVAL(IT)) f_min = vectfVAL(IT)
        IF (f_min1.GT.vectf_ott(IT)) f_min1 = vectf_ott(IT)
        IF (f_max.LT.vectfVAL(IT)) f_max = vectfVAL(IT)
    END DO
    !write(TABELLA,2030) nomefun, n, NFTOT/IRUNS, SUMNF/IRUNS
    F_MINTOT = F_MINTOT/IRUNS
    F_MINOTT = F_MINOTT/IRUNS
    !IF (DABS(F_MIN).LT.1.D-3) THEN
!        WRITE(TABELLA,2110) F_MIN
!    ELSE
!        WRITE(TABELLA,2100) F_MIN
!    ENDIF
!    IF (DABS(F_MINTOT).LT.1.D-3) THEN
!        WRITE(TABELLA,2110) F_MINTOT
!    ELSE
!        WRITE(TABELLA,2100) F_MINTOT
!    ENDIF
!    IF (DABS(F_MIN1).LT.1.D-3) THEN
!        WRITE(TABELLA,2110) F_MIN1
!    ELSE
!        WRITE(TABELLA,2100) F_MIN1
!    ENDIF
!    IF (DABS(F_MINOTT).LT.1.D-3) THEN
!        WRITE(TABELLA,2110) F_MINOTT
!    ELSE
!        WRITE(TABELLA,2100) F_MINOTT
!    ENDIF
!    WRITE(TABELLA,2110) (F_MINOTT-fglob)/max(1.0d0,abs(fglob))
!
    !if((F_MINOTT-fglob)/max(1.0d0,abs(fglob))<1.d-4) then
!        iok = 1
!    else
!        iok = 0
!    endif
    NFAILS = 0
    DO IT=1,IRUNS
        IF(DABS(VECTFVAL(IT)-F_MIN).GT.1.0d-2) NFAILS = NFAILS+1
    ENDDO
    !WRITE(TABELLA,2120) NFAILS
!    WRITE(TABELLA,2180)
!    DEALLOCATE(XINF,XSUP)
    DEALLOCATE(X,XOTT,Z,VETT,XPROP,DOLDALFA,D)
    DEALLOCATE(RA,RB,IPERM)
2100 FORMAT(' & ',ES12.5,$)
2110 FORMAT(' & ',D10.3,$)
2030 FORMAT(A40,' & ',I2,' & ',I6,' & ',I6, $)
!2100 FORMAT(' & ',F13.4,$)
!2110 FORMAT(' & ',D9.3,$)
2120 FORMAT(' & ',I4,'\\')
2180 FORMAT(' \\ ')
2140 FORMAT(I3,'  ',$)
2150 FORMAT(ES11.4,'  ',$)
2160 FORMAT(I6,'  ',$)
2170 FORMAT(I6,'  ',I3)
691 FORMAT(/,1X,' NFTOT=',I7,4X,' NPCTOT=',I7,4X,' NLMTOT=',I7,4X,' LSTOT=',I7,/)
END SUBROUTINE SENZADERGLOB
All Procedures
adhisteq AGGIORNO_OTTIMO alogam altmov altmov BackProjection bakvec balanc balbak bandr bandv BarrelDistortion bisect bobyqa bobyqa bobyqb bobyqb bqr ButterflyMask9x9 CalcHoughLUT CalcKINPEDPatternSingle Calckvectorcone Calckvectortrace CalcR CalcRLocal CardIntersection cbabk2 cbal cdiv cg ch cinvit CLerror_check CLinit_PDCCQ CLquery_platform_info CLread_source_file combak comhes comlr comlr2 comqr comqr2 cortb corth csroot ctfped_writeFile CubochoricNeighbors cumul_histogram DD_Density DD_Estep DD_getQandL DD_Mstep delete_FZlist Denoise_Pattern Denoise_PED DI_EMforDD DI_Init DI_RotateToMu DI_SampleDD DI_Similarity_Classifier EBSD4calfun EBSDcalfun ECCICalcSgh ECPcalfun efitEBSDWrapper efitECPWrapper EI elmbak elmhes eltran EMsoftCgetEBSDmaster EMsoftCgetEBSDPatterns EMsoftCgetECPatterns EMsoftCgetMCOpenCL Eshelby_disp FCORE figi figi2 ForwardProjection FPHON FSCATT GENERA_PUNTO_SA GetAverageOrientationNameList GetConvertOrientationsNameList getDDDensityLBM GetDictIndxOpenCLNameList getDisorientationAngle getDisorientationAngleAxis getDisorientationAngleAxisTwoPhases getDisorientationAngleDouble getDisorientationAngleSingle GetDisorientationsNameList GetDvsDNameList GetEBSDclusterNameList GetEBSDdetparmscanNameList GetEBSDFullNameList GetEBSDIndexingNameList GetEBSDMasterNameList GetEBSDMasterOpenCLNameList GetEBSDNameList GetEBSDoverlapNameList getEBSDPatterns getEBSDPatterns2 getEBSDPatternsWrapper GetECCINameList getECPatterns getECPatternsWrapper GetECPIndexingNameList GetECPMasterNameList GetECPNameList GetECPpatternNameList GetECPSingleNameList GetECPZANameList GetEMDPFit4NameList GetEMDPFitNameList getEulersfromFile GetFitOrientationPSNameList getFZtypeandorder GetKAMNameList GetkinematicalNameList GetKosselMasterNameList GetKosselNameList getKosselPatterns getKosselPatternsWrapper GetLACBEDNameList GetMCCLfoilNameList GetMCCLMultiLayerNameList GetMCCLNameList GetMCCLsphereNameList GetMCLIPSSNameList GetMCNameList GetMultiPhaseNameList GetOrientationSimilarityNameList GetOrientationVizNameList GetPEDIndxNameList GetPEDkinNameList GetPEDZANameList GetPFInversionNameList GetRefineOrientationNameList GetreflectorNameList GetRFZNameList GetSRdefectNameList GetSTEMDCINameList GetTKDIndexingNameList GetTKDMasterNameList GetTKDNameList GETWK GetZAdefectNameList HiPassFilter HoughTransform hqr hqr2 htrib3 htribk htrid3 htridi image_entropy image_histogram image_jointentropy image_jointhistogram image_mutualinformation imtql1 imtql2 imtqlv init_dislocation_data init_Einclusion_data init_foil_data init_inclusion_data init_stacking_fault_data init_STEM init_STEM_ZA init_void_data init_YSH_dislocation_data initialize_foil_geometry Initialize_ReflectionList Initialize_ReflectionList Initialize_ReflectionList_EwaldSweep InitializeDefects InitializeEshelbyInclusion InnerProdGPU insideCubeHexFZ insideCubicFZ insideCubicMFZ insideCyclicFZ insideDihedralFZ insideDihedralMFZ INTERFACCIA InversionDivision invit IsinsideFZ IsinsideMFZ Jaccard_Distance JSON_cleanuppointers JSON_failtest JSON_initpointers JSON_minify JSON_writeNMLdoubles JSON_writeNMLintegers JSON_writeNMLreals JSONgetDouble JSONgetDoubleVector JSONreadDefectFile JSONreadDouble JSONreadDoubleVec JSONreadEBSDclusterNameList JSONreadEBSDMasterNameList JSONreadEBSDNameList JSONreadEBSDoverlapNameList JSONreadECPMasterNameList JSONreadFoilData JSONreadInteger JSONreadIntegerVec JSONreadKosselMasterNameList JSONreadKosselNameList JSONreadLogical JSONreadMCCLMultiLayerNameList JSONreadMCCLNameList JSONreadMCNameList JSONreadReal JSONreadRealVec JSONreadreflectorNameList JSONreadString JSONwriteDictIndxOpenCLNameList JSONwriteEBSDclusterNameList JSONwriteEBSDMasterNameList JSONwriteEBSDNameList JSONwriteECCINameList JSONwriteECPMasterNameList JSONwriteECPNameList JSONwriteECPpatternNameList JSONwriteKosselMasterNameList JSONwriteKosselNameList JSONwriteLACBEDNameList JSONwriteMCCLMultiLayerNameList JSONwriteMCCLNameList JSONwriteMCNameList JSONwritePEDkinNameList JSONwritePEDZANameList JSONwriteRFZNameList LINESEARCH_INVERTI linesearchbox_cont logCp MAINBOX1 MAINBOX2 makedislocation makestackingfault makestackingfaultECCI makeYSHdislocation makeYSHdislocation MC_concatenateMuellerMatrices MC_get_AD_from_EO MC_get_AuxiliaryAngle MC_get_basicMuellerMatrix MC_get_diattenuator MC_get_EllipticityAngle MC_get_EO_from_AD MC_get_OrientationAngle MC_get_PhaseShiftAngle MC_get_Polarization MC_get_retarder MC_get_rotator MC_get_Stokes_AD MC_get_Stokes_EO MC_print_MuellerMatrix MC_propagateStokesVector MC_rotate_MuellerMatrix minfit NANCHK ortbak orthes ortran PGM_Write_File POIDEV PoVRay_addCubochoricCube PoVRay_addCylinder PoVRay_addEulerBox PoVRay_addReferenceFrame PoVRay_addSphere PoVRay_addWireFrameSphere PoVRay_declare_DF3file PoVRay_drawFZ PoVRay_getpos_FZ222 PoVRay_getpos_FZ23 PoVRay_getpos_FZ32 PoVRay_getpos_FZ422 PoVRay_getpos_FZ432 PoVRay_getpos_FZ622 PoVRay_initFZ2 PoVRay_initFZ3 PoVRay_initFZ4 PoVRay_initFZ6 PoVRay_openFile PoVRay_setCamera PoVRay_setLightSource PoVRay_write_DF3file prelim prelim PrintTime pythag qsortd qzhes qzit qzval qzvec r8_swap r8mat_print r8mat_print_some r8vec2_print r8vec_print ran randDDMarginal randUniformSphere ratqr read_apb_data read_STEM_data read_YSH_dislocation_data rebak rebakb reduc reduc2 ReduceDisorientationtoMFZ ReduceOrientationtoCubicEFZ ReduceOrientationtoRFZ rescue rescue rg rgg RI1 RI2 RICERCA_LUNGO_ASSI RIH1 RIH2 RIH3 rng_seed rng_uniform rs rsb rsg rsgab rsgba rsm rsp rspp rst rt sample_Cone sample_isoCube sample_isoCubeFilled SamplefcctwinRFZ SampleIsoMisorientation SampleRFZ SampleRFZtwin SENZADERGLOB SSORT STOP svd Time_estimate Time_remaining Time_report Time_reset Time_start Time_stop Time_tick Time_tock timestamp timestamp tinvit tql1 tql2 tqlrat trbak1 trbak3 tred1 tred2 tred3 tridib trsbox trsbox tsturm update update VMFMeanDirDensity WatsonMeanDirDensity WEKO YSHDisp YSHDisp
Call graph
senzaderglob calls qsortd, genera_punto_sa, 3, dexp, aggiorno_ottimo, ricerca_lungo_assi, interfaccia
genera_punto_sa calls dexp
ricerca_lungo_assi calls mainbox1
interfaccia calls mainbox2
mainbox1 calls linesearchbox_cont, dfloat
mainbox2 calls linesearchbox_cont